### ISSUE TITLE
cannot mount EBS volume

### ISSUE THREAD

**Issue by rems0** [aws/aws-parallelcluster#1001]
**Environment:**
 - AWS ParallelCluster 2.3.1
 - OS: CentOS7
 - Scheduler: slurm
 - Master instance type: m5.large
 - Compute instance type: c5.large

**Bug description and how to reproduce:**
Mounting ebs volume fails with:
botocore.exceptions.ClientError: An error occurred (IncorrectInstanceState) when calling the AttachVolume operation: Cannot attach volume 'vol-0acee4a6e1ee62c81' with Marke
tplace codes as the instance 'i-09616c8a184c64e66' is not in the 'stopped' state.
---- End output of /usr/local/sbin/attachVolume.py vol-0acee4a6e1ee62c81 ----

**Additional context:**
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/3074691/cfn-init-cmd.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/3074692/cfn-init.log)
[cfn-wire.log](https://github.com/aws/aws-parallelcluster/files/3074693/cfn-wire.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/3074694/cloud-init.log)
[config.txt](https://github.com/aws/aws-parallelcluster/files/3074697/config.txt)
[node-post-install-setup.sh.txt](https://github.com/aws/aws-parallelcluster/files/3074706/node-post-install-setup.sh.txt)

The volume is in the same availability zone as the master and has state "available".

Thanks,
Richard

**Comment by lukeseawalker** [comment]
Hi @rems0,
the reason is that you are trying to attach a volume with a Marketplace product code and the prerequisites listed [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-attaching-volume.html) are not satisfied. 
From the logs you are trying to attach the volume of the marketplace Centos7 AMI. Is there any reason why doing that? Couldn't you use the public image instead of the Marketplace one (see https://wiki.centos.org/Cloud/AWS)?
