### ISSUE TITLE
When using Slurm, jobs never complete

### ISSUE THREAD

**Issue by hellmersjl3ds** [aws/aws-parallelcluster#1110]
**Environment:**
 - aws-parallelcluster-2.3.1
 - OS: CentOS Linux release 7.6.1810 (Core)
 - Scheduler: Slurm
 - Master instance type: m5.2xlarge
 - Compute instance type: p3.8xlarge

**Bug description and how to reproduce:**
Jobs submitted by the centos user (or any other user) keep running and running.  When using scancel to stop the job, the jobs go into CG status, and I need to down and resume the compute nodes

**Additional context:**
 - pre/post-install scripts, if any: There is one.

**Comment by hellmersjl3ds** [comment]
[pp-grid-post-config - DEIDENTIFIED.txt](https://github.com/aws/aws-parallelcluster/files/3267242/pp-grid-post-config.-.DEIDENTIFIED.txt)

**Comment by lukeseawalker** [comment]
Hi @hellmersjl3ds,
this sounds like a scheduler issue than a ParallelCluster one. 
I would start looking at the Slurm logs to check if there is something interesting. 
Jobs stuck in CG are in completing status, it usually means that they cannot be terminated, probably because of an I/O operation, see https://slurm.schedmd.com/troubleshoot.html#completing for details.

Are you seeing the issue with every job? Also the simplest ones like submitting a sleep command?

I have rapidly looked at the post install script.
Did you verified that NFS shares are working after your changes?

(minor) since the first version of ParallelCluster, Ganglia is disabled by default.

**Comment by hellmersjl3ds** [comment]
I modified my post install script to NOT run NFS configuration on the master node.  I think the restart of NFS on that node was causing Slurm to get confused.  Once I did that things started working correctly.

**Comment by lukeseawalker** [comment]
cool, thank you for the update.
