### ISSUE TITLE
a task queue on the master node

### ISSUE THREAD

**Issue by notestaff** [aws/aws-parallelcluster#1118]
Currently, only ComputeNodes can run tasks.  Could you add the option to create a job queue on the MasterServer, with a specified number of slots?  [StarCluster](http://star.mit.edu/cluster/) had this, and it was useful.  For development/debugging, this allows a quick trial run, without the overhead of starting a compute node.  Also, the MasterServer compute capacity is often underutilized (I define it to be a somewhat high-end node when using NFS).  Thanks!

**Comment by notestaff** [comment]
P.S. Most important, if the MasterServer is the NFS server, it should be in the same Placement Group of type cluster with compute nodes (i.e. placement=cluster).  But if it has a different node type, you're likely to get errors about insufficient capacity.  So, if you want to use high-end compute nodes, you have to use a high-end MasterServer node, which means you'll want to use it as a ComputeNode when possible.  Which is also why you'd want the option of running the MasterServer as a spot instance ( #1092 ).

**Comment by sean-smith** [comment]
This is a great idea

**Comment by sean-smith** [comment]
See http://star.mit.edu/cluster/docs/0.93.3/plugins/sge.html#monitoring-cluster-usage for reference on StarCluster's implementation

**Comment by enrico-usai** [comment]
I'm going to close this issue. Each cluster has only a single head node and it is needed to manage other responsibilities (such as hosting the scheduler controller, NFS sharing and NICE DCV endpoint) we are choosing to be deliberate in not introducing additional responsibilities (like job submission) that are likely to introduce additional failure modes for the head node (and consequently the cluster). See also [Head Node Instance Type - Best Practices](https://github.com/aws/aws-parallelcluster/wiki/Best-Practices#head-node-instance-type) wiki page.

As part of [3.0.0 release](https://github.com/aws/aws-parallelcluster/releases/tag/v3.0.0) we removed the possibility to have both head node and compute nodes in the same placement group to avoid insufficient capacity issues and to better distinguish nodes responsibilities. If having issues with networking due to NFS sharing we suggest to use EFS (see [when to Choose Amazon EFS: aka EFS vs EBS vs S3](https://aws.amazon.com/efs/when-to-choose-efs/)) or FSx for Lustre.
