### ISSUE TITLE
Auto-Scaling Issues, terminating not found by master node and terminating on their own

### ISSUE THREAD

**Issue by jcpasion** [aws/aws-parallelcluster#1206]
**Bug description and how to reproduce:**
After getting my stack to successfully create by pre-installing `unbound`, I now have an issue with the autoscaling group. After immediately SSHing into my master node, I run `sinfo` and get this output:
```
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      0    n/a
```
Also, I notice that the EC2 compute nodes in my auto-scaling group immediately terminate after initializing, with this message as justification:

```
Description:DescriptionTerminating EC2 instance: i-0aaafaa8d795cd925
--
Cause:CauseAt 2019-07-17T18:24:28Z instance i-0aaafaa8d795cd925 was taken out of service in response to a user request.

```

This happens even if I suspend `termination` and `replace unhealthy` actions for the auto-scaling group.

Looking into my slurmctld.log files in the master nodes, I find that the compute nodes are now not able to be found by the master node. If I run `srun -N 2 -n2 hostname`, the job gets stuck on waiting for node:
 ```
srun: Required node not available (down, drained or reserved)
srun: job 2 queued and waiting for resource
```
and the logs below reflect the changes as a result of requesting a job.

### **Environment:**

AWS ParallelCluster version 2.4
```
[aws]
aws_region_name = us-east-1

[cluster HPC]
key_name = *****
vpc_settings = vpc
pre-install = s3://****/install_unbound.sh
scaling_settings = custom
base_os: ubuntu
scheduler: slurm
initial_queue_size = 2
maintain_initial_size = true
placement_group = DYNAMIC
placement = compute
master instance type = c5.large
compute instance type = c5n.large

[vpc vpc]
vpc_id: vpc-*****
master_subnet_id = subnet-*****
vpc_security_group_id = sg-*****

[scaling custom]
scaledown_idletime = 30

[global]
cluster_template = galaxy-HPC
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```

**Referenced Issue** 
#1192 

### Logs
[master_cfn_init_log.txt](https://github.com/aws/aws-parallelcluster/files/3403257/master_cfn_init_log.txt)
[master_jobwatcher.txt](https://github.com/aws/aws-parallelcluster/files/3403258/master_jobwatcher.txt)
[master_sqswatcher_log.txt](https://github.com/aws/aws-parallelcluster/files/3403259/master_sqswatcher_log.txt)
[master_slurmctld_log.txt](https://github.com/aws/aws-parallelcluster/files/3403260/master_slurmctld_log.txt)
[compute_nodewatcher.txt](https://github.com/aws/aws-parallelcluster/files/3403411/compute_nodewatcher.txt)

**Comment by jcpasion** [comment]
I noticed errors in the /var/log/amazon/ssm directory that asked for permissions for ssm and ec2messages, which I've added. The update SQSwatcher file is attached here.
[updated_master_sqswatcher_log.txt](https://github.com/aws/aws-parallelcluster/files/3403721/updated_master_sqswatcher_log.txt)

**Comment by demartinofra** [comment]
By looking at the logs It seems like the issue is still related to the networking/dns setup. The master node is not able to resolve the compute nodes short name (see error: Failed when connecting to host ip-10-42-65-198 with error: [Errno -2] Name or service not known), hence it's unable to restart slurm on the compute nodes to complete the setup. 

On the other side compute nodes are terminating themselves after a certain timeout since they are not attached correctly to the scheduler.

**Comment by demartinofra** [comment]
I think the missing `ec2.internal` in `/etc/resolv.conf` is causing this problem. And the search domain in `/etc/resolv.conf` are managed through the domain name DHCP Options Set config

**Comment by jcpasion** [comment]
In addition to installing unbound as referenced in #1192 , I added to the bottom of the preinstall script, the script to add ec2.internal as referenced in #597 , and now my master node can recognize and send jobs to the compute nodes. I will test further if anything is not working, but it looks functional, I will keep you posted!

**Comment by joeydumont** [comment]
@jcpasion I think we're trying to build something similar. Do keep us posted here :)

**Comment by jcpasion** [comment]
My cluster was working fine all throughout yesterday. However, my network has a protocol that shuts down all EC2 instance outside of work hours. My Master and Compute Nodes were shut down, and upon wake up, they failed to connect as they did before, resulting in the repeated terminating and creation of new compute nodes. Maybe this issue is related to the timeout issues of not being connected to the scheduler again.

**Comment by demartinofra** [comment]
Generally speaking if you want to terminate the master node of your cluster you should have a graceful shutdown where you stop the cluster to terminate all compute nodes and have them removed from the master node and then you stop the master node, otherwise you risk to get into an inconsistent state. 

Regarding the issue you are facing, are you sure the `/etc/resolv.conf` didn't get restored to its initial value after the restart? I'm afraid something got reverted with the restart and the master cannot resolve the compute nodes anymore, hence those are self terminating periodically.
