### ISSUE TITLE
Cluster creation stuck on "Compute Fleet - CREATE COMPLETE"

### ISSUE THREAD

**Issue by carlitador** [aws/aws-parallelcluster#1233]
Hi,

I am trying to use a configuration that worked in the past on a new PC. I reinstalled parallel cluster and when I try to launch a cluster, it stays stuck on "Compute Fleet - CREATE_COMPLETE". Here is my configuration:

```
[aws]
aws_region_name = us-east-1
aws_access_key_id = xxx
aws_secret_access_key = xxx

[cluster default]
vpc_settings = public
key_name = xxx
compute_instance_type = c5.18xlarge
master_instance_type = t2.micro
initial_queue_size = 0
max_queue_size = 2
maintain_initial_size = false
custom_ami = ami-xxx
master_root_volume_size = 30
compute_root_volume_size = 30

[vpc public]
master_subnet_id = subnet-xxx
vpc_id = vpc-xxx

[global]
update_check = true
sanity_check = false
cluster_template = default

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```

Any idea?

Thanks

**Comment by andrew-hardin** [comment]
I recently was creating a cluster in a new zone, and I found this issue while trying to understand why the process was stuck at `Compute Fleet - CREATE COMPLETE`.

The root cause was that the master node wasn't accessible due to a incorrect `ssh_from` parameter in the cluster config file. If you're facing the same issue, it may be worth verifying that you can reach the master node (e.g. `telnet <MASTER_IP> 22`).
