### ISSUE TITLE
pcluster createami command not using config's 'custom_chef_cookbook' variable

### ISSUE THREAD

**Issue by Mauroabbatemarco** [aws/aws-parallelcluster#1272]
**Environment:**
 - AWS ParallelCluster: aws-parallelcluster-2.4.1

**Bug description and how to reproduce:**
I've trying to use the pcluster createami command with a cluster config file that has the 'custom_chef_cookbook' variable set to my custom cookbook tgz located on s3, as pointed [here](https://aws-parallelcluster.readthedocs.io/en/latest/custom_cookbook.html).

pcluster createami is looking for '**config.args.custom_ami_cookbook**' on ([pcluster.py](https://github.com/aws/aws-parallelcluster/blob/develop/cli/pcluster/pcluster.py) line 840) and [cfnconfig.py](https://github.com/aws/aws-parallelcluster/blob/develop/cli/pcluster/cfnconfig.py) is loading '**custom_chef_cookbook**' (line 516) from config. I've found a work arround using the following command:

pcluster createami --ami-id <ami-id> --os <os> -cc <custom_cookbook_path>

Thanks,
Mauro.

**Comment by sean-smith** [comment]
Hi @Mauroabbatemarco 

This is by design, we started with not reading the config file at all and recently we added support for reading the VPC section of the config file.

How can we improve the [documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.createami.html) so this is clear?
