### ISSUE TITLE
Slurm cluster scaling too slowly and not to target node number

### ISSUE THREAD

**Issue by cgorgulla** [aws/aws-parallelcluster#1288]
**Environment:**
 - AWS ParallelCluster: 2.4.1
 - OS: alinux
 - Scheduler: Slurm
 - Master instance type: t3.micro
 - Compute instance type: m5.large (spot / preemptible)

**Bug description and how to reproduce:**
- Creating a slurm cluster with 0 minimum nodes and 5000 maximum nodes (VMs)
- Starting 1000 jobs, where each job uses 1 node  (VM), i.e. uses the two cores of the compute instances
- Slurm adds new nodes extremely slowly, one by one. It adds one more node only after the previously added node is active. This takes too much time. All the nodes of all the pending jobs should be requested/added simultaneously.
- Slurm never manages to get more than 130 or so nodes up and running:

![Screenshot at 2019-08-28 12-35-43](https://user-images.githubusercontent.com/23050981/63875189-e8387b00-c990-11e9-820c-7e77658c734f.png)

**Additional context:**
Please find attached the files config, /var/log/sqswatcher, /var/log/jobwatcher, and /var/log/nodewatcher from one of the active nodes:

- [config.txt](https://github.com/aws/aws-parallelcluster/files/3551912/config.txt)
- [nodewatcher.txt](https://github.com/aws/aws-parallelcluster/files/3551913/nodewatcher.txt)
- [slurmctrld.txt](https://github.com/aws/aws-parallelcluster/files/3551914/slurmctrld.txt)
- [sqswatcher.txt](https://github.com/aws/aws-parallelcluster/files/3551915/sqswatcher.txt)

**Comment by enrico-usai** [comment]
Hi @cgorgulla,
actually the scaling logic should be able to add all the nodes simultaneously according with the number of pending jobs (since version 1.6.1).

The jobwatcher asks the scheduler for the pending jobs and configures the Auto Scaling Group to start the requested number of compute nodes.
We need the `/var/log/jobwatcher` from the master node to verify the scaling-up process.
Could you share it with us?

What kind of jobs are you submitting? Do they have some dependency?
Could you share the script you are submitting?
I'm asking because it could happen that your nodes are terminated due to inactivity while waiting for the startup of the other nodes.

You could also try to change the default value of the `scaledown_idletime` parameter:
```
[cluster default]
scaling_settings = custom
...

[scaling custom]
# Amount of time in minutes without a job after which the compute node will terminate
# Defaults to 10
scaledown_idletime = 20
```

**Comment by cgorgulla** [comment]
Hi @enrico-usai ,

Thank you very much for your answer.

Please find here the file /var/log/jobwatcher:

[jobwatcher.txt](https://github.com/aws/aws-parallelcluster/files/3557533/jobwatcher.txt)

At each of the times 22:00 and 23:10 I submitted 500 jobs. Each job uses one full node. Only around 100-130 are started/running/nodes come up.

The jobs which I submit do not have any dependencies, and they are run for many hours. Here is the header of one of the job files:

In the meantime, I do not know why, the jobs are not anymore started one by one, but simultaneously as it should be. But still, we do not reach more than roughly 130 nodes to become active. Even though we have a spot instance limit of 5000 VM. 

```
#SBATCH --job-name=b-1.1
#SBATCH --mail-type=fail
#SBATCH --time=1-00:00:00
#SBATCH --mem-per-cpu=500M
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --partition=compute
#SBATCH --output=../workflow/output-files/jobs/job-1.1_%j.out           # File to which standard out will be written
#SBATCH --error=../workflow/output-files/jobs/job-1.1_%j.out            # File to which standard err will be written
#SBATCH --signal=10@300

srun -n 1 -N 1 ../workflow/job-files/sub/one-step.sh 
```
The script one-step just does some computations using binary executables, and take a long time. 

Any ideas what the problem with upscaling is?

**Comment by enrico-usai** [comment]
Hi @cgorgulla 

behind the scenese ParallelCluster manages an [Auto Scaling Group (ASG)](https://docs.aws.amazon.com/autoscaling/ec2/userguide/AutoScalingGroup.html), to increase or decrease the number of required compute nodes by changing the "desired size" parameter of the ASG, according to the number of pending jobs.

From the logwatcher log I can say:
1. At 22:00 you didn't have pending jobs and it seems you had 7 nodes running (because the ASG desired setting parameter was set to 7).
```
2019-08-29 22:00:12,197 INFO [slurm:get_required_nodes] Computing number of required nodes for submitted jobs
2019-08-29 22:00:12,204 INFO [jobwatcher:_poll_scheduler_status] There are no pending jobs or the requirements on pending jobs cannot be satisfied. Noop.
2019-08-29 22:01:12,370 INFO [utils:get_asg_settings] min/desired/max 0/7/5000
```

2. At 22:01 you started the job submission and our daemon detected the pending jobs, increasing the desired size in the Auto Scaling Group.
```
2019-08-29 22:01:12,394 INFO [jobwatcher:_poll_scheduler_status] 11 nodes requested, 9 nodes busy or unavailable
2019-08-29 22:01:12,394 INFO [jobwatcher:_poll_scheduler_status] Setting desired to 20 nodes, requesting 13 more nodes from asg.
...
2019-08-29 22:03:13,159 INFO [jobwatcher:_poll_scheduler_status] 129 nodes requested, 9 nodes busy or unavailable
2019-08-29 22:03:13,160 INFO [jobwatcher:_poll_scheduler_status] Setting desired to 138 nodes, requesting 59 more nodes from asg.
...
2019-08-29 22:05:13,790 INFO [jobwatcher:_poll_scheduler_status] 212 nodes requested, 38 nodes busy or unavailable
2019-08-29 22:05:13,791 INFO [jobwatcher:_poll_scheduler_status] Setting desired to 250 nodes, requesting 53 more nodes from asg.
...
2019-08-29 22:09:15,218 INFO [jobwatcher:_poll_scheduler_status] 364 nodes requested, 96 nodes busy or unavailable
2019-08-29 22:09:15,219 INFO [jobwatcher:_poll_scheduler_status] Setting desired to 460 nodes, requesting 105 more nodes from asg.
...
2019-08-29 22:11:16,386 INFO [jobwatcher:_poll_scheduler_status] 410 nodes requested, 99 nodes busy or unavailable
2019-08-29 22:11:16,386 INFO [jobwatcher:_poll_scheduler_status] Setting desired to 509 nodes, requesting 7 more nodes from asg.
```
3. At 22:13 the scale up process ended up because the "desired" value of the ASG was already set to the required value.
```
2019-08-29 22:12:16,773 INFO [jobwatcher:_poll_scheduler_status] 506 nodes required, 509 nodes in asg. Noop
2019-08-29 22:13:16,966 INFO [utils:get_asg_settings] min/desired/max 0/509/5000
```
It means that our scaling logic is working correctly.
ParallelCluster is asking the Auto Scaling Group to raise up 500+ nodes, as requested.

What's happening here is that you're facing Auto Scaling Group limits.
By default the ASG launches a certain number of instances at a time.
With the default limits, your 500 nodes should be available after about 25 minutes.

You could try to ask the AWS support to increase this limit or alternatively start the cluster with `initial_queue_size = 500` and `maintain_initial_size = true` and submit your jobs once the cluster is ready.

Let us know if it helps.

**Comment by cgorgulla** [comment]
Hi @enrico-usai ,

Thank you very much for your answer, it was very helpful. 

It makes sense that ASG limit is the cause of the upscaling problems. 

However, we were really not able to get more than 130 nodes, even after hours of waiting. Maybe this is also related that we use spot instances, and sometimes they are preempted reducing the number of instances again. 

Yes, the possibility with `initial_queue_size` would be there, but we really need an autoscaling cluster. 

Increasing the limits related to the Auto Scaling Group as you suggested seems to be the way to go. Which limits related to the group do we need to increase exactly, and to which values? We would like to be able to launch up to 20 000 instances within an hour.

Thank you very much.

**Comment by nstornetta** [comment]
Hi, @cgorgulla.

Scaling to the level of instances you've specified (10,000+) will most likely require some level of engagement with an account manager or part of the support team at AWS. If you or your team already has an AWS account manager or a support plan, then as a first step we'd recommend reaching out via one of those channels to ask for their help with your use case and ASG limits.

**Comment by Palak-15** [comment]
Hello @cgorgulla 

I think you need to change spot to ondemand.
