### ISSUE TITLE
Unable to run jobs in pcluster using sge scheduler when custom ami used

### ISSUE THREAD

**Issue by chaavi01** [aws/aws-parallelcluster#1370]
**Environment:**
 - AWS ParallelCluster / CfnCluster version aws-parallelcluster-2.4.1
 - OS: centos7
 - Scheduler:  SGE
 - Master instance type: c5.2xlarge
 - Compute instance type: c5.2xlarge

**Bug description and how to reproduce:**
1. Bring up pcluster using ami-0d6c93513ba5d3734 (aws-parallelcluster-2.4.1-centos7-hvm-201907260655) as custom-ami in us-west-2
2. Log-in into pcluster ‘Master’ as ‘centos’ (since ‘centos’ is the default user for CentOS7)
3. Try submitting a simple job which echos 'hellow world' to master using ‘qsub’ command. This give the below message:
    $> qsub ./echo.sh 
    Unable to run job: warning: centos's job is not allowed to run in any queue
    Your job 1 ("echo.sh") has been submitted
    Exiting.
4. We were unable to login as 'ec2-user' since the authentication fails

Note: Without specifying custom-ami, we were able to login as 'ec2-user' into Master and able to run jobs'

**Comment by sean-smith** [comment]
@chaavi01 This is a normal warning message that occurs when there's not enough resources to run your job immediately. Your job was still submitted and will run when the resources scale up.

This is coming from SGE operating as a traditional scheduler and not knowing about instances that have yet to scale up. In SGE's view of the world, clusters have a fixed size and a job submitted when there's no resources won't run at any point. In the cloud this doesn't apply as the resources will autoscale in order to run the job. 

Can I ask why you're using the ami `ami-0d6c93513ba5d3734` as a custom ami instead of just specifying `base_os = centos7` which would have the same result?

**Comment by chaavi01** [comment]
@sean-smith : 
The reason for using custom AMI ami-0d6c93513ba5d3734 is in future we want to customize this AMI by installing additional tools which is needed for our jobs to run.

Regarding not enough resources, the pcluster brought up with 2 (minimal size) compute nodes and I am not specifying any resource constraints in the qsub command. This means the echo.sh job suppose to run on any compute machine (in this case there 2 machines already up and running).
Also 'qhost' command not showing any machine details. 

Whereas in the pcluster brought up without mentioning any custom ami, the 'qhost' command lists the 2 machines. This pcluster accepts the echo.sh job without issues and runs them on the existing compute nodes.
 
Regards,
Chandra
