### ISSUE TITLE
Placement group "compute" option not documented

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#1408]
In the AWS Parallel Cluster documentation here: https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#placement
In the cluster settings if I have "placement_group = DYNAMIC" it implies "placement = compute" however I can't find any documentation about how "compute" differs from "cluster" (which is documented here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html#placement-groups-cluster).

**Comment by nstornetta** [comment]
Hi, @RickoLacharity. The page you have linked to in the AWS ParallelCluster documentation explains the placement option as part of the cluster settings. That section explains the following: 

> Placement: Defines the cluster placement group logic, enabling either the whole cluster or only the compute instances to use the cluster placement group.

In other words, choosing "compute" specifies that only your cluster's compute nodes will be located within the placement group. This is the default configuration. Otherwise, specifying "cluster" means that the placement group will include both the cluster's master node in addition to the cluster's compute nodes. For most use cases we recommend requiring only the compute nodes to be located within the same placement group, which is why this setting is enabled by default. This terminology may differ slightly from the way the same term is used in the Placement Groups documentation where there is a slightly different mental model of what a "cluster" is.

**Comment by RickoLacharity** [comment]
Thank you, I realized now I misread the documentation.
