### ISSUE TITLE
pcluster delete hangs when pcluster's IAM role has been modified by user

### ISSUE THREAD

**Issue by aerogt3** [aws/aws-parallelcluster#1412]
**Environment:**
 - AWS ParallelCluster 2.4.1
 - OS: ubuntu 1604
 - Scheduler: slurm
 - Master instance type: c5n.2xlarge
 - Compute instance type: c5n.18xlarge

**Bug description and how to reproduce:**
If you change the IAM role created by pcluster, pcluster delete hangs. Ideally it would still work, but at minimum would be nice to have error output.

Very easy to reproduce, just launch pcluster create, make a change to the IAM role, and run pcluster delete. In my case, I had granted read access to codecommit.

**Comment by lukeseawalker** [comment]
Hi @aerogt3,
this is the expected behaviour of CloudFormation.
You can verify that going through the "AWS console - CloudFormation", select the Cloudformation stack of the cluster and then "Stack Action - Detect drift". Right after click on "Stack Action - View drift results". 
The drift detection enables you to detect whether a stack's actual configuration has drifted from its template configuration.

We'll work to improve the error message for the delete command.

**Comment by aerogt3** [comment]
Ok, understood. Thansk for the reply! In that case, as a feature suggestion, it would be nice to have a "--force" option for pcluster delete that removes the cluster despite any stack modification by the user.

**Comment by enrico-usai** [comment]
Marking as closed based on the fact that this matches an expected behaviour of CloudFormation that is designed to protect users against inadvertent errors. Users can "force" deletion from CloudFormation console, after checking the drifted resources.
