### ISSUE TITLE
Support for Centos7 AMI in China

### ISSUE THREAD

**Issue by liuyukoala** [aws/aws-parallelcluster#1491]
**Environment:**
 - AWS ParallelCluster / CfnCluster version : 2.5
 - OS: centos7
 - Scheduler: SGE
 - Master instance type:t3.xlarge
 - Compute instance type: c5.large

**Bug description and how to reproduce:**
As in cn-northwest-1 region there is no centos AMI available, pcluster create command will fail  when i set base_os=centos7. The detailed error message is as following:
Template error: Unable to get mapping for AWSRegionOS2AMI::cn-northwest-1::centos7
I try to make a custom AMI of centos7, but it didn't work either.
Is there any workaround method?
thanks!

**Additional context:**
Any other context about the problem. E.g.:
 - configuration file without any credentials or personal data.
 - pre/post-install scripts, if any
 - screenshots, if useful
 - if the cluster fails creation, please re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node
 - if a compute node was terminated due to failure, there will be a directory `/home/logs/compute`. Attach one of the `instance-id.tar.gz` from that directory
 - if you encounter scaling problems please attach `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node

**Comment by demartinofra** [comment]
Unfortunately Centos 7 official AMI is not available in China regions and that is the reason why ParallelCluster is not supporting it at the moment.

A workaround can be to import a Centos 7 AMI in cn-northwest-1 and then use the pcluster createami command as described [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html#build-a-custom-aws-parallelcluster-ami) to create a ParallelCluster AMI that can be then specified as `custom_ami` in the cluster config.

Just be aware that because of Chinese gov firewalls you might face connectivity issues while trying to build the custom AMI.

**Comment by demartinofra** [comment]
I'm going to mark this as a feature enhancement so that we can evaluate native support for Centos 7 AMI in China.

Here is also another request: https://github.com/aws/aws-parallelcluster/issues/1505

**Comment by liuyukoala** [comment]
Got it! Thanks for you kindly help!

**Comment by MMichael-S** [comment]
Hi @demartinofra 

Do you have any progress for "Support for Centos7 AMI in China"?

Have already CentOS6/7 official AMI in China region (ZHY & BJS) long time ago.

https://awsmarketplace.amazonaws.cn/marketplace/seller-profile?id=d86d613e-d4e3-4746-8dff-baec467169e7&ref=dtl_prodview-xhibnjn5u6kjmz

**Comment by demartinofra** [comment]
Adding support for CentOS in China is part of our product roadmap. Unfortunately, we do not have an ETA for this item. While there are some CentOS AMIs available in China, these are not compatible for use with ParallelCluster due to limitations on their reuse and republication. We are working with the CentOS community to make compatible AMIs available in China and will then be able to include support for them inside ParallelCluster.

_Originally posted by @nstornetta in https://github.com/aws/aws-parallelcluster/issues/2192#issuecomment-722463000_

**Comment by SivaKanishka** [comment]
Hi,

I have copied the image I built in Singapore region to China region as suggested in [this](https://github.com/aws/aws-parallelcluster/issues/2192#issuecomment-720419331). While trying to build the cluster, I got the following error.
```
Template error: Unable to get mapping for AWSRegionOS2AMI::cn-northwest-1::centos7
```
Is this specific to parallelcluster compatibility with Centos7 in China region?

**Comment by lukeseawalker** [comment]
Hi @SivaKanishka,
are you setting the parameter `custom_ami` in the PCluster configuration as described previously [here](https://github.com/aws/aws-parallelcluster/issues/1491#issuecomment-558669523)?
The value for `custom_ami` must be the new AMI id that you got as part of the copy process into the region `cn-northwest-1`.

**Comment by SivaKanishka** [comment]
Hi @lukeseawalker 

Yes, I have set the new AMI id that we created in China region. 

Also, I have tried changing the `base_os` parameter in config file to alinux2 after I got the error I have mentioned in my previous comment. Compute fleet creation is successful and master node creation is initialising, but status check for it is failing with the following error,
```
Instance reachability check failed
```

**Comment by lukeseawalker** [comment]
Sorry for the late reply @SivaKanishka,
let's do a step back:
once you have copied the AMI into one of the two China regions, are you able to start an Instance from it and SSH into the instance? Can you please do this test without involving PCluster first?

**Comment by enrico-usai** [comment]
We are marking this item as closed for the time being. 

As indicated earlier in this issue thread, publishing AMIs in a given region requires our team to have a base, official AMI that is eligible for reuse and republication in that region. 

To date, this is not the case for CentOS 7 in the China regions. If we are able to make progress with partner teams in having official AMIs eligible for ParallelCluster use, then we will reopen and update this issue.
