### ISSUE TITLE
X11 forwarding no longer enabled on master instance (2.5.0, Centos 7)

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#1508]
Is this a bug or intentional? I'm guessing this has something to do with:
`Add support for NICE DCV on Centos 7 to set up a graphical remote desktop session on the Master node.`

**Comment by RickoLacharity** [comment]
I found:
`Change default sshd config in order to disable X11 forwarding and update the list of supported ciphers
significantly increases scaling speed when ASG launch rate is raised.`

If I re-enable X11 forwarding what sort of slowdown will I see?

**Comment by demartinofra** [comment]
Hi @RickoLacharity 

There is a small inconsistency in the release notes since the increase in scaling speed was related to the previous item of the list. Sorry for the confusion.

Now regarding your question: x11forwarding has been disabled by default to harden cluster security in cases where you don't require it. You can go ahead and re-enable it in your cluster without impacting any functionality.

Could you briefly explain your use case to have x11forwarding enabled so that we can take this into account when evaluating default ssh config for future versions of ParallelCluster?

Francesco

**Comment by RickoLacharity** [comment]
X11 allows for remote GUI access for a lot of software (Configuration or CAD GUI's). However, X11 can also be used with a scheduler to request an environment with GUI capabilities. 

eg. `ssh -X {master} "srun -n1 --pty --x11 xclock"`

ref. https://slurm.schedmd.com/faq.html#x11

**Comment by enrico-usai** [comment]
@RickoLacharity thank you for your feedback.

As you reported, starting from ParallelCluster 2.5.0 you can interact with the master instance by using your browser, through a [NICE DCV connection](https://docs.aws.amazon.com/parallelcluster/latest/ug/dcv.html).

In any case, feel free to re-enable X11 Forwarding, by using a [custom post installation script](https://docs.aws.amazon.com/en_us/parallelcluster/latest/ug/pre_post_install.html) for example.

**Comment by RickoLacharity** [comment]
I was able to verify that x11-forwarding still works for interactive job scheduler sessions. All that is necessary is re-enabling x11-forwarding on the master instance by following [this guide](https://prasadlinuxblog.wordpress.com/2018/05/29/how-configure-x11-forwarding-in-centos-rhel-6-7/).

Slurm example:
salloc -n1 {GUI-Application}

**Comment by enrico-usai** [comment]
Thank you @RickoLacharity 
I'm going to close this issue, please feel free to open a new if needed.
