### ISSUE TITLE
Python tabulate version error with parallelcluster-2.5.0

### ISSUE THREAD

**Issue by rmarable** [aws/aws-parallelcluster#1509]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 2.5.0
 - OS: OSX-10.14.6 (Mojave)
 - Scheduler: n/a
 - Master instance type: n/a
 - Compute instance type: n/a

**Bug description and how to reproduce:**
The following error was returned after a successful installation of version 2.5.0 of ParallelCluster on a Mac running OSX 10.14.6 (Mojave) using Python-3.7.4 provided by Homebrew:
Successfully built aws-parallelcluster tabulate
ERROR: aws-parallelcluster 2.5.0 has requirement tabulate<=0.8.3,>=0.8.2, but you'll have tabulate 0.8.6 which is incompatible.

$ pcluster version
2.5.0

**Comment by demartinofra** [comment]
Hi @rmarable,

Thanks for reporting this.
I believe this is caused by some incompatible dependencies that are already installed in your system. As of now ParallelCluster 2.5.0 requires tabulate to be <=0.8.3,>=0.8.2.

Can you try to install the CLI in a virtualenv as described in the official docs: https://docs.aws.amazon.com/parallelcluster/latest/ug/install-virtualenv.html

**Comment by rmarable** [comment]
Thanks @demartinofra - I'll close this issue.
