### ISSUE TITLE
v.2.5.0 - Can I set a custom ENV variable somewhere if I'm building a custom AMI anyway

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#1513]
**Environment:**
 - AWS ParallelCluster 2.5.0
 - OS: CentOS 7
 - Scheduler: SGE
 
Ack this may be more of a feature/guidance request than a bug but I'm wrestling with v2.5.0 in my security conscious client who has private subnets and VPC with internet/API access blocked by default and SSL intercept/decrypt in play which requires trusting custom CA certificates before the client code can talk HTTPS to the outside world ..

My catch-22 is that I think I need to set some custom ENV variables like "AWS_CA_BUNDLE" (_for our custom SSL CA certs_) and "noproxy=github.com" _(because we can use a proxy for API traffic but we can't use the proxy for the github.com destinations_) settings at the earliest possible boot moment -- my v2.5.0 grids are stalling right now on basic communication with the c'oudformation API so I think I need the customizations in place even before a pre_install bootstrap script would be acceptable.  

TL/DR: Is there a place in the AMI image where I can set some ENV variables that would be exposed/visible to the parallelcluster cookbooks and install agents doing the earliest possible parallelcluster setup and cloudformation status reporting -- even before pre_install bootstrap hooks get called? 

Thanks!

Here is an example from the master node. Looks like I'm hitting SSL trust issues right away. I *tried* to append our custom ca certs to the python boto cacert.pem files but it looks like I missed the one that is actually used.   If I could set AWS_CA_BUNDLE= before the cloudformation API calls I think this would all work ... unless the earliest script is using /usr/lib/python2.7/site-packages/cfnbootstrap/packages/requests/cacert.pem? If so then I can customize that in my custom AMI! 

> 2019-12-03 17:52:11,191 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
> 2019-12-03 17:52:11,191 [DEBUG] Describing resource MasterServerLaunchTemplate in stack parallelcluster-hpctest-v1
> 2019-12-03 17:52:11,370 [ERROR] SSLError
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 162, in _retry
>     return f(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 234, in _timeout
>     raise exc[0]
> SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
> 2019-12-03 17:52:11,416 [DEBUG] Sleeping for 0.097685 seconds before retrying
> 2019-12-03 17:52:11,514 [DEBUG] Describing resource MasterServerLaunchTemplate in stack parallelcluster-hpctest-v1
> 2019-12-03 17:52:11,631 [ERROR] SSLError
>

**Comment by lukeseawalker** [comment]
Hi @chrisdag,
if I have understood correctly you are searching a way to export an env variable before calling the cfn-init command, so using a [custom CloudFormation template](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#template-url) could be an idea worth to try.

Basically you need to modify the user data, both for the Master and the Compute node, in order to export your environment variable. The two points to do the changes are [here](https://github.com/aws/aws-parallelcluster/blob/develop/cloudformation/aws-parallelcluster.cfn.json#L2223) and [here](https://github.com/aws/aws-parallelcluster/blob/develop/cloudformation/aws-parallelcluster.cfn.json#L3185). Before calling the cfn-init command you should export your variable.
Then upload the custom template to a bucket and use it with the template_url configuration.

L
