### ISSUE TITLE
Q: Best practices for more interactive/responsive scaling?

### ISSUE THREAD

**Issue by briandobbins** [aws/aws-parallelcluster#1526]
Hi all,

  I glanced around at the wiki but didn't see anything related to this -- I'm looking at ways of decreasing spin-up time for nodes.  Are there any write-ups about this?  Eg, things like how does image size affect spin-up, what are the trade-offs in making jobwatcher/sqswatcher run more frequently, can I 'bake-in' additional things to reduce what Chef installs?

  This would be pretty useful for training sessions using parallel cluster.  At the moment, our setup works, but it takes between 5-9 minutes for a multi-node job to launch [c5.18xlarge, Slurm scheduler, but Torque seems similar].  That's totally fine for production, but I'd love to get it lower for more 'interactive' use.

  Thanks,
  - Brian

**Comment by lukeseawalker** [comment]
Hi @briandobbins,
before moving forward I would ask you if you are using an official ParallelCluster AMI (e.g. 
 one of this list for version 2.5.0 https://github.com/aws/aws-parallelcluster/blob/v2.5.0/amis.txt) or a custom one?

Thanks
L

**Comment by briandobbins** [comment]
Hi Luca,

  I customized an AMI from that list -- primarily adding some files, but not changing the OS in a meaningful way.  I also do have a post install script that makes a few more changes, but it's also fairly light.

  If you're seeing more responsiveness from the base AMIs, I'll give that a shot too and see if I can find any differences on my own.  I just assumed the 5-9 minute spin up was fairly standard.  I am also using 'spot' instances if that matters.

  Thanks, and let me know if you need additional information.

  - Brian

**Comment by lukeseawalker** [comment]
Moving everything to the AMI instead of using a post install script could help a bit.
Could you please post the `cfn-init*` and `cloud-init*` files of one compute node so we can double check that there are no evident bottleneck?

**Comment by demartinofra** [comment]
A few additional comments:
- Spot instances might introduce some additional delays if the spot request cannot be satisfied right away
- you could try to compare provisioning time of your custom spot cluster with the one obtained with a vanilla pcluster AMI, no post-install and ondemand capacity. This way you can better understand what the lower bound is for node provisioning time.
- If a job requires more than 10 nodes you could request an increase of the default ASG launch rate (normally it is set to launch 10 instances every 30 seconds). This enables you to launch more nodes concurrently.

As @lukeseawalker suggested feel free to share the logs present in `/var/log/` from one of your compute nodes and from your master node so that we can take a look and see if there are specific bottlenecks in the bootstrap logic.
