### ISSUE TITLE
Q: Possible Slurm / Spot issue?

### ISSUE THREAD

**Issue by briandobbins** [aws/aws-parallelcluster#1587]
Hi all,

  I wish I had a lot more information on this, but it's the second time we're seeing it, and I'm curious to hear thoughts of the parallelcluster team.  We're running 2.5.0, using Slurm as the scheduler, and using 'spot' instances.  We've had 30 jobs die at once, all at the same time, with messages like the following:

<job> slurmstepd: error: get_exit_code task 0 died by signal: 15
<job> slurmstepd: error: If munged is up, restart with --num-threads=10
<job> slurmstepd: error: Munge encode failed: Failed to access "/var/run/munge/munge.socket.2": No such file or directory
<job> slurmstepd: error: authentication: Invalid authentication credential
<job> slurmstepd: error: *** JOB 162 ON ip-10-0-16-42 CANCELLED AT 2019-12-29T05:31:10 DUE TO NODE FAILURE, SEE SLURMCTLD LOG FOR DETAILS ***
<job> slurmstepd: error: get_exit_code task 0 died by signal: 15

We were told by support that this was due to a spike in spot demand, but the price didn't go above the baseline (and we had a 20% buffer or so above that).  I also did see that the 2.5.1 release has a 'fix' relating to Munge (seen above) for CentOS 7 builds, which this is, but I didn't see any details from a quick look - here's the line in the release notes:

- Fix installation of Munge on Amazon Linux, Centos 6, Centos 7 and Ubuntu 16.

Have any of you seen similar issues or have ideas?  Both failures we've seen happened in December, but weeks apart, using c5.18xlarge nodes in the us-west-1 region, with no corresponding spot price increase to indicate an uptick in demand above the bid price.

**Comment by enrico-usai** [comment]
Hi @briandobbins 

We had an issue during the installation phase of the munge package in the aforementioned OSes.
The details of the fix are in the cookbook package: https://github.com/aws/aws-parallelcluster-cookbook/pull/453

We never seen this error but the message seems pretty self-explanatory (no such file or directory --> munge not installed). 
We cannot confirm your issue is related to the munge issue but in any case we recommend to use the latest ParallelCluster version (2.5.1) with the fix.

If the issue happens again it is useful to have the configuration file and the log files from the master and from the failing compute nodes, available in the `/home/logs/compute` folder of the master.

Let us know if it helps.

**Comment by rexcsn** [comment]
Hi @briandobbins

Adding to Enrico's comment, here are some specific things that would help us debug the issue if it happened again:
* Provide output to the following commands:
  - squeue
  - scontrol show job
  - scontrol show node
  - sdiag 
* Provide slurm configuration files, which are located under `/opt/slurm/etc/`. The easiest way to do this is to just zip the folder and send it over
* Provide slurm daemon log files:
  -`/var/log/slurmctld.log` on the Master server
  -`/var/log/slurmd.log` on the failing Compute servers, if possible. This is a little harder because the failing compute server might have been terminated, but you should find it in `/home/logs/compute` folder of the master after the failure.
