### ISSUE TITLE
Update /etc/yum.conf earlier in the install process.

### ISSUE THREAD

**Issue by CornTimer** [aws/aws-parallelcluster#1647]
We use clusters in a private VPC that has Internet access via a proxy, the configuration for which is set in the configuration file.  This setup is confirmed to work correctly, however it does not get set early enough when compute nodes are instantiated.

The proxy information will eventually be reflected in /etc/yum.conf, however the spin-up process will attempt to install other software prior to making this change (ex:  MPI libraries from Intel).

We tried fixing this via the pre-install script, but it appears that running that also occurs *after* this initial software install.

Results:  
 - Necessary software never gets installed
 - Compute node build process often takes so long they are often marked as failed and the process starts again.

**Environment:**
 - AWS ParallelCluster / CfnCluster version aws-parallelcluster-2.4.1, 2.5.1
 - OS: alinux, centos7
 - Scheduler: SGE

**Comment by rexcsn** [comment]
Hi,

We pre-bake our AMI with several packages; unfortunately,`intel_mpi` is one of them, so you are correct, before pre-install script `intel_mpi` is already installed. In this case we will need to create a custom AMI.

The workaround is to launch an instance with the base AMI for OS of your choice. Run the pre-install script or manually setup your configuration on the instance. Create an AMI from that instance, and use it to create a `pcluster` AMI by run `pcluster createami -ai [your AMI ID] -os [your base OS] [other options as needed]`. Finally, use the resulting custom AMI to create the cluster.

Hope that helps!

**Comment by CornTimer** [comment]
We've gotten as far as tracking the problem to cloud-init.  It attempts to do a software update/install and query certain metadata values for each instance (http://169.254.169.254/latest/meta-data/...)

All of these actions have to wait on a timeout followed by multiple retries, so in the end it takes 30 minutes or more to instantiate any nodes.

If we go all the way back to parallelcluster version 2.3.1 then it works properly.  Every version later than that has this problem.

And to reiterate from the original post, these clusters are being created in a private VPC.

**Comment by enrico-usai** [comment]
Hi @CornTimer 
thanks for the details.

We're actually configuring the proxy in the yum configuration as [the first action](https://github.com/aws/aws-parallelcluster/blob/v2.5.1/cloudformation/aws-parallelcluster.cfn.json#L2907-L2917) of the user data, it means it's executed as first step when the compute node start, before any installation of external packages.

Intel MPI packages are not downloaded from yum but from the Intel website, so you need to enable that website (and all the other required ones) in your proxy configuration.

At present, the network access is required by compute nodes to download different packages.
The IP address 169.254.169.254 instead is a link-local address, it is valid only from the instance and should always be available.

You said the configuration was working with ParallelCluster 2.3.1. I haven't been able to find any relevant change in the proxy management after this version. Did you use the same VPC and the same subnet for the test with the 2.3.1 version? 

Could you please double check the routing table of your private subnet, to be sure the compute nodes are able to contact the web through the proxy?
Do you have any error in the master instance? If no, is it in a different subnet?
You should be able to see in the log of the proxy what are the websites the compute nodes are trying to contact and enable all of them in the proxy configuration.

Could you share your configuration file without any personal data and the log files from a failing compute instance?
You can re-execute create action using `--norollback` option.  
You should find `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files in both the Master and compute nodes.
If compute node was terminated due to failure, there will be a directory `/home/logs/compute`. Attach one of the `instance-id.tar.gz` from that directory.

Let us know if it helps.

**Comment by CornTimer** [comment]
Thanks for the reply, and unfortunately, I'm not currently in a position to be able to attach any of the logs or the pcluster template.

When you say you configure the proxy in the userdata, what does that config entail?  It's certainly not set in /etc/yum.conf until much later in the instance instantiation, but that's also true for the instances that work properly.

For right now, I can tell you that if I use the same template under pcluster 2.3.1 and 2.4.1, the 2.3.1 install will work properly and the 2.4.1 (and 2.5.1) will not.

So everything other than the pcluster version is the same -- subnets, proxy server, routing tables, AMI image, etc.

And yes, we see this same behavior on the master node as well.

Also, I think there was some misinterpretation of /var/log/clout-init.log regarding meta-data requests.  Ignore that as a symptom.  If I can recreate that and validate it I'll let you know.

**Comment by enrico-usai** [comment]
Hi @CornTimer 
thanks for the answer.

We are setting the proxy it in the yum.conf as [first step](https://github.com/aws/aws-parallelcluster/blob/v2.5.1/cloudformation/aws-parallelcluster.cfn.json#L2907-L2917) of the instance startup and it should be available to all the subsequent steps. 
It's possible to verify the right execution of the proxy configuration steps by checking the content of the cloud-init.log and cloud-init-output.log files.

> same [...] AMI image [...] 

Are you using a custom ami? [Which process](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html) did you follow to create your custom ami?
If you're [modifying a Pcluster AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html#modify-an-aws-parallelcluster-ami) please be sure the AMI matches the version of ParallelCluster. 

> same [...] proxy server [...] 

Without any configuration file or log files it's hard for us to debug or try to replicate the issue. 
From the data we have right now, since we added support for Intel MPI in the [2.4.1 version](https://github.com/aws/aws-parallelcluster/releases/tag/v2.4.1), I'd suggest to double check the proxy logs and eventually allow access to the Intel website and to all the other repositories required by the new features added to ParallelCluster since 2.4.1.

Please let us know if you're able to replicate the issue and provide us some snippets of the log files.

**Comment by CornTimer** [comment]
Oh yes, this can be replicated 100% of the time.

Now have access to the config and log files, so here come the deluge.  First up is the redacted 
config, then the cloud-init*.log files from the master node when running this using pcluster 2.4.1 (2.5.1 has the same behavior).  For comparison I will then also attach the logs using pcluster 2.3.1 from a build using the same template.

[config-redacted.txt](https://github.com/aws/aws-parallelcluster/files/4247545/config-redacted.txt)

################
### Logs: 2.4.1
################

[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/4247546/cloud-init.log)


[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/4247547/cloud-init-output.log)

################
### Logs: 2.3.1
################

[cloud-init-231.log](https://github.com/aws/aws-parallelcluster/files/4247552/cloud-init-231.log)


[cloud-init-output-231.log](https://github.com/aws/aws-parallelcluster/files/4247553/cloud-init-output-231.log)

**Comment by lukeseawalker** [comment]
Hi @CornTimer ,
I'm marking this as a bug since as you noticed, the proxy configuration is not taking place early in the process.

I can provide you a workaround that works with the configuration that you are using (us-east-1 and alinux)

Download locally the cloudformation template for the version that you would like to use.
E.g. for 2.5.1

```
wget https://s3.amazonaws.com/us-east-1-aws-parallelcluster/templates/aws-parallelcluster-2.5.1.cfn.json
```

Locate inside the file the `"UserData"` sections. NB they are two, one for the master and one for the compute and both of them must be modified.

Locate the two parts

```
"Content-Type: multipart/mixed; boundary=\"==BOUNDARY==\"\n",
"MIME-Version: 1.0\n\n",
"--==BOUNDARY==\n",
"Content-Type: text/cloud-config; charset=\"us-ascii\"\n",
"MIME-Version: 1.0\n\n",
"#cloud-config:\n",
"runcmd:\n",
" - [ sh, -c, 'which yum && echo \"proxy=",
{
  "Fn::If": [
    "UseProxy",
    {
      "Ref": "ProxyServer"
    },
    "_none_"
  ]
},
"\" >> /etc/yum.conf || echo \"Not yum system\"' ]\n",
" - [ sh, -c, 'which apt-get && echo \"Acquire::http::Proxy \\\"",
{
  "Fn::If": [
    "UseProxy",
    {
      "Ref": "ProxyServer"
    },
    "false"
  ]
},
"\\\";\" >> /etc/apt/apt.conf || echo \"Not apt system\"' ]\n",
"--==BOUNDARY==\n",
```

and substitute them with 

```
"Content-Type: multipart/mixed; boundary=\"==BOUNDARY==\"\n",
"MIME-Version: 1.0\n\n",
"--==BOUNDARY==\n",
"Content-Type: text/cloud-boothook; charset=\"us-ascii\"\n",
"MIME-Version: 1.0\n\n",
"#!/bin/bash -x\n\n",
"echo \"Configuring proxy\" >/tmp/debug.conf.proxy.log\n",                  
"which yum && echo \"proxy=",
{
  "Fn::If": [
    "UseProxy",
    {
      "Ref": "ProxyServer"
    },
    "_none_"
  ]
},
"\" >> /etc/yum.conf || echo \"Not yum system\"\n",
"--==BOUNDARY==\n",
```

Then save and upload this modified template into an S3 bucket, take note of the URL.

Create a cluster with the usual command `pcluster create` adding the `-u` option flag to specify the custom template URL to be used  e.g.
```
pcluster create ... -u https://my_bucket/my_custom_template
```

NB `pcluster` version must match the version of the template you modified before.

Thanks,
Luca

**Comment by lukeseawalker** [comment]
Hi @CornTimer,
an easier alternative to the workaround I provided in my previous comment is to use ParallelCluster version 2.6.0 that was just released few days ago.
