### ISSUE TITLE
AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by Khanscer** [aws/aws-parallelcluster#1648]
**Environment:**
 - aws-parallelcluster-2.5.1
 - Config 
aws_region_name = us-east-2
aws_access_key_id = xxxxxx 
aws_secret_access_key = xxxxxx

[cluster default]
vpc_settings = public
key_name = xxxx
ebs_settings = custom
post_install = xxxxxxxx
base_os = ubuntu1604
maintain_initial_size = true
compute_instance_type = c5.2xlarge
initial_queue_size = 1
max_queue_size = 5

[vpc public]
master_subnet_id = subnet-0187256334afe34ef
vpc_id = vpc-bebdb6d6
use_public_ips = false

[global]
update_check = true
sanity_check = true
cluster_template = default

[ebs custom]
ebs_snapshot_id = snap-xxxxx
volume_type = gp2

Hello, I'm running pcluster create test in the Command prompt on windows with the previous config file. Apparently it stays in the following step indefinitely.

C:\Users\user>pcluster create test
Beginning cluster creation for cluster: test
Creating stack named: parallelcluster-test
Status: MasterServerWaitCondition - CREATE_COMPLETE

**Comment by rexcsn** [comment]
Hi,

Could you verify if the cluster can be created without the `post_install` script?

**Comment by Khanscer** [comment]
Hi, I tried the same command on ubuntu and resulted, after 60-70min, in the following error:
$ pcluster create test
Beginning cluster creation for cluster: test
Creating stack named: parallelcluster-test
Status: parallelcluster-test - ROLLBACK_IN_PROGRESS                             
Cluster creation failed.  Failed events:
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 0 SUCCESS signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

The same error occurs without the post_install script

**Comment by rexcsn** [comment]
Another thing in the config that can potentially cause a problem is `use_public_ips=false`. I would recommend removing that if possible, otherwise please double check your network configuration: https://docs.aws.amazon.com/parallelcluster/latest/ug/networking.html#aws-parallelcluster-in-a-single-private-subnet-connected-using-direct-connect

**Comment by Khanscer** [comment]
Hi, thanks for the help. Without the use_public_ips=false, several issues appear.

C:\Users\josen>pcluster create test
Beginning cluster creation for cluster: test
Creating stack named: parallelcluster-test
Status: parallelcluster-test - ROLLBACK_IN_PROGRESS
Cluster creation failed.  Failed events:
  - AWS::EC2::SecurityGroup MasterSecurityGroup Resource creation cancelled
  - AWS::CloudFormation::Stack EBSCfnStack Resource creation cancelled
  - AWS::DynamoDB::Table DynamoDBTable Resource creation cancelled
  - AWS::IAM::Role RootRole Resource creation cancelled
  - AWS::SQS::Queue SQS Resource creation cancelled
  - AWS::EC2::EIP MasterEIP The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceeded; Request ID: 5920b10c-9019-4ee7-b006-d789b95e146e)

I'll search for those errors. Thanks again

**Comment by enrico-usai** [comment]
Hi @Khanscer 

The `AddressLimitExceeded` means you're reaching the limit of the number of Elastic IP you can instantiate on your account (by default the limit is 5). 
You can check if you have detached Elastic IPs and delete them or [request for a limit increase](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html).

### More insights on use_elastic_ips=false

From your configuration file we can see you're using a single _public_ subnet for your cluster (for "public" I mean a subnet on which there is an **Internet Gateway**).

As suggested by @rexcsn you cannot set `use_public_ips` to `false` when using a public subnet because one of the Internet Gateway [requirements](https://docs.amazonaws.cn/en_us/vpc/latest/userguide/VPC_Internet_Gateway.html#vpc-igw-internet-access) is to have a globally unique IP address for all the instances in the subnet.

> The internet gateway logically provides the one-to-one NAT on behalf of your instance, so that when traffic leaves your VPC subnet and goes to the internet, the reply address field is set to the public IPv4 address or Elastic IP address of your instance, and not its private IP address. 

By setting `use_public_ips` to `false` the Compute Instances will not have a public Ip and it means they cannot be contacted by the Internet Gateway, it is the reason of your first failure on which the ComputeFleet creation fails: `AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 0 SUCCESS signal(s) out of 1.`

The other effect of setting `use_public_ips` to `false` is that the Master won't use an Elastic IP but will use a dynamic public IP. It is the reason why in the first case you didn't encounter the `AddressLimitExceeded` error.

Let us know if it helps.

**Comment by Khanscer** [comment]
Hi @enrico-usai,
Sorry for the late response. I have just tried what you suggested. After releasing the IPs generated the config file worked. Thank you very much. Also thanks to @rexcsn for the help.
