### ISSUE TITLE
sqswatcher (SignatureDoesNotMatch) error in log

### ISSUE THREAD

**Issue by etiennebourgeois** [aws/aws-parallelcluster#1651]
**Environment:**
 - AWS ParallelCluster 2.5.0

**Bug description and how to reproduce:**
I am not sure how to re-create this, everything was running fine, until the sqswatcher seems to have stopped running for about 3 hours (nothing in the logs) and then a SignatureDoesNotMatch error appeared. Once that happened, then new Compute nodes were no longer getting created properly and our jobs weren't running anymore.

We weren't able to recover form this error, so we re-created a brand new cluster and now that is up and running.

We also saw a lot of errors logged in the jobwatcher log as well. I am not sure what caused this and why it couldn't recover. I attached both log files.

Thanks!

[sqswatcher.failure.txt](https://github.com/aws/aws-parallelcluster/files/4206554/sqswatcher.failure.txt)
[jobwatcher.failure.txt](https://github.com/aws/aws-parallelcluster/files/4206555/jobwatcher.failure.txt)

**Comment by rexcsn** [comment]
Hi,

Here is an issue that seems to be similar to what we are seeing here: https://stackoverflow.com/questions/44017410/signature-expired-is-now-earlier-than-error-invalidsignatureexception.
`sqswatcher` makes calls to SQS, and I think the error is because the machine time is out of sync. Could you try to synchronize the time of your machine as indicated by the thread above?

You can also follow this guide to set up time sync on your instance to eliminate this potential problem: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

I assume the log files you provided are complete, and we are seeing a gap between `2020-02-09 03:xx:xx` and `2020-02-09 08:xx:xx` where there is nothing in both the `sqswatcher` and `jobwatcher` logs.
Are you aware of any process on your machine that could be resetting the time?

**Comment by etiennebourgeois** [comment]
Thanks for you answer, we ended up creating a new cluster, we will take @rexcsn's advice and setup time sync on our instances.
