### ISSUE TITLE
Cannot create cluster following error

### ISSUE THREAD

**Issue by johnkit** [aws/aws-parallelcluster#1669]
**Environment:**
 - aws-parallelcluster-2.5.1
 

**Description**
I had an error in my config file, and as a result `pcluster create` aborted with "Cluster creation failed". After fixing the config file, however, I am not able to use the same cluster name.

* `pcluster create` returns a message that the stack already exists.
* `pcluster update` returns a message that the stack doesn't have a ComputeFleet.
* `pcluster instances` also returns a message that the stack doesn't have a ComputeFleet.
* `pcluster start` also returns a message that the stack doesn't have a ComputeFleet.

No master server was created/launched, and the cluster seems to be in some zombie state. Is there any way to recover from this, or do I have to delete the cluster and try again (possibly with a different cluster name?)

**Comment by rexcsn** [comment]
Hi,

If you do `pcluster list` you will most likely see that the failing stack is there. If you want to use the same stack name you will have to do `pcluster delete [your stack name]` and wait for the CloudFormation stack to be completely deleted, before creating a new one with the same name. You can always check the status of the current stacks with `pcluster list` or in your CloudFormation console.

In the case of creation failures, the expected behavior is that CloudFormation stack will rollback all the resources(if not specifying `--no-rollback`), but the stack itself will still be there, and you need to delete the stack manually with `pcluster delete` or in the CloudFormation console to completely clean up.

Hope that helps!

**Comment by johnkit** [comment]
Yep, that makes sense. Thanks so much for the quick reply.
