### ISSUE TITLE
slurm job will not requeue when spot is pre-empted

### ISSUE THREAD

**Issue by mikerossgithub** [aws/aws-parallelcluster#1671]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.5.1]
2.4.1
 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.

**Bug description and how to reproduce:**
Using slurm and `sbatch --requeue` jobs are not requeued when spot's are preempted due to lack of capacity

The requeue system seems to work if the job runs out of memory and crashes. But if the spot instance is pre-empted by AWS due to lack of spot capacity, then the job is never requeued.

I call the job with the following command:
`sbatch job_script.sh`

Inside job_script.sh I have:
```
#SBATCH --requeue
do_something.sh || scontrol requeue $SLURM_JOB_ID
```

**Comment by lukeseawalker** [comment]
What is the status of the slurm queue after the spot reclaim? Can you please post the output?

**Comment by demartinofra** [comment]
My guess is that the logic to requeue the job is coded in the job script itself (`|| scontrol requeue $SLURM_JOB_ID`), which is running on the compute node. If the node is reclaimed by spot the instance is terminated, hence the job killed, and because of this it never gets to run the requeue command.

I'd recommend to periodically check for [spot instance termination notices](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#spot-instance-termination-notices) and add the re-queue logic there. You could start for instance a background process as first step of your submission script which checks for these events and trigger a requeue if necessary.

More in general, if it helps, here is some additional documentation on how ParallelCluster behaves with spot instances: https://docs.aws.amazon.com/parallelcluster/latest/ug/spot.html

**Comment by mikerossgithub** [comment]
We went with the background process solution pretty much as you described. I was surprised SLURM doesn't support this, but the background process gives us finer control than SGE anyway. Thank you for your help!
