### ISSUE TITLE
Cluster size 

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#1674]
- aws-parallelcluster-2.5.1
- Ubuntu18.04
- SGE
Hello Aws-Parallelcluster Team,
I'm running into problems trying to deploy a cluster with 100+ spot instances. The problem is somewhat related to the one described at https://github.com/aws/aws-parallelcluster/issues/1115 although several details are different. When I tried on Saturday, it wasn't going past spinning up the master instance. I requested a limit increase for the Stack sets per administrator and Stack count. The new behavior is kind of funny because it spins up the master instance plus a single compute instance (have happened yesterday and today). I don't even know if the problem could be any spot limit (similar to the said thread) because I don't see any spot service limit in the new console (and clusters with 75 instances are probably well beyond any service limit set months ago). I have the logs in case they are needed.
Thanks.

**Comment by demartinofra** [comment]
Hi @afernandezody 

This could be due to Spot availability for the specific compute instance type you are using in the selected AZ.

Could you share the following please:
* your cluster config (mostly interested in compute instance type and spot price)
* AvailabilityZone and AvailabilityZoneId for your compute subnet. you could retrieve this by running an `aws ec2 describe-subnets` command

Also while cluster is creating (or if you still have a failed one cause you used the -nr flag) you could check the ASG history from the console or from the CLI in order to understand why the compute nodes could not be launched. If you want me to provide the programmatic way to retrieve this just let me know. Here is a useful resource: https://docs.aws.amazon.com/autoscaling/ec2/userguide/CHAP_Troubleshooting.html

**Comment by afernandezody** [comment]
```
[aws]
aws_region_name = us-east-1
aws_access_key_id = 
aws_secret_access_key = 

[cluster c1cluster]
vpc_settings = odyvpc
placement_group = DYNAMIC
placement = compute
key_name = 
master_instance_type = t3.micro
compute_instance_type = c5n.18xlarge
cluster_type = spot
enable_efa = compute
initial_queue_size = 125
max_queue_size = 125
maintain_initial_size = true
scheduler = sge
base_os = ubuntu1804

[vpc odyvpc]
master_subnet_id = 
vpc_id = 

[global]
update_check = true
sanity_check = true
cluster_template = c1cluster

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

```
I understand that some declarations are no longer needed. The subnet is us-1f. I'll try your suggestions a bit later in the day.

**Comment by afernandezody** [comment]
Hi @demartinofra,
It seems that you were right and it's hitting a spot limit as shown in the console screenshot. I'm unsure if this limit is because of my account, the AZ/subnet combination or something else. Do you have any suggestion on how to increase this limit? Thanks.
 
![error_Autoscale](https://user-images.githubusercontent.com/44442767/75842131-8b81a700-5d9d-11ea-9a9f-62c2d468a20f.png)

**Comment by demartinofra** [comment]
I'm not sure whether the limit is related to your account or to unavailability of spot capacity for the instance type you selected. You could try to open a customer case to have this limit checked as explained here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html

Also to apply some additional checks on my side I'd need the AvailabilityZoneId mapped to the az you are using but for some reason (maybe older awscli version?) I'm not seeing this in the output you posted. You could try running a `aws ec2 describe-availability-zones` to get that value otherwise. 
In any case my recommendation is to open a customer case and link this issue to it.

**Comment by afernandezody** [comment]
I opened the ticket with the support team (it's the old console but hopefully it's still OK sending them from there).
The return from `aws ec2 describe-availability-zones` doesn't show much: 
```
{
    "AvailabilityZones": [
        {
            "State": "available",
            "ZoneName": "us-east-1a",
            "Messages": [],
            "RegionName": "us-east-1"
        },
        {
            "State": "available",
            "ZoneName": "us-east-1b",
            "Messages": [],
            "RegionName": "us-east-1"
        },
        {
            "State": "available",
            "ZoneName": "us-east-1c",
            "Messages": [],
            "RegionName": "us-east-1"
        },
        {
            "State": "available",
            "ZoneName": "us-east-1d",
            "Messages": [],
            "RegionName": "us-east-1"
        },
        {
            "State": "available",
            "ZoneName": "us-east-1e",
            "Messages": [],
            "RegionName": "us-east-1"
        },
        {
            "State": "available",
            "ZoneName": "us-east-1f",
            "Messages": [],
            "RegionName": "us-east-1"
        }
    ]
}
```
