### ISSUE TITLE
Pcluster update failed Parameters: [CWLogOptions] do not exist in the template

### ISSUE THREAD

**Issue by medcelerate** [aws/aws-parallelcluster#1682]
**Environment:**
 - AWS ParallelCluster / 2.6.0
```
[aws]
aws_region_name = us-east-1

[global]
cluster_template = slurmonawsv2
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster slurmonawsv2]
key_name = omit
scheduler = slurm
master_instance_type = m4.4xlarge
compute_instance_type = m5.4xlarge
initial_queue_size = 1
max_queue_size = 800
spot_price = 1.50
maintain_initial_size = true
vpc_settings = default
custom_ami = omit
cluster_type = spot
compute_root_volume_size = 400
tags = {"RunSchedule": "24x7", "PC": "PCSB"}
s3_read_resource = 
s3_read_write_resource =
extra_json = { "cluster" : { "ganglia_enabled" : "yes" } }
fsx_settings = sharedfs
scaling_settings = sc
cw_log_settings = cwllog

[cw_log cwllog]
enable = true
retention_days = 14

[fsx sharedfs]
shared_dir = /cromwell_root
storage_capacity = 10800
imported_file_chunk_size = 1024
export_path = s3://cromwellfsxstore/fsx
import_path = s3://cromwellfsxstore
weekly_maintenance_start_time = 1:00:00


[scaling sc]
scaledown_idletime = 20

[vpc default]
vpc_id = omit
master_subnet_id = omit
compute_subnet_id = omit
use_public_ips = false
```

**Bug description and how to reproduce:**
Attempt to ```run pcluster update -c {config_file} slurmonawsv2```
Returns: Parameters: [CWLogOptions] do not exist in the template

**Additional context:**
Cluster was created on V2.5.0 and wanted to updated in order to add cloud logging. However, if I remove the log section the same error persists.

**Comment by demartinofra** [comment]
As of now unfortunately you cannot update a cluster created with a previous version (v2.5.0) to a newer version (v2.6.0), which means in order to use the new features you need to create a new cluster. 
Note that also the custom_ami needs to be recreated to work with the newer version.
In case you want to update the cluster created with v2.5.0 please make use of the CLI for that specific version.

Just let us know if you have additional question or need help to move to the newer version!
