### ISSUE TITLE
Use a common EFS for two different clusters

### ISSUE THREAD

**Issue by basepaws-tech** [aws/aws-parallelcluster#1690]
**Environment:**
 - ParallelCluster 2.6
 - I have two cluster templates defined (light and heavy) both use the same EFS (asset). Condensed version of config:
```

[aws]
aws_secret_access_key = X
aws_access_key_id = X
aws_region_name = us-west-1

[global]
cluster_template = default
sanity_check = true
update_check = true

[cluster light]
vpc_settings = public
...
...
base_os = ubuntu1604
ephemeral_dir = /scratch
efs_settings = asset

[cluster heavy]
vpc_settings = public
...
...
base_os = ubuntu1604
ephemeral_dir = /scratch
efs_settings = asset

[efs asset]
shared_dir = /asset
encrypted = false
performance_mode = generalPurpose
efs_fs_id = fs-id
```

**Bug description and how to reproduce:**
I can start the clusters individually. I can either create "light" cluster by it self or create "heavy" cluster by itself. The EFS (asset) attaches fine in either cases. I can't start both clusters one after another.

When I start the "heavy" cluster followed by the "light" cluster, the "light" cluster fails with "MasterServerWaitCondition" error. Removing the efs_settings from the "light" cluster allows the cluster to start. Does pcluster support one EFS attaching to multiple cluster templates?

**Comment by ddeidda** [comment]
Hi.

Unfortunately a custom AMI cannot be upgraded in this way. ParallelCluster does not upgrade existing software during nodes booting.
As specified in the user guide:"After you build your own AMI, you no longer receive updates or bug fixes with future releases of AWS ParallelCluster. Also, you must repeat the steps used to create your custom AMI with each new AWS ParallelCluster release."

https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html

**Comment by ddeidda** [comment]
Hi,
thanks for reporting this issue.

We are investigating, further updates will follow.

**Comment by rexcsn** [comment]
Hi @basepaws-tech, it is a bit complicated to use the same EFS for multiple clusters because of the complication around EFS mount targets and security groups.

If all clusters are in different availability zone your cluster config should be fine. Just make sure to use a subnet that is in a different availability zone for each cluster.

If you want the clusters to be in the same availability zone, you have to create a mount target manually in that AZ, associate the mount target with a security group that only has inbound access for itself, and specify this SG with `additional_sg` in your pcluster config.

Here is an example:
Create SG `sg-06fbxxxxx (efs_only)`
Edit SG inbound rule to only allow access for itself:
```

Type | Protocol | Port range | Source | Description - optional
All traffic | All | All | sg-06fbxxxxx (efs_only) | --- 
```
Use AWS console or AWS CLI to create a mount target in the availability zone you want to launch your clusters, and associate mount target with `sg-06fbxxxxx (efs_only)`
Add `additional_sg` to vpc section in pcluster config:
```
[vpc efs]
vpc_id = ...
master_subnet_id = ...
additional_sg = sg-06fbxxxxx
```
You should be good to go and your clusters should be able to use the same EFS even if they are in the same availability zone.

**Comment by demartinofra** [comment]
Resolving since there hasn't been any update for some time. Feel free to re-open if you still have open questions/issues.
