### ISSUE TITLE
Can not create cluster: AutoScalingGroup ComputeFleet Received 1 FAILURE

### ISSUE THREAD

**Issue by ddeidda** [aws/aws-parallelcluster#1691]
From: https://forums.aws.amazon.com/thread.jspa?threadID=318577

After seeking advice from support, I updated my config.
To avoid possible errors, I clean up all previous cluster by 'pcluster delete'

Then I can't even create any cluster right now with error:

```
+Beginning cluster creation for cluster: cl-p3+
Creating stack named: parallelcluster-cl-p3
Status: parallelcluster-cl-p3 - ROLLBACK_IN_PROGRESS
Cluster creation failed.  Failed events:
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 1 FAILURE signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

my config file is as following:
```
aws_region_name = us-east-1
 
[global]
cluster_template = default
update_check = true
sanity_check = false
 
[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
 
[cluster default]
key_name = N.Vir
base_os = centos7
scheduler = slurm
master_instance_type = m5.xlarge
compute_instance_type = p3dn.24xlarge
initial_queue_size = 1
max_queue_size = 36
maintain_initial_size = true
vpc_settings = default
efs_settings = customfs
 
[vpc default]
vpc_id = vpc-ccxxxx
master_subnet_id = subnet-b65xxxx   ( point to us-east-b) 
vpc_security_group_id = sg-092c75818c80bf228
 
[efs customfs]
shared_dir = /mnt/efs
efs_fs_id = fs-19xxxx
```

Is there anything wrong with this config.
If not, 'pcluster create' can at least build a default cluster, isn't it?

Thanks.

**Comment by rexcsn** [comment]
This could potentially be an issue with cluster not having correct access to the EFS. To quickly check if it's related to EFS access, try creating a cluster without `efs_fs_id`, which will create a new EFS with the cluster.

If it succeeds that means the rest of the config is ok and the problem is with cluster unable to access the existing EFS filesystem. Please double check to make sure:
* There is no existing mount target in the availability zone of the master subnet.
* If there is a mount target you can either:
  * Remove the existing mount target so that `pcluster` can create one that will work with the cluster for you
  * Or associate the mount target with a security group that only has inbound access to itself, and specify that security group in cluster config with `additional_sg` parameter. Here is some more info on how to do that: https://github.com/aws/aws-parallelcluster/issues/1690#issuecomment-603561044

Thank you!

**Comment by demartinofra** [comment]
I'm going to resolve this one since there hasn't been any update in 23 days. Feel free to reopen if needed.
