### ISSUE TITLE
compute nodes do not function (unable to submit slurm jobs)

### ISSUE THREAD

**Issue by tarankalra-usgs** [aws/aws-parallelcluster#1732]
**Environment:**
 - AWS ParallelCluster  [aws-parallelcluster-2.6.0]
 - OS: [centos7]
 - Scheduler: slurm
 - Master instance type: [c5n.large]
 - Compute instance type: [c5n.18xlarge]

**Bug description and how to reproduce:**
I am trying to submit slurm jobs by logging into a master node. My job gets queued up but never starts. I do not see any compute nodes getting fired up on the AWS console while the master node is running.

I have full access to EC2 and S3 but do not have any other permissions associated with my IAM. 
 
Does the admin of the cluster need to add a separate policy for users to access compute nodes ? 
or is there another alternative to solve the issue ?

**Comment by rsignell-usgs** [comment]
As a new parallel cluster admin, I'm interested in this too.  Following the [User's Guide section on AIM]
(https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html) I tried creating a `ParallelClusterInstancePolicy`:
<details>
<pre>
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:AttachVolume",
                "ec2:DescribeInstanceAttribute",
                "ec2:DescribeInstanceStatus",
                "ec2:DescribeInstances",
                "ec2:DescribeRegions"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow",
            "Sid": "EC2"
        },
        {
            "Action": [
                "dynamodb:ListTables"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow",
            "Sid": "DynamoDBList"
        },
        {
            "Action": [
                "sqs:SendMessage",
                "sqs:ReceiveMessage",
                "sqs:ChangeMessageVisibility",
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl"
            ],
            "Resource": [
                "arn:aws:sqs:<REGION>:<AWS ACCOUNT ID>:parallelcluster-*"
            ],
            "Effect": "Allow",
            "Sid": "SQSQueue"
        },
        {
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:SetDesiredCapacity",
                "autoScaling:UpdateAutoScalingGroup",
                "autoscaling:DescribeTags",
                "autoScaling:SetInstanceHealth"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow",
            "Sid": "Autoscaling"
        },
        {
            "Action": [
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackResource"
            ],
            "Resource": [
                "arn:aws:cloudformation:<REGION>:<AWS ACCOUNT ID>:stack/parallelcluster-*/*"
            ],
            "Effect": "Allow",
            "Sid": "CloudFormation"
        },
        {
            "Action": [
                "dynamodb:PutItem",
                "dynamodb:Query",
                "dynamodb:GetItem",
                "dynamodb:DeleteItem",
                "dynamodb:DescribeTable"
            ],
            "Resource": [
                "arn:aws:dynamodb:<REGION>:<AWS ACCOUNT ID>:table/parallelcluster-*"
            ],
            "Effect": "Allow",
            "Sid": "DynamoDBTable"
        },
        {
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::<REGION>-aws-parallelcluster/*"
            ],
            "Effect": "Allow",
            "Sid": "S3GetObj"
        },
        {
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::NONE/batch/*"
            ],
            "Effect": "Allow",
            "Sid": "S3PutObj"
        },
        {
            "Resource": [
                "*"
            ],
            "Action": [
                "sqs:ListQueues"
            ],
            "Effect": "Allow",
            "Sid": "SQSList"
        },
        {
            "Action": [
                "iam:PassRole"
            ],
            "Resource": [
                "arn:aws:iam::<AWS ACCOUNT ID>:role/parallelcluster-*"
            ],
            "Effect": "Allow",
            "Sid": "BatchJobPassRole"
        },
        {
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::dcv-license.<REGION>/*"
            ],
            "Effect": "Allow",
            "Sid": "DcvLicense"
        }
    ]
}
</pre>
</details>
but creating this policy (after substituting `<REGION>` and `<AWS ACCOUNT ID>`) results in the error:
```
IAM resource path must either be "*" or start with user/, federated-user/, role/, group/, instance-profile/, mfa/, server-certificate/, policy/, sms-mfa/, saml-provider/, oidc-provider/, report/, access-report/.
```

So I too am interested what policy to apply for parallel cluster users (besides admin!)

**Comment by enrico-usai** [comment]
Hi all, 
I think here we have two different issues.

---

@tarankalra-usgs If you have issues with the job submission could you please share:
 - Configuration file (i.e. `~/.parallelcluster/config`) without any credentials or personal data.
 - `/var/log/jobwatcher`, `/var/log/sqswatcher` and `/var/log/slurmctld.log` logs from the Master node.

The configuration file is useful to see what are your configuration parameters, especially [max_queue_size](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#configuration-max-queue-size) and the other scaling related parameters.

The  `jobwatcher`, `sqswatcher` and `slurmctl` are useful to understand if slurm is managing correctly your jobs and if our scale logic is working correctly.

Thanks

---

@rsignell-usgs You could have some small error in the defined policy, probably due to the replacement of the `<REGION>` and `<AWS ACCOUNT ID>` placeholders.

From the message (`IAM resource path must either be "*" ...`) the issue could be in the definition of the following item:
```
 "Action": [
                "iam:PassRole"
            ],
            "Resource": [
                "arn:aws:iam::<AWS ACCOUNT ID>:role/parallelcluster-*"
            ],
            "Effect": "Allow",
            "Sid": "BatchJobPassRole"
```
Could you please double check it?
To debug the root cause of your issue it would be useful to have the whole policy you created (just replacing the account-id with a random number).

In any case, as a general suggestion, feel free to open a new issue instead of commenting to an already opened one, especially if the issue you're facing is different from the one tracked in the github issue.
It could help the users to have a more specific analysis of the problem.

Let us know if it helps or feel free to open e new issue if needed.

Thanks

**Comment by rsignell-usgs** [comment]
@enrico-usai , thanks so much for your reply.   Indeed, we had something wrong with the AWS account/zone info.   Instead of editing the policy by hand we used search and replace in text editor, and then the policy was fine.   

But working with @tarankalra-usgs we discovered that creating this policy was not what we needed.  
We simply needed to add the existing policy `AWSCloudFormationFullAccess` to the group policy and then the user was able to use `pcluster start` and `pcluster stop`, and also run jobs on the resulting cluster! 

In case it's useful to others, here are the group policies that worked:
![2020-04-13_11-06-30](https://user-images.githubusercontent.com/1872600/79131830-3b700a00-7d77-11ea-829d-e1a49bba7d8e.png)
