### ISSUE TITLE
sbatch job in pending state while the compute fleet is running

### ISSUE THREAD

**Issue by tarankalra-usgs** [aws/aws-parallelcluster#1746]
**Environment:**
 - AWS ParallelCluster 2.6.1]
- configuration file 
```aws_region_name = us-west-2

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = reaper
base_os = centos7
scheduler = slurm
enable_efa = compute
master_instance_type = c5n.large
compute_instance_type = c5n.18xlarge
disable_hyperthreading = true
cluster_type = spot
spot_bid_percentage = 80
placement_group = DYNAMIC
placement = cluster
initial_queue_size = 1
max_queue_size = 8
maintain_initial_size = true
#enable_intel_hpc_platform = true
compute_root_volume_size = 80 #Intel HPC Platform
#fsx_settings = myfsx
ebs_settings = myebs
vpc_settings = myvpc

[vpc myvpc]
vpc_id = vpc-fxxxx
master_subnet_id = subnet-0xxxxxxxxxxxxxxx
compute_subnet_id = subnet-0xxxxxxxxxxxxxx
use_public_ips = false

[fsx myfsx]
shared_dir = /fsx
storage_capacity = 13200
import_path = s3://coawst
export_path = s3://coawst

[ebs myebs]
shared_dir = shared
volume_type = gp2
volume_size = 300  # Intel HPC Platform
```

**Bug description and how to reproduce:**
I have configured a compute fleet and the instance state of that compute fleet is based on the configuration file above. The compute fleet is running as I can see it on the AWS console. 

However, the job that I submit on the compute node remains queued. One would think that with the compute fleet running as indicated by the AWS console, the job would not be in a pending state but get queued. I am not using the compute fleet for any other jobs. 

I have tried to stop pcluster and start it again. However, it does not help. Any cues would help ?

**Comment by rexcsn** [comment]
Hi @tarankalra-usgs ,

Note that compute nodes need to be setup and present in the scheduler configuration to be ready to run a job. This may take a few minutes after the actual compute instance is launch and you are able to see the instance in your EC2 console.
To check which nodes are in your slurm configuration, do `sinfo` or `scontrol show nodes`

If you are seeing a persistent problem with instances not appearing in scheduler configuration, please attach the following logs which are under `/var/log` in the master instance so we can better debug the issue:
* `sqswatcher`
* `jobwatcher`
* `slurmctld.log`
Since you are using v2.6.1 which has CloudWatch logging enabled by default, you can also retrieve these logs in the CloudWatch console.

Thank you.

**Comment by privojack** [comment]
I recently ran into this with a VPC that was using a private DNS domain for its DHCP option set with Slurm.  in `/var/log/syslog` on the compute nodes, I saw DNS failures in the final bootstrapping steps.

Flipping to `ec2.internal` for my DHCP option set resolved these issues.  

If you can post any logs that will be helpful, this is a total shot in the dark on the DNS/DHCP recommendation from somebody who just had to deal with it 😄
