### ISSUE TITLE
Error while creating compute fleet while using custom image created using EC2 Imagebuilder service

### ISSUE THREAD

**Issue by SivaKanishka** [aws/aws-parallelcluster#1789]
I know a similar issue is posted [here](https://github.com/aws/aws-parallelcluster/issues/1648). I followed the suggested changes, but couldn't resolve it.

**Environment:**
 - AWS ParallelCluster version - aws-parallelcluster-2.6.1
 - OS: centos7
 - Scheduler: slurm
 - Master instance type: m3.medium
 - Compute instance type: m3.medium

**Bug description and how to reproduce:**
I have built a custom AMI using EC2 Imagebuilder service with centos7 AMI supported by the Parallel cluster (AMI ID: ami-0dc8c5f93897f1809). I installed my custom software using the EC2 imagebuilder service. The AMI creation was successful. After configuring the parallelcluster as mentioned below, I got the mentioned error in the title. Both Master and Compute nodes are on the same public subnet, and **use_public_ips** value is set to true in config file. Following is the error:
**AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 1 FAILURE signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement**

**Additional context:**
Any other context about the problem. E.g.:
 - configuration file 
```
[aws]
aws_region_name = us-west-2

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = <key name>
master_instance_type = m3.medium
compute_instance_type = m3.medium
master_root_volume_size = 25
scheduler = slurm
base_os = centos7
custom_ami = ami-xxxxx
initial_queue_size = 1
max_queue_size = 2
maintain_initial_size = true
vpc_settings = hpc-test

[vpc hpc-test]
vpc_id = vpc-b43b33cd
master_subnet_id = subnet-xxxxx
vpc_security_group_id = sg-xxxxx
use_public_ips = true
```
- There are no pre/post-install scripts
- [cfn-init.log](https://github.com/aws/aws-parallelcluster/files/4634426/cfn-init.log)
- [cloud-init.log](https://github.com/aws/aws-parallelcluster/files/4634445/cloud-init.log)
- I was not able get the logs from compute node. It got terminated, and re-spawned. There are no log file in the re-spawned compute node.

**Comment by lukeseawalker** [comment]
Hi @SivaKanishka,
if a compute node was terminated due to failure, there will be a directory `/home/logs/compute` in the master node. Attach one of the `instance-id.tar.gz` from that directory.
 
If there is no `/home/logs/compute` in the master node we need to retrieve the logs from the compute node in an alternative way:
- re-create the cluster with the --norollback flag
- go to EC2 > Autoscaling > parallelcluster-[cluster_name]
- check Enable instance scale-in protection and suspend all processes  
- go to EC2 > Security Groups > search for parallelcluster-[cluster_name]-ComputeSecurityGroup
- edit the inbound rule and add SSH access from your IP address (or anywhere)

Now find the ip address of the compute node from the EC2 console and ssh into the instance. Once on the instance retrieve the /var/log/cfn-*, /var/log/cloud-* and /var/log/messages logs.

Please remember to remove the configuration done in the above steps and to remove the instance by hand once the logs are retrieved.

**Comment by SivaKanishka** [comment]
Hi @lukeseawalker,

Thanks for taking time to look at the previous logs. I was able to follow the steps you mentioned and fetch the logs from compute node. Here are the logs:
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/4662856/cfn-init.log)
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/4662857/cfn-init-cmd.log)
[cfn-wire.log](https://github.com/aws/aws-parallelcluster/files/4662858/cfn-wire.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/4662861/cloud-init.log)
[messages.log](https://github.com/aws/aws-parallelcluster/files/4662875/messages.log)

Thanks,
Siva

**Comment by lukeseawalker** [comment]
Can you please run the following three commands from the master host and post the output here?
```
showmount -e localhost

rpcinfo -u localhost nfs 3

rpcinfo -u localhost nfs 4
```

**Comment by SivaKanishka** [comment]
These are the outputs,
**showmount -e localhost**
```
Export list for localhost:
/opt/slurm 172.31.0.0/16
/opt/intel 172.31.0.0/16
/home      172.31.0.0/16
/shared    172.31.0.0/16
```
**rpcinfo -u localhost nfs 3**
```
program 100003 version 3 ready and waiting
```
**rpcinfo -u localhost nfs 4**
```
rpcinfo: RPC: Program/version mismatch; low version = 3, high version = 4
program 100003 version 4 is not available
```

**Comment by lukeseawalker** [comment]
The reason why the compute is not able to join the cluster is that it is not able to mount the `/home` shared dir from the master node.
The failing command is
```
mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-172-31-10-15.us-west-2.compute.internal:/home /home
STDOUT: 
STDERR: mount.nfs: Connection timed out
```
Unfortunately the root cause is still unclear to me.
Is the problem always reproducible whenever you try to create a new cluster?
Does it happen when you create a cluster without specifying the `custom_ami` parameter?

**Comment by SivaKanishka** [comment]
Yes, even without `custom_ami` option, the cluster creation always stops during compute fleet setup

**Comment by demartinofra** [comment]
I've been trying to reproduce this issue but without any success. I'm wondering if your specific VPC/Subnet setup is the culprit here.

Could you try to use pcluster configure and let it create a new vpc and public subnet. Then just create a cluster with the networking setup produced by pcluster configure. This is just to understand if the issue is vpc specific.

**Comment by SivaKanishka** [comment]
Hi @demartinofra,
Thanks for taking to resolve this. I will try to new vpc and subnet and give it a try. The current VPC and subnet are default ones. Subnet had internet gateway in its route table.

As a side note, we can you look at [this](https://github.com/aws/aws-parallelcluster/issues/663#issuecomment-632984794). We have the same observation as that comment.

**Comment by demartinofra** [comment]
From the cfn-init.log that you posted I see that the node address is present in the mount command when it fails:
```
mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-172-31-10-15.us-west-2.compute.internal:/home /home
```

Why do you think your problem relates to that comment? Can you check that `ip-172-31-10-15.us-west-2.compute.internal` is the correct address of the master node? Also did you get the chance to try with a new vpc/subnet created by pcluster?

**Comment by SivaKanishka** [comment]
I was able to bring the cluster up by creating new vpc/subnet using pcluster. The difference I found was the security groups attached to master and compute nodes. In the previous config, my security group **didn't** have all the ports open to a security group attached to compute/master node. I might have missed this in the documentation while I was configuring earlier. Maybe this should be highlighted in the documentation.
Regarding node address issue, the node address was correct. I missed that and referred it in my previous comment.
