### ISSUE TITLE
Install software in Compute Node

### ISSUE THREAD

**Issue by kausikbakshi** [aws/aws-parallelcluster#1807]
I am using pcluster config file like:

[cluster default]
key_name = abckey
vpc_settings = public
master_instance_type = m5.2xlarge
compute_instance_type = c5.18xlarge
The Master instance created successfully 

After that I write a **helloworld.sh** file where I use:
mpirun -np 144 ruby -v
or 
mpirun -np 144 hostname

both cases it generates 2 compute nodes and throw a output file named helloworld.sh.o1
which contains 72 same hostnames and 72 other hostnames for "mpirun -np 144 hostname"
or 
which contains 144 same ruby version.

Now my query is:

Instead of mpirun -np 144 hostname command I used mpirun -np 144 ruby -v and its returns 144 ruby version line. in **helloworld.o1** file because AWS has default ruby installed in every instance. But I need some different fundamentals. After generating dynamically compute node by mpi command (e.g. mpirun -np 144 hostname) , I want to install some software package (e.g. imagemagic or anything which is not present in AWS instance by default)  dynamically in these compute node and there after want to see the version of this software package from compute node in helloworld.sh.o1 file. Is it possible ? if so then please help.

Thanks in advance

**Comment by demartinofra** [comment]
In order to install custom software I would recommend to look at the following options:
- [Custom Bootstrap Actions](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html): allows you to define a script that is automatically executed at runtime every time a node is bootstrapped
- [Building a Custom AWS ParallelCluster AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html): describes how to build your own custom AMI that already contains all required software so that no runtime installation is needed when you launch new compute instances

In case you want to run an mpi program which executes a single process per node you could look at the `--map-by ppr:1:node`. By using -np 144 you are launching 144 processes running the specified command. 
Based on the scheduler you can also use different commands to achieve the expected result. 
For example with Slurm you could run `sbatch -N 2 test.sh` where test.sh contains the following code:
```
#!/bin/bash
srun hostname
```
