### ISSUE TITLE
disabling hyperthreading after the cluster up

### ISSUE THREAD

**Issue by porcaro33** [aws/aws-parallelcluster#1876]
**Environment:**
 - AWS ParallelCluster 2.7.0
 - Configuration file (i.e. ~/.parallelcluster/config) 

**Bug description and how to reproduce:**
This is not bug report. This is question.
I spun-up a cluster with parallelcluster 2.7.0 and install various apps/libs/configs on top of the cluster.
but I found I forgot to disable hyperthreading. I already spent a few days for additional cluster settings.
Are there any way to disable hyperthreading after the cluster up.

config
# parallelcluster version 2.7.0
[global]
update_check = true
sanity_check = true
cluster_template = default

[aws]
aws_region_name = us-west-2

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[vpc HPC_VPC]
vpc_id = vpc-XXXXXXXXX
master_subnet_id = subnet-XXXXXXXXX
compute_subnet_id = subnet-XXXXXXXXXXX
additional_sg = sg-XXXXXXXXX
use_public_ips = false

[cluster default]
vpc_settings = HPC_VPC
key_name = parallel-cluster
master_instance_type = m5.2xlarge
compute_instance_type = r5.24xlarge
initial_queue_size = 0
max_queue_size = 10
maintain_initial_size = false

scheduler = sge
cluster_type = ondemand

ephemeral_dir = /scratch
shared_dir = shared
encrypted_ephemeral = false
ebs_settings = shared

master_root_volume_size = 50
compute_root_volume_size = 30
base_os = centos7
ec2_iam_role = parallecluster_EC2_role
disable_hyperthreading = false
scaling_settings = custom

placement_group = DYNAMIC
placement = compute
enable_intel_hpc_platform = false
dcv_settings = custom-dcv

#extra_json = { "cluster" : { "ganglia_enabled" : "yes" } }

[dcv custom-dcv]
enable = master

[ebs shared]
volume_type = gp2
volume_size = 4000
encrypted = false

[scaling custom]
scaledown_idletime = 15

**Comment by ddeidda** [comment]
Hi @porcaro33.

Updating the ``disable_hyperthreading `` parameter on a running cluster is currently not officially supported.

An alternative (working with a postinstall script) is described in [this guide](https://github.com/aws/aws-parallelcluster/wiki/How-to-disable-Intel-Hyper-Threading-Technology). Please note that this guide is referred to Amazon Linux; the provided script could need to be adapted to work on other OSs. 

Once updated the ``extra_json`` and the ``post_install`` parameters you should run a [pcluster update](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.update.html) command.
Hope this helps.

**Comment by porcaro33** [comment]
@ddeidda Thanks for your reply. I tried to "pcluster update", but the update fail every time with "Error Code: InvalidNetworkInterface.InUse". This may related to https://github.com/aws/aws-parallelcluster/issues/1628

Is there other way to add "extra_json = { "cluster" : { "cfn_scheduler_slots" : "cores" } }"?

**Comment by ddeidda** [comment]
@porcaro33 
the extra_json parameter should not be affected by the issue you mentioned, but maybe you had already tried updating the cluster (maybe just to set disable_hyperthreading to true) and now unfortunately you can't run other updates on it, as described in the issue you mentioned.

At this point the best option is probably to re-create the cluster. 
To save the work you did on your master instance you could explore the possibility of making [your own custom AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html). Since your cluster is already up, running and customized you could use the [first method](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html#modify-an-aws-parallelcluster-ami), starting directly from point n. 7.

Hope it helps.

**Comment by porcaro33** [comment]
Any plan to release the update commands patch quickly?

**Comment by rexcsn** [comment]
Hi @porcaro33,

To summarize the discussion here:

Unfortunately updating `disable_hyperthreading` is not supported today, but we currently don't have any validation or warning to prevent user from doing this operation.
After the upcoming update patch, we will warn the user if user is trying to update a parameter that is not supported, such as `disable_hyperthreading`. As a result, the user can know the current limitations of `pcluster update` and can prevent breaking the cluster by updating a parameter that is not supported.
If you would like to see support for updating `disable_hyperthreading` added, please let us know, and we will evaluate this feature request internally.

As for your original issue, in order to use a cluster with hyperthreading disabled, the only way is to re-create the cluster, with the config parameter `disable_hyperthreading=true`.
*Note: The instance types you are currently using, `m5.2xlarge` and  `r5.24xlarge`, do support this option, but not all instance types support using this option, see our documentation [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#disable-hyperthreading). For instance types that do not support `disable_hyperthreading` option, you can still disable hyperthreading manually following the instruction in this thread [here](https://github.com/aws/aws-parallelcluster/issues/1855#issuecomment-653549084).*

Please let us know if you have other question or concern. Thank you!

**Comment by porcaro33** [comment]
@rexcsn  @ddeidda 
I decided to re-create my whole cluster and will use post install for disabling HT. Thank you for answering to my question.
