### ISSUE TITLE
parallelcluster integrated with Active Directory

### ISSUE THREAD

**Issue by luyang93** [aws/aws-parallelcluster#1899]
**Environment:**
 - aws-parallelcluster-2.7.0
 - [config](https://pastebin.com/6CeBaiR0)

**Bug description and how to reproduce:**
 - I need to add pcluster to Active Directory. It needs to change DNS ip address to Domain Controller ip address. So I edit the dhcp option set of the VPC, from domain-name: cn-northwest-1.compute.internal, domain-name-servers: AmazonProvidedDNS to domain-name: example.com,  domain-name-servers: 10.0.4.200(Domain Controller ip). Then master and compute host cannot communicate with each other. I have to change dhcp option set to the origin one(AmazonProvidedDNS)

How can I add master and compute host to a self-manage Active Directory.
I have tried, add a seperate EC2 centos7 instance in Active Directory with sssd, it works well.

**Comment by tilne** [comment]
The Amazon-provided DNS is necessary for the node's of a cluster to be able to communicate with one another. You'll need to specify multiple DNS servers in the DHCP option set. This documentation should help: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html.

I've added the "enhancement" label because I better support for custom DNS configurations is something we've been looking into recently.

**Comment by luyang93** [comment]
I tried many dhcp-option sets, but none of them worked well.

1. 
domain-name: example.com cn-northwest-1.compute.internal
domain-name-servers: 10.0.4.200, AmazonProvidedDNS

2.
domain-name: cn-northwest-1.compute.internal example.com
domain-name-servers: 10.0.4.200, AmazonProvidedDNS

3.
domain-name: cn-northwest-1.compute.internal
domain-name-servers: 10.0.4.200, AmazonProvidedDNS

4.
domain-name: cn-northwest-1.compute.internal
domain-name-servers: AmazonProvidedDNS, 10.0.4.200

5.
domain-name: example.com cn-northwest-1.compute.internal
domain-name-servers: 10.0.4.200

6.
domain-name: example.com cn-northwest-1.compute.internal
domain-name-servers: AmazonProvidedDNS, 10.0.4.200



which one may be the right one?

**Comment by luyang93** [comment]
can I follow this blog?
it doesn't set Amazon-provided DNS
https://aws.amazon.com/cn/blogs/opensource/aws-parallelcluster-aws-directory-services-authentication/
https://d2908q01vomqb2.cloudfront.net/ca3512f4dfa95a03169c5a670a4c91a19b3077b4/2019/07/31/image-3.png

**Comment by joeydumont** [comment]
It's been almost a month, so you probably figured something out, but here's what I did.

To solve the DNS issues, I installed `unbound` on the master node, and configured the compute nodes to use the master node as their DNS server. I used the `pre_install` and `post_install` scripts to do that. Take a look at [this page](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-static-dns-ubuntu-debian/) to ensure that DNS changes are permanent.

Here's the relevant portion of my unbound.conf

```forward-zone:
 name: "domain_fqdn."
 forward-addr: domain_controller_ip_1
 forward-addr: domain_controller_ip_2

forward-zone:
 name: '<region>.compute.internal'
 forward-addr: 169.254.169.253 # Amazon DNS
```

I think I set `private_address` to the VPC CIDR as well, so that unbound returns private IPs for that range. `domain_insecure` was also necessary for both the domain_fq and `<region>.compute.internal`.

For the domain join part, I put the AD join account creds in Parameter Store, and added these sections to the `UserData` of both MasterServer and ComputeFleet launch templates:

```json
{
          "NRCJoinDomain": {
            "packages": {
              "yum": {
                "sssd": [],
                "realmd": [],
                "oddjob": [],
                "oddjob-mkhomedir": [],
                "adcli": [],
                "samba-common": [],
                "samba-common-tools": [],
                "krb5-workstation": [],
                "openldap-clients": [],
                "policycoreutils-python": [],
                "jq": []
              }
            },
            "commands": {
              "001_joindomain": {
                "command": "sudo realm join -v -U '{{resolve:ssm:/path/to/JoinDomainServiceAccountUsername:1}}' --computer-name 'Master' <domain_fqdn> <<< {{resolve:ssm:/path/to/JoinDomainServiceAccountPassword:1}}"
              }
            }
          }
}
```

Note that this is not super robust, as (1) you need to provide the exact version of the parameter in your CFN template and (2) you can't put the password in a `SecureString` as `{{resolve:ssm-secure}}` won't work in a `UserData` field. If you have suggestions, I'd like to hear them. To somewhat secure the credentials, I set up IAM roles that restrict access to a certain prefix in Parameter Store to a specific group of users.

In the `additional_cfn_template`, I set up a lifecycle hook for the ComputeFleet that triggers a Lambda function when a node is terminating and removes it from the domain.

Hope this helps, and feel free to reach out if you have questions.

**Comment by demartinofra** [comment]
Hi @luyang93 

apologies for the late reply. Are you still blocked by this issue? 

Starting with ParallelCluster 2.9, when the Slurm scheduler is used ParallelCluster automatically configures a DNS domain for the cluster (`${ClusterName}.pcluster`) and registers all nodes on that domain. If you need to have nodes on a custom domain in order to join an AD for example then you need to follow these steps:
1. Add the `disable_cluster_dns = true` option to the `[cluster]` section in your config
2. Configure a custom DHCP option set and have:
```
domain-name: example.com
domain-name-servers: 10.0.4.200
```
3. You need to take care of registering cluster nodes in your DNS as they are launched by ParallelCluster. For this you can use a pre-install script which retrieves the `hostname` and the private ip from the node where it's running and adds a record `$hostname.example.com` to your DNS server which points to the node private IP. Also make sure your name server is able to resolve records for public domains or has a properly configured forwarding rule for anything which is not example.com otherwise the cluster won't be able to access the internet.

Let us know if you need additional support.

Francesco

**Comment by gwolski** [comment]
@demartinofra I have successfully enabled my launching machines to use a pre-install script to do a realm join with my Azure based Active Directory Domain Services service...  However, I start running into issues if I run more than one machine in the cluster.  Additional hosts fail to register, authentication issues, permission denied, etc....  

 I suspect it has to do with the created hostnames being longer than 15 characters and no uniqueness in the first 15 characters.  Microsoft has a warning (and it's a known NETBIOS limitation) that you shouldn't have hostnames greater than 15 characters (I guess you can if the uniqueness is in the first 15 characters).  You can see the limitation documented  here:

https://docs.microsoft.com/en-us/azure/active-directory-domain-services/join-centos-linux-vm

where it states a requirement:
"Unique Linux VM names that are a maximum of 15 characters to avoid truncated names that might cause conflicts in Active Directory"

The parallel cluster documentation is clear on how hosts are named, but there is no way to change it...  So my hosts end up with names of the form:

simc2m16-spot-dy-r5large-[1-25]

where the uniqueness ends up in the last one or two characters, i.e. the instance count...  Well past the 15 character point.

Is there a workaround I'm missing?

Alternatively, does anyone know a way to not join the AD for DNS, rather use the normal Route53 *.pcluster domain, and just use my AD for user authentication -- I really don't know the best answer for that.   Thanks in advance.

**Comment by enrico-usai** [comment]
Hi @gwolski 
I think this should help: https://github.com/aws/aws-parallelcluster/issues/2577#issuecomment-810401832

Enrico
