### ISSUE TITLE
Pcluster launch create fail

### ISSUE THREAD

**Issue by sumedhjain** [aws/aws-parallelcluster#1902]
**Environment:**
 aws-parallelcluster-2.8.0 & 2.7.0

 - Configuration file 
`[aws]
aws_region_name = eu-west-1

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = mycfdEU
base_os = alinux2
tags = {"Name": "CFDEU2"}
master_instance_type = t2.micro
compute_instance_type = c5.metal
max_queue_size = 20
initial_queue_size = 0
maintain_initial_size = true
vpc_settings = default
cluster_type = spot
spot_price = 1.65
custom_ami = ami-06c1b20396c5551f3
placement_group = DYNAMIC
placement = compute
scheduler = sge
#enable_efa = compute
s3_read_write_resource = arn:aws:s3:::cfd7/*
dcv_settings = default
scaling_settings = default
#fsx_settings = fs
#compute_root_volume_size = 25

[dcv default]
enable = master

[vpc default]
vpc_id = vpc-XXXXX
master_subnet_id = subnet-XXXXX

#[fsx fs]
#shared_dir = /fsx
#storage_capacity = 1200
#deployment_type = SCRATCH_1

[scaling default]
scaledown_idletime = 5
#scaling_threshold = 1
#scaling_adjustment = 1
#scaling_threshold2 = 80
#scaling_adjustment2 = 5
#scaling_period = 60
#scaling_evaluation_periods = 2
#scaling_cooldown = 120`

Error Screenshot: 
![Screenshot from 2020-07-27 21-43-22](https://user-images.githubusercontent.com/64367379/88565427-372fda00-d052-11ea-86bd-fd27fe476132.png)

**Bug description and how to reproduce:**
Error thrown at cluster creation. Rolback clipped and require log files are attached. Cluster launch tried on two version of Pcluster (2.7.0 & 2.8.0)

 **- if the cluster fails creation, please re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node**
[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/4983108/cloud-init-output.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/4983109/cloud-init.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/4983110/cfn-init.log)
Require logs are attached.

**Comment by sumedhjain** [comment]
The exact config was used earlier to successfully create a cluster. This error started to occur recently.

**Comment by sumedhjain** [comment]
Master server node was changed to g4dn.xlarge to avoid the DCV error but same error was thrown.

**Comment by demartinofra** [comment]
Hi, I'm looking into this. Getting back to you soon.

**Comment by demartinofra** [comment]
`custom_ami = ami-06c1b20396c5551f3` is an AMI that was prepared with `pcluster` version `2.6.1`. As also pointed out in the official [product documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html) a custom AMI is not compatible across different versions of the product.

In your specific case, using an AMI meant to work with version 2.6.1 is causing, among other things that can make your cluster setup unstable, some artifacts to be re-downloaded at runtime. Among these artifacts there is the intel_mpi package that is failing during download due to some unavailability of the Intel endpoint hosting the artifacts. We are following up with Intel to address such issue. 
In any case in order to use that specific custom AMI you are required to use `aws-parallelcluster` 2.6.1, which would currently work as expected, otherwise the cluster risks to be launched with an inconsistent setup. To make this even more clear for customers we are working on introducing additional validations so that this is prevented by the CLI at cluster creation time.

Let us know if we can support you with any other open question or issue you are facing.

**Comment by sumedhjain** [comment]
@demartinofra I was under the impression that ami are compatible across pcluster versions. Thank you for your input. 
It is working with pcluster 2.6.1. I am new to cluster creation. 
Running on older versions might cause problems for me in future?

**Comment by demartinofra** [comment]
Running on older versions won't give you access to the latest features but it should not be a source of errors. [Release notes](https://github.com/aws/aws-parallelcluster/releases) and [changelog](https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.rst) can give you an overview of the features and fixes you are missing out on.

We do recommend to upgrade to latest ParallelCluster version when creating a new cluster in order to get all latest enhancements but if rebuilding your custom AMI is too much of a pain you can stick to that version for now. What I can add on top of that is that we are doing some work in order to simplify and streamline the custom AMI creation process so that it'll be easier in the future to keep up with newer releases of ParallelCluster without having to re-do most of the work needed to create the custom AMI at every new release.

Let me know if we can help with anything else or resolve the issue

**Comment by gregjohnso** [comment]
> The exact config was used earlier to successfully create a cluster. This error started to occur recently.

+1 Same thing here.

**Comment by demartinofra** [comment]
@gregjohnso the fact that the error started to appear recently was due to a temporary unavailability of an Intel endpoint. The intel endpoint was required because the cluster was trying to apply new bootstrap scripts (coming from 2.8) on an AMI baked for (2.6).

While the issue with the Intel endpoint has been addressed I still highly discourage you from using an older AMI with a newer ParallelCluster version since there is no guarantee the cluster can be launched with a consistent setup.
