### ISSUE TITLE
pcluster createami fails - Could not get lock /var/lib/dpkg/lock-frontend

### ISSUE THREAD

**Issue by gregjohnso** [aws/aws-parallelcluster#1904]
**Environment:**
 - aws-parallelcluster==2.8.0
 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.

**Bug description and how to reproduce:**
I ran the following command to create an custom ParallelCluster ami
`pcluster createami --ami-id ami-037176e5332a04eb6 --os ubuntu1804 -i p3.2xlarge`

The ami is "Deep Learning AMI (Ubuntu 18.04) Version 30.0"

**Additional context:**
It looks like a file locking issue
[stdout.txt](https://github.com/aws/aws-parallelcluster/files/4989646/stdout.txt)
[packer.log.20200728-090506._i8r0xb6.txt](https://github.com/aws/aws-parallelcluster/files/4989653/packer.log.20200728-090506._i8r0xb6.txt)

**Comment by demartinofra** [comment]
This looks like an issue with the DL AMI you are using. I have the feeling the DL AMI was created while the installation/udpate was in progress, leaving the package manager in a bad state. 

Let me see if there is something we can do. In the meanwhile to get you unblocked you could try starting from a previous version of the DL AMI.

**Comment by tilne** [comment]
This is fixed by [this aws-parallelcluster-cookbook PR](https://github.com/aws/aws-parallelcluster-cookbook/pull/684). The problem was that, although the AMI build was waiting for the service that identifies and downloads the packages that are eligible for updating to release a lock before stopping it, it was not waiting for and then stopping the service that actually applies the updates.
