### ISSUE TITLE
quick question regarding openmpi on pre-built centos7 AMIs

### ISSUE THREAD

**Issue by keien** [aws/aws-parallelcluster#1931]
just wanted to know where I can find the build/install procedure for the openmpi install that is available on the centos7 AMI, as we wanted to replicate it on our own servers that doesn't use the pcluster AMIs

I found this wiki doc but I can't tell if this is the most up-to-date instructions: https://github.com/aws/aws-parallelcluster/wiki/OpenMPI-Install-from-Source-and-Uninstall

**Comment by enrico-usai** [comment]
Hi @keien 

As you can see in the cookbook package [we're installing](https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.8.1/attributes/default.rb#L165)  mpich-devel and openmpi-devel packages from the standard OS repositories.

When using an EFA powered instance [we're removing](https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.8.1/recipes/efa_install.rb#L31-L36) openmpi-devel and openmpi packages because the default openmpi installation conflicts with the one installed with EFA.

If you want to use both flavours or you have specific requirements you can follow [the guide](https://github.com/aws/aws-parallelcluster/wiki/OpenMPI-Install-from-Source-and-Uninstall) you linked.

Let us know if it helps.

**Comment by keien** [comment]
thanks, that helps a lot
