### ISSUE TITLE
After cfncluster stop/start new nodes are not showing up in sinfo

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#207]
Hi, I am using cfncluster 1.3.2 and deploying a cluster in us-west-2. Below is my configuration file.
After cfncluster stop, I did cfncluster start using --reset-desired, I see ec2 nodes starting on ec2 dashboard. However, sinfo does not show those nodes and seems to have history of old nodes that were launched before cfncluster stop. 

Let me know if you need any more information. Appreciate your help!

```
[cluster default]
vpc_settings = public
key_name = xxxxxxxx
master_instance_type = m4.2xlarge
compute_instance_type = m4.xlarge
initial_queue_size = 4
max_queue_size = 20
maintain_initial_size = true
placement_group = DYNAMIC
master_root_volume_size = 20
compute_root_volume_size = 20
base_os = ubuntu1604
ebs_settings = custom
scheduler = slurm
custom_ami = ami-xxxxxx
s3_read_resource = xxxxx
s3_read_write_resource = xxxxxx

[ebs custom]
volume_type = gp2
volume_size = 100

[vpc public]
master_subnet_id = xxxxxxxx
vpc_id = vpc-xxxxxxx

[global]
update_check = true
sanity_check = true
cluster_template = default
```

**Comment by mohanasudhan** [comment]
Can you verify slurm log file? Please copy-paste here so it can help in debugging

**Comment by adavanisanti** [comment]
@mohanasudhan Where can I find slurm log file? I see slurm.conf in /opt/slurm/etc/slurm.conf.

**Comment by bwbarrett** [comment]
There are a couple files worth looking at (on the master node).  First is `/var/log/sqswatcher`, which has entries every time an SQS message arrives for a instance being added / removed from the cluster.  If you don't see call-ins there, then there's no chance slurm will be updated properly.  The next is `/var/log/slurmctld.log`, which is the general slurm log.  There should be some matching entries about restarting slurm and the like in `slurmctld.log` around the time for each entry in `sqswatcher`.

I will say that there are lots of dragons around the `stop` and `start` in CfnCluster.  If you leave your cluster down for too long (> 4 hours), nodes won't be removed properly.  What state gets restored after a `start` is a little surprising to some customers.  It's honestly a feature I'd like to remove (and just make it easier to stop all / restart X number of compute nodes).

**Comment by adavanisanti** [comment]
@bwbarrett Following up from issue #209. Will using centos6 help with this issue of start and stop?

**Comment by mohanasudhan** [comment]
we plan to have this fix https://github.com/awslabs/cfncluster-cookbook/pull/37 in next release.

**Comment by tedm** [comment]
every time I try to run this, I get this error at the end of the script:

The following resource(s) failed to create: [ComputeFleet].
CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | ComputeFleet | Received 1 FAILURE signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

Config is:

[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_access_key_id = xxx
aws_secret_access_key = xxx
aws_region_name = us-west-2

[cluster default]
vpc_settings = public
key_name = xxx
compute_instance_type = t2.micro
master_instance_type = t2.micro
initial_queue_size = 1
max_queue_size = 5
maintain_initial_size = true
scheduler = sge
cluster_type = ondemand
master_root_volume_size = 15
compute_root_volume_size = 15
base_os = ubuntu1404

[vpc public]
vpc_id = vpc-xxx
master_subnet_id = subnet-xxx

I've checked the cfn* logs on the master once with --norollback, but it didn't give any more detailed info.? Depending on instances config, sometimes the error will be 1/2 for the ComputeFleet, so create of master always succeeds, and on occasion, one compute instance??

Thanks for any suggestions.

**Comment by mohanasudhan** [comment]
Can you verify cfn* logs in compute node ?

**Comment by tedm** [comment]
@mohanasudhan Have been working on debugging this. You are correct in that the compute nodes do come up, even with the errors. So looking at the logs in the compute nodes, it looks like they're not succeeding mounting the /shared share by DNS. I'm thinking that because I am firing this up in our main default VPC, and not creating new VPCs, that our DNS/DHCP services for our VPC aren't registering the DDNS of the new instances. I can probably get this to run manually at this point, or create a new VPC with the DNS that the cfn scripts are expecting. Thanks for the help. I'll continue working on this.

**Comment by demartinofra** [comment]
Hi,

I'm going to resolve this issue since it refers to a very old version of CfnCluster and in the meanwhile the node activation and registration process got largely improved.

Regarding custom DHCP option set configuration: ParallelCluster requires the internal VPC DNS server to resolve the private FQDN of the instances that is used to configure the scheduler. At the moment we don't have a proper way to support custom DNS configs but you could look at https://github.com/aws/aws-parallelcluster/issues/1192#issuecomment-512237121 for a working solution.
