### ISSUE TITLE
Add support to stop/start the head node when instance storage is present on the EC2 instance

### ISSUE THREAD

**Issue by acastanedam** [aws/aws-parallelcluster#2080]
**Environment:**
Same https://github.com/aws/aws-parallelcluster/issues/2067#issue-708093322

**Bug description and how to reproduce:**
Thanks @lukeseawlaker for the fixing of issue #2067, now it is working (in the `develop`
branch). Unfortunately, I have another problem, when I try to start
the cluster, the master server does not pass the `Instance status
checks` and it is not reachable. If I create, just a single instance
(without `pcluster`), then after stopping, the restarting proceeds
without any problem. What could be the problem?.

**Comment by demartinofra** [comment]
Hi @acastanedam 

Can you please detail the steps that I can follow to reproduce the issue you are facing? When you refer to starting/stopping a cluster, what type of operation you are performing to achieve that? My understanding is that you are also stopping the master server which is not something we support natively in ParallelCluster so I need some additional details to understand the sequence of steps you are performing.

Francesco

**Comment by acastanedam** [comment]
Hi @demartinofra

After the creation of the cluster, I stop both the master and the
compute node, the first with the `awscli` and the second with
`pcluster stop`. Then I try to do the same for the restarting process,
i.e, using `awscli` for the master and `pcluster start` for the
compute node. The problem is the master does not pass the Status
Checkings, and although is running, it is not reachable, can not do
`ssh`. This could look like an issue in `awscli`, but when I just
create one instance in the aws console, this does not happen.

**Comment by demartinofra** [comment]
Thanks for detailing the steps you are following.

First of all I have a general comment on stopping the head node: while I totally understand the reason why you are doing that, this is not a feature that today is officially supported by the product. This means that you might face a series of issues when trying to stop the head node of the cluster like the one you are reporting here. Moreover keep in mind that the head node is responsible to stop/start the compute fleet so you should make sure that you don't terminate the head node until the compute fleet enters a stopped state (which can be retrieved by running pcluster status).

Now getting back to your problem I think I know what is causing the failure in restarting the head node of the cluster: this is most likely due to the fact that the instance used as master node (`z1d.2xlarge`) has an instance store. When an instance with local storage is used, ParallelCluster takes care of formatting and mounting the ephemeral drive. Also, in order to automatically remount the instance store on head node restarts, ParallelCluster creates an entry in fstab which remounts the ephemeral drive automatically on reboots. Now when you stop and start an instance with an instance store the ephemeral drive is replaced by EC2 and ParallelCluster currently does not have any logic to format and mount the new drive. Because of this the bootstrap of the instance fails and it enters an unreachable status.
To unblock your use case you could remove the entry in /etc/fstab related to the ephimeral drive but this means that you won't have any ephemeral drive mounted when restarting the instance after having stopped it.

I would mark this issue as a feature request just because stopping and starting the head node is not a provided feature.

**Comment by acastanedam** [comment]
Thank very much for the detailed explanation and making of it a
feature request. I think, in general, this will be very useful.

Best
