### ISSUE TITLE
  - AWS::EC2::Instance MasterServer Failed to receive 1 resource signal(s) within the specified duration

### ISSUE THREAD

**Issue by ravinpoudel** [aws/aws-parallelcluster#2105]

**Comment by ravinpoudel** [comment]
I am stuck with the following error:
Beginning cluster creation for cluster: test1
WARNING: EFA was enabled on queue 'compute', but instance type 'c5n.4xlarge' does not support EFA.
Creating stack named: parallelcluster-test1
Status: MasterServerSubstack - CREATE_IN_PROGRESS

Status: MasterServerSubstack - CREATE_IN_PROGRESS
Status: MasterSecurityGroupIngress - DELETE_COMPLETE
Cluster creation failed.  Failed events:
 - AWS::CloudFormation::Stack MasterServerSubstack Embedded stack arn:aws:cloudformation:us-east-2:XXXXXXXXXXXXXXX:stack/parallelcluster-test1-MasterServerSubstack-XXXX/XXXXXXXXXXX was not successfully created: The following resource(s) failed to create: [MasterServer].
   - AWS::CloudFormation::Stack parallelcluster-test1-MasterServerSubstack-XXXXXXX The following resource(s) failed to create: [MasterServer].
   - AWS::EC2::Instance MasterServer Failed to receive 1 resource signal(s) within the specified duration

Following is my config info that I use for creating cluster
#################################################
[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = us-east-2

[vpc myvpc]
vpc_id = vpc-9e1eb1f5
master_subnet_id = subnet-XXXXXXXXXXXXX
compute_subnet_id = subnet-XXXXXXXXXXXXXXXXXXXXXXX
use_public_ips = true

[ebs myebs]
shared_dir = /shared
volume_size = 100


[fsx myfsx]
shared_dir = /fsx
storage_capacity = 7200
deployment_type = SCRATCH_1
import_path = s3://XXXXXXXX/tomount
imported_file_chunk_size = 1024
export_path = s3://XXXXXXXXXXXX/scratch

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = my-key-pair
base_os = alinux2
scheduler = slurm
master_instance_type = c5n.4xlarge
master_root_volume_size = 100
# custom_ami = NONE
vpc_settings = myvpc
ebs_settings = myebs
fsx_settings = myfsx
queue_settings = compute



[queue compute]
compute_type = ondemand
enable_efa = true
placement_group = DYNAMIC
disable_hyperthreading = true
compute_resource_settings = default


[compute_resource default]
instance_type = c5n.4xlarge
min_count = 2
initial_count = 2
max_count = 50

[scaling custom]
scaledown_idletime = 10 # Specifies the amount of time in minutes without a job, after which the compute node terminates.

**Comment by demartinofra** [comment]
Hi @ravinpoudel 

From the reported error it looks like the cluster failed to create because it could not launch the required min_count capacity. in order to confirm this and understand the reason behind this failure I would recommend you to do the following:
1. Launch creation with no rollback flag so that the cluster is not deleted right away on failures (`pcluster create -nr ...`). You can delete it later on with a `pcluster delete`.
2. Look at the produced logs either in the CloudWatch console (you'll find a log group having the cluster name) or directly on the head node by ssh-ing into it with `pcluster ssh` command. Logs to look at are: `/var/log/chef-client.log`, which should confirm where the creation is stuck on, and `/var/log/parallelcluster/clustermgtd`, that contains the reason why capacity cannot be provisioned. If there are logs from compute nodes as well please look at `cloud-init-output` log files in CloudWatch.

Francesco

**Comment by ravinpoudel** [comment]
Hi @demartinofra 
Tried with `pcluster create -nr ...` and got the following - 

Beginning cluster creation for cluster: mycluster
Creating stack named: parallelcluster-mycluster
Stack [parallelcluster-mycluster] already exists
Deleting bucket parallelcluster-xbjch7o6nlnsnbs6

**Comment by ravinpoudel** [comment]
[clustermgtd.txt](https://github.com/aws/aws-parallelcluster/files/5335802/clustermgtd.txt)
[chec-client.log](https://github.com/aws/aws-parallelcluster/files/5335804/chec-client.log)

**Comment by demartinofra** [comment]
From `clustermgtd` log file:

```
An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 32 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.
```

I think you need to request a limit increase in order to launch the configured instances
