### ISSUE TITLE
multi-node parallel calculation error when docker installation command is included in the post_install script

### ISSUE THREAD

**Issue by jaechanglim** [aws/aws-parallelcluster#2147]
When I add docker installation command in post_install.sh, the multi-node parallel is broken.
If I remove the docker install part in post_install.sh, everything works fine
Here I attach the relevant files

post_install.sh: post install script
log_c5.large.tar: /var/log folder of compute node
log_master.tar: /var/log folder of mastner node
test.cpp: cpp file for multi node parallel
job.sh: jobscript for multi node submission
error: error message from slurm scheduler

 - AWS ParallelCluster version [e.g. 2.9.0]: 2.9.1
 - Full cluster configuration without any credentials or personal data
```
[aws]
aws_region_name = ap-northeast-2

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = XXX
scheduler = slurm
base_os = centos7
master_instance_type = t3.small
#compute_instance_type = t3.small
compute_instance_type = c5.large
maintain_initial_size = True
cluster_type = ondemand
initial_queue_size = 2
max_queue_size = 2
scaling_settings = scaling_jaechang
efs_settings = efs_jaechang
vpc_settings = vpc_jaechang
post_install = s3://XXX/post_install2.sh
s3_read_write_resource = arn:aws:s3:::XXX/*
post_install_args = XXX

[vpc vpc_jaechang]
vpc_id = XXX
master_subnet_id = XXX
compute_subnet_id = XXX
use_public_ips = false
additional_sg = XXX

[ebs ebs_jaechang1]
ebs_volume_id = XXX
shared_dir = appl

[ebs ebs_jaechang2]
ebs_volume_id = XXX
shared_dir = workdir

[scaling scaling_jaechang]
scaledown_idletime = 10

[efs efs_jaechang]
shared_dir = workdir_efs
efs_fs_id = XXX
```
 - Cluster name: test3
 - [Optional] Arn of the cluster CloudFormation main stack:
[error.zip](https://github.com/aws/aws-parallelcluster/files/5399759/error.zip)

**Comment by jaechanglim** [comment]
I found that the key problem is not the post install itself, but docker initiation.
When I remove the contents of the post_install and initiate docker (sudo systemctl start docker)by ssh into each compute node
The same error occurs

**Comment by enrico-usai** [comment]
Hi @jaechanglim 

Could you please tell us more about "the multi-node parallel is broken" ?
Do you mean that you are unable to create the cluster or that you're unable to execute jobs on it?

If I have understood correctly the creation of the cluster is failing because the post install script is failing. Can you confirm?
Which is the error you're facing when initiating docker by ssh?

## Network configuration notes

In your configuration file, you're using `use_public_ips = false` but for standard network configuration (e.g. master in public subnet and compute in private subnet) you should set `use_public_ips = true`. See [networking configuration](https://docs.aws.amazon.com/parallelcluster/latest/ug/networking.html#aws-parallelcluster-in-a-single-private-subnet-connected-using-direct-connect).

Are you able to create a cluster with the same network configuration if you remove the post-install script?

**Comment by badaldavda8** [comment]
Hi @enrico-usai Basically, @jaechanglim's cluster is getting created successfully. But when execution of jobs there are 2 scenarios for following script -
#!/bin/bash
#SBATCH --job-name="mpi"
#SBATCH --nodes=2
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=1
#SBATCH --time=100:00:00
#SBATCH -o %x.o%j
#SBATCH -e %x.e%j

cd $SLURM_SUBMIT_DIR
mpirun -np 4 ./a.out

**Scenario 1**
Docker not installed - the job script runs successfully.

**Scenario 2**
Docker installed (be it manually or using postinstall script) - the job is stuck in creating state. 

@jaechanglim Kindly confirm if what I have shared is correct.

**Comment by enrico-usai** [comment]
Thanks @badaldavda8.

@jaechanglim after the docker installation a new network interface is added to your instance:
```
$ ifconfig -a
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:2b:4e:02:53  txqueuelen 0  (Ethernet)
...

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 10.0.2.226  netmask 255.255.255.0  broadcast 10.0.2.255
...

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
...
```
so you should exclude it during the submission, e.g. with `--mca btl_tcp_if_exclude` or `--mca btl_tcp_if_include`, see: https://www.open-mpi.org/faq/?category=tcp

Let us know if it helps.

**Comment by jaechanglim** [comment]
@enrico-usai @badaldavda8 adding --mca btl_tcp_if_exclude docker0 solved my problem.
Thanks so much for your help.

@enrico-usai I guess that "use_public_ips = false" would be better in terms of security.
Can you provide some scenario that "use_public_ips = false" may cause some problem or advantage of "use_public_ips = true"

**Comment by enrico-usai** [comment]
@jaechanglim 
`use_public_ips = false` can cause problems when using the same public subnet (with an internet gateway) for both head node and compute fleet because the compute nodes won't have a public ip so they won't able to reach internet, or it might cause issues if "auto-assign public ip" is set to false in the subnet used for the head node.

When using different subnets for head node and compute fleet (and the compute subnet one has a NAT gateway) the only difference is that the head node will have an Elastic Ip or a simple Public Ip but it doesn't impact compute nodes that won't have public ips anyway.
> If set to true, an Elastic IP address is associated to the head node.
> If set to false, the head node has a public IP (or not) according to the value of the "Auto-assign Public IP" subnet configuration parameter.

Source: [use-public-ips doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/vpc-section.html#use-public-ips).

In any case if your network setup works correctly you can keep it as is. Nat gateway for compute subnet is the suggested approach.

Great to know that `--mca btl_tcp_if_exclud` solved your issue, thanks for sharing.

Please let us know if you need more help or if we can close the issue. Thanks

**Comment by jaechanglim** [comment]
@enrico-usai 
Thank you for the kind reply and explanation. 
I close the issue.
Thanks
