### ISSUE TITLE
Potential issue with ParallelCluster: Some jobs are stuck

### ISSUE THREAD

**Issue by jlim125** [aws/aws-parallelcluster#2159]
**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 2.8.1
 - Full cluster configuration without any credentials or personal data: Attached
[config.txt](https://github.com/aws/aws-parallelcluster/files/5412151/config.txt)

 - Cluster name: pcluster-canu5
 - [Optional] Arn of the cluster CloudFormation main stack: 3f2db640-120c-11eb-b4e5-0e353767367b

**Bug description and how to reproduce:**
We are running a ParallelCluster (parallelcluster-pcluster-canu5) and we have encountered an unusual issue with the ParallelCluster. We created the ParallelCluster 2.8.1 with master+compute instances (now 37 m5n.24xlarge) and we are using slurm. We are running a software Canu (https://canu.readthedocs.io/en/latest/index.html ), specifically cormhap step.

For some jobs, we have experienced: 
- output files stopped growing after certain random size
- but the timestamp of these files kept updating
- not input-data related
- issues happened within instances / nodes that seem to have other productive jobs running concurrently

Strangely, only some jobs are randomly stuck and not moving forward. We haven't seen this when we use our own HPC. Could you take a look into this? Thanks!

**Comment by enrico-usai** [comment]
Hi @jlim125 

Could you please clarify if you're just seeing issues at job level or if you're also seeing compute instances failures?

I'm asking this because from your config I saw you're using spot, so some errors may be caused by some instances reclaimed by spot or by some limits in spot capacity.

You're using [m5n.24xlarge](https://aws.amazon.com/ec2/instance-types/m5/) instances, with 96 vcpus, and the default [spot instance limit](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html) for M* instances is 1440 vcpus, it means you cannot request more than 15 instances but in your configuration file I can see you have an `initial_queue_size` of 35.

I don't know if you already requested an increase for this limit, in any case to be able to debug your issue we need the following logs from the Head node: `/var/log/jobwatcher`, `/var/log/sqswatcher` and `/var/log/slurmctld.log`

If there are compute nodes failures, try to collect from one of the "failing" compute nodes: `/var/log/nodewatcher` and `/var/log/slurmd.log`.

If the failure is at job level and you don't have any compute node failure I'd double check slurm logs to see why the job is stucked. 
We've seen similar issues with Canu in past https://github.com/aws/aws-parallelcluster/issues/1616 and there were problems at `slurmstepd` level.

Let us know if it helps.

**Comment by jlim125** [comment]
Thanks for your help!

We're just seeing issues at job level. Compute instances are running ok.

As you pointed out, we have requested the limit increase so we were able to launch more instances than the default setting. Because each job needs 16 vCPUs, 6 jobs are running on one compute instance.

I attached logs from both the head and compute nodes. 
[debug-logs.tar.gz](https://github.com/aws/aws-parallelcluster/files/5419192/debug-logs.tar.gz)

There are a few compute nodes that partially slow down, but I took logs from one representative node. Please let me know if you need more information.

Thanks,
Jaechul

**Comment by enrico-usai** [comment]
Hi @jlim125 

I'm going to provide some general guidelines when using FSx with large files. I hope they can help to solve your issue.
The sources are the official [FSx performance documentation](https://docs.aws.amazon.com/fsx/latest/LustreGuide/performance.html) and [configuring lustre file striping wiki](https://wiki.lustre.org/Configuring_Lustre_File_Striping).

## FSx layout

> All file data in Lustre is stored on disks called object storage targets (OSTs). All file metadata [...] is stored on disks called metadata targets (MDTs). Amazon FSx for Lustre file systems are composed of a single MDT and multiple OSTs.
> Amazon FSx for Lustre automatically spreads your file data across the OSTs that make up your file system to balance storage capacity with throughput and IOPS load.

## FSx performance optimization and file striping

> Using Lustre, you can configure how files are striped across OSTs. When a file is striped across multiple OSTs, read or write requests to the file are spread across those OSTs, increasing the aggregate throughput or IOPS your applications can drive through it.

> One of the main factors leading to the high performance of Lustre™ file systems is the ability to stripe data over multiple OSTs.

Setting up a striped layout for large files (especially files larger than a gigabyte in size) is important for several reasons:
* Prevents a single large file from filling an OST, possibly causing storage exhaustion on that OST (this could be your case).
* Improves throughput by allowing multiple OSTs and their associated servers to contribute IOPS, network bandwidth and CPU resources. This is especially true for large sequential reads in which Lustre can concurrently request data from multiple OSTs.
* Reduces the likelihood that a small subset of OSTs will become hot spots that limit overall performance.

The FSx layout (stripe count, stripe size) of a file is fixed when the file is first created. 
I'd suggest you to review [the layout of your FSx](https://docs.aws.amazon.com/fsx/latest/LustreGuide/performance.html#storage-layout), the [strip configuration](https://docs.aws.amazon.com/fsx/latest/LustreGuide/performance.html#striping-data) and I'd suggest to configure FSx carefully after reading the two provided docs.

Note: it's possible to change the layout of a file after it is created, as suggested [here](https://wiki.lustre.org/Configuring_Lustre_File_Striping).

## FSx file striping and ParallelCluster

When using FSx with ParallelCluster it's possible to configure the stripe count and the maximum amount of data per file by setting the [`imported_file_chunk_size`](https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html#fsx-imported-file-chunk-size) configuration parameter in the [`fsx`](https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html) section.

Let us know if it helps.
