### ISSUE TITLE
Adding SLURMD on master node || How To

### ISSUE THREAD

**Issue by atulyadavtech** [aws/aws-parallelcluster#2255]
Hi Team,

How we can add SLURMD in master/login node.
Requirement: Running SLURMD service on the master node.
Objective:  Including master node also in compute power pool.

Thank You
Atul Yadav
Locuz

**Comment by ddeidda** [comment]
@atulyadavtech 

Currently there is no officially supported way to include the head node in the compute fleet. The configuration of head and compute nodes follows two completely, mutually exclusive paths in the current setup of clusters managed by ParallelCluster; basically a ParallelCluster node can only be bootstrapped as "head" or "compute", not both. 

The configuration you want to achieve could likely be obtained by leveraging with the slurm configuration files in the head node, but there could be a bunch of caveats since this unexpected configuration could interfere with the behaviour of parallelCluster daemons.

The only suggestion I can think of, if it comes to saving costs, would be to choose the least expensive instance type for the head node, compatibly with the workload expected to have on it. .
