### ISSUE TITLE
Use of Autoscaling groups

### ISSUE THREAD

**Issue by tdudgeon** [aws/aws-parallelcluster#2258]
**Required Info:**
 - AWS ParallelCluster version: 2.91

This is a question about the documentation.
This clearly states that the worker instances are managed through an autoscaling group. See for instance: https://docs.aws.amazon.com/parallelcluster/latest/ug/autoscaling.html

However when looking a the EC2 console there are no Autoscaling groups present even though worker instances are being created and removed as expected.
Is the documentation inaccurate?
I ask primarily because I had problems with spot instances not being created and thought the obvious first place to look was the autoscaling group, but it didn't exist.

**Comment by ddeidda** [comment]
@tdudgeon 

Thanks for calling this out.
AutoScaling groups are no longer used in clusters with the Slurm scheduler starting from version 2.9.0, as reported in the [Changelog](https://github.com/aws/aws-parallelcluster/releases/tag/v2.9.0). They are instead still used with other schedulers like SGE or Torque.

So, if you are using Slurm as scheduler, this is the reason why you do not see new Autoscaling groups in your EC2 console. I am marking this as a bug in our docs to be fixed.

Other than that, are you still having issues with spot instances?

**Comment by tdudgeon** [comment]
@ddeidda Yes, we are using Slurm, so that makes sense.
And, yes, we do see some sporadic issues with spot instances not being created, but can't make this reproducible.
If these aren't being handled by a ASG then where do I look for problems?

**Comment by ddeidda** [comment]
ParallelCluster logs useful information locally in master and head nodes and, if not disabled by configuration, also in CloudWatch Logs. Here is the [list of all the logs](https://docs.aws.amazon.com/parallelcluster/latest/ug/cloudwatch-logs.html) currently collected.

In your case (Slurm cluster), the most relevant logs to start investigating on your issues should be the following ones from the head node:

- /var/log/parallelcluster/clustermgtd (clustermgtd)
- /var/log/parallelcluster/slurm_resume.log (slurm_resume)
- /var/log/parallelcluster/slurm_suspend.log (slurm_suspend)

Please let us know if you can get the information you are looking for from there; otherwise we will try looking deeper at the issue.

PS: you can retrieve information about your spot instance requests by mean of this aws cli call: 
`aws ec2 describe-spot-instance-requests`

**Comment by tdudgeon** [comment]
Thanks. I'll create a separate topic if I continue to hit problems with spots.

**Comment by stefan-maxar** [comment]
@ddeidda a quick follow-up on this thread since I was about to ask about this as well in a new ticket. we use Slurm as our scheduler as well and allocate a lot of instances at once that must be in the same placement group. Prior to 2.9.X, when allocating a large number of instances in the same placement group (say 150+ c5n.18x), if there was insufficient capacity, the Autoscaling Group would keep trying to get the remaining instances. In 2.9.X and newer, what happens if there is insufficient capacity? Is Parallel Cluster behind the scenes re-trying to get the instances? Or? One of the nice features of the ASG being present was the fact that it would keep trying to get instances if ICE'd. Thanks!

**Comment by enrico-usai** [comment]
Hi @stefan-maxar 

we preserved the same behavior, with the downside of keeping partial capacity that might not be enough to run the job.
Then, we added this possibility: https://github.com/aws/aws-parallelcluster/wiki/Configuring-all_or_nothing_batch-launches

Let us know if it helps.

**Comment by enrico-usai** [comment]
@tdudgeon I just want to mention that you can see sporadic issues with spot if using an `inital_count` > 0.

> Cluster creation doesn't complete until at least this many nodes have been launched into the compute resource. If the compute_type setting for the queue is spot and there aren't enough Spot Instances available, the cluster creation might time out and fail.

Source: https://docs.aws.amazon.com/parallelcluster/latest/ug/compute-resource-section.html#compute-resource-initial-count

**Comment by stefan-maxar** [comment]
> Hi @stefan-maxar
> 
> we preserved the same behavior, with the downside of keeping partial capacity that might not be enough to run the job.
> Then, we added this possibility: https://github.com/aws/aws-parallelcluster/wiki/Configuring-all_or_nothing_batch-launches
> 
> Let us know if it helps.

Hey @enrico-usai - yes, this helps a lot, thanks! We've tested spinning up clusters with large capacity and the internal retry in the latest PCluster versions for provisioning additional instances seems to work as well as, if not better, than what the ASG does. There were some AWS-related API limitations (and resulting throttling) that would occur when the ASG was trying for too many instances and/or too long. 

One thing we are trying to figure out now is alerting to when insufficient capacity occurs. Our current workflow uses a CloudWatch event rule to trigger SNS notifications for when the ASG cant launch an instance (e.g., "EC2 Instance Launch Unsuccessful" error from the ASG). What would be the proper replacement without the ASG for the 2.9.X and 2.10.0? We were thinking of creating a CW log stream for /var/log/parallelcluster/clustermgtd on the master node and creating metrics filters and alarms off that, but we are unsure if/how we can isolate insufficient capacity from that log or if there is some other method you'd recommend.
