### ISSUE TITLE
initial_count leads to timeout on cluster creation

### ISSUE THREAD

**Issue by bollig** [aws/aws-parallelcluster#2289]
- AWS ParallelCluster version [e.g. 2.9.0]: 2.10.0

[Undocumented condition](https://docs.aws.amazon.com/parallelcluster/latest/ug/compute-resource-section.html#compute-resource-initial-count) that leads to "The following resource(s) failed to create: [MasterServer]." timeout error.  Config has 2 queues (ordered as spot, ondemand), each with unique compute resources. initial_count = 2 for compute_resources in the ondemand queue, and nothing specified for spot queue. Resolved issue by re-ordering queues with ondemand first or dropping initial_count for secondary queue (ondemand).

**Comment by enrico-usai** [comment]
Hi Evan,

I tried to replicate the issue with the following configuration with no luck:

```
[cluster ...]
...
queue_settings = spot,ondemand

[queue spot]
compute_type = spot
compute_resource_settings = spot
enable_efa = false

[compute_resource spot]
instance_type = t2.xlarge

[queue ondemand]
compute_resource_settings = ondemand
enable_efa = false

[compute_resource ondemand]
instance_type = t2.large
initial_count=2
min_count=2
```

Could you please provide us the complete configuration file you're using?

Thanks

**Comment by ddeidda** [comment]
@bollig 

there are several reasons that could lead to the issue you reported.
Most likely what solved your issue was the dropping of the `initial_count` parameter rather than the re-ordering of queues, since you allowed the cluster to be created without initial capacity.

Anyway, were you able to submit jobs to the on_demand queue after cluster creation? If you are still experiencing issues please feel free to share your configuration file and logs under the `/etc/var/log/parallelcluster` directory.
