### ISSUE TITLE
Support more than 5 queues in a cluster

### ISSUE THREAD

**Issue by jmcgeepresettech** [aws/aws-parallelcluster#2343]
I know that this may seem like a strange request, and don't get me wrong - it's great that we can now have multiple queues (we worked around this previously by building different versions and sourcing .rc files) - but is there a reason we have a limit of 5 queues?

Is this a hard limit or just an arbitrary number that was picked? 

I'm about to go digging through and seeing how easy that would be to change, but I'd like some thoughts around this as well.

**Comment by tilne** [comment]
Hi @jmcgeepresettech,

Unfortunately I wasn't able to come up with a definitive answer as to how we settled on the limit of five queues. The team members who made that decision are currently on vacation. I'll be sure to bring it up with them when they return. In the meantime I'm marking this as a feature request.

**Comment by demartinofra** [comment]
Hi @jmcgeepresettech 

sorry for the late reply. The main reason why this limit was set is to control the max number of resources that are created in the cluster and configured in the scheduler so that we can make sure there is no degradation in performance and the cluster management daemons can complete all required actions within an acceptable timeframe.

If you want to experiment with using > 5 queues, you can try to disable sanity_check by specifying sanity_check = false in your configuration file. After disabling sanity_check, you should be able to create a cluster with > 5 queues.

Of course, this is not an officially supported path, so you might encounter some issues.
It would be great if you could inform us of the limitations and issues you see when working with 5 queues, so we can take those into account when evaluating an increase to such limits.

**Comment by jmcgeepresettech** [comment]
That's a great trick, I didn't know that sanity_check = false was an option. 

We actually forked the repository and expanded it ourselves, but that'll save us from merging changes from public master on the next major release.

For us, we have a large number of different requirements combining spot instances, on-demand instances - of varying types - so we also expanded on the instance types per queue, too (will sanity_check = false stop that check too?).

It's kind of complicated, and it's basically NDA as to why I can't elaborate further, but we definitely needed more than 5.

**Comment by oplatek** [comment]
> Thanks for the feedback. One last question: what would be a reasonable number for queues and compute resources that satisfies your use case?

Hi @demartinofra,

I hijacked your question to @jmcgeepresettech and I would like to give our reasoning which sounds similar and I can disclose it.

We need to support two types of GPU instances for spot instances (G and P family) so we eliminate the low capacity of GPUs in a region/zone. We support the same kind of instances with an on-demand version so if we cannot get the spot instances we switch back to the on-demand version.

We would love to use `placement=cluster` and `placement_group=Dynamic` for each queue and since the placement group should contain only a single type of instance we need **four queues so far** in order to minimize `InsufficientInstanceCapacity` for on-demand instances and especially for spot instances. (Assuming that the placement_group and placement=cluster setting help also with InsufficientIn Spot Capacity).

However, for each type, we need three different sizes so ideally, we would **need 12 GPU queues** plus one queue for CPU jobs.

**Comment by enrico-usai** [comment]
@hy714335634 for multi-AZ feature we have the https://github.com/aws/aws-parallelcluster/issues/3114

@oplatek we don't recommend to use `placement=cluster` when facing `InsufficientInstanceCapacity` because with this setting the head node (that is a probably a different instance type) must be in the same placement group of the compute nodes and it's easier to find capacity issues.

As part of 3.0.0 we removed the possibility to have the entire cluster in the same placement group, leaving the feature to use a placement group for each queue.

It is not strictly required to have a single instance type for each queue/placement group but it is true that if the same placement group is used for different instance types, it’s more likely that the request might fail due to an insufficient capacity error.

As part of [3.0.0 release](https://github.com/aws/aws-parallelcluster/releases/tag/v3.0.0) we extended the limits for supported number of Slurm queues to 10 and compute resources to 5, this should help for your use cases.

I'm going to close this issue. Thanks for your feedbacks!
