### ISSUE TITLE
Mounting New EBS Volume on an Existing Cluster

### ISSUE THREAD

**Issue by zadelman** [aws/aws-parallelcluster#2345]
AWS ParallelCluster version 2.9.1
 
How does one add/mount a new EBS volume to work with an already-running parallel cluster? I'm able to successfully mount a new volume on the master node, but the compute nodes can't see this new volume. 

I searched through your documentation and on this forum but I didn't find anything.  Any advice is much appreciated.

**Comment by tilne** [comment]
Hey @zadelman 

My initial recommendation would be exporting the mount point of the newly attached volume on the head node to the computes, and then mounting this NFS drive on your compute nodes via a post-install script.

**Comment by tilne** [comment]
Hey @zadelman 

My initial recommendation would be exporting the mount point of the newly attached volume on the head node to the computes, and then mounting this NFS drive on your compute nodes via a post-install script.

In order to export the mount point from the head node to the comptues, you can add an entry to the /etc/exports file and then run a command to export the newly added entry. To give a concrete example, if the mount point on the head node is /new_ebs, then I would add an entry to /etc/exports that looks like this:

```
/new_ebs ${IPV4_CIDR_BLOCK}${EXPORT_OPTIONS}
```

To see what values to use for the IPV4_CIDR_BLOCK and EXPORT_OPTIONS variables, check the existing entries in /etc/exports on the head node. For example, the cluster I'm testing this on has the following entry:

```
/opt/slurm 172.31.0.0/16(rw,sync,no_root_squash)
```

After the entry is created, run `sudo exportfs -o /new_ebs` on the head node.

Then to mount the NFS drive on the compute nodes as they are added to the cluster, you can use a [post_install script](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#post-install) that ensures the mount point on the compute exists, and then mounts it:
```bash
mkdir -p /new_ebs_on_compute
sudo mount ${HEAD_NODE_PRIVATE_IP}:/new_ebs /new_ebs_on_compute
```
where HEAD_NODE_PRIVATE_IP is the value of the head node's private IPv4 address. This can be most easily obtained by viewing the outputs of your cluster's CloudFormation stack via the AWS console or by running the following command:
```
aws cloudformation describe-stacks --stack-name parallelcluster-${CLUSTER_NAME} --region ${CLUSTER_REGION} --query "Stacks[0].Outputs[?OutputKey=='MasterPrivateIP'].OutputValue" --output text
```

Note: it's highly discouraged to run the command as part of the post-install script, because that can lead to API throttling when attempting to scale a cluster very quickly. In order to configure your running cluster to use this post-install script you'll need to stop the cluster, update it (using the updated config file), and then restart it.
