### ISSUE TITLE
 AWS ParallelCluster in private VPC connected using Direct Connect and http_proxy

### ISSUE THREAD

**Issue by andrei-xdlab** [aws/aws-parallelcluster#2396]
Environment:

AWS ParallelCluster 2.10.1
OS: ubuntu 1804
Scheduler: Slurm
Master instance type: m5.xlarge
Compute instance type: m5.xlarge

Question
We are trying to deploy a parallel cluster environment  in the private VPC using proxy_server and use_public_ips = false
Can I create multiple parallel clusters with a private subnet connected using Direct Connect gateway? If so, are there any modifications I need to do to the settings described in the [guide](https://aws-parallelcluster.readthedocs.io/en/latest/networking.html#aws-parallelcluster-in-a-single-private-subnet-connected-using-direct-connect)?

proxy_server = http://<IP>:10080
use_public_ips = false
custom_AMI for corporate DNS 

The corporate proxy has whitelist outbound access and we need list of URL that will be requested by parallel cluster

resources like below but we need a full list to allow outbound access in the proxy

pypi.python.org
bootstrap.pypa.io
supermarket.chef.io
mirrorlist.centos.org

Thanks
Andrei

**Comment by lukeseawalker** [comment]
Hi @andrei-xdlab,
you can create multiple clusters in the same subnet. There shouldn't be other settings other than the one reported in the [doc](https://aws-parallelcluster.readthedocs.io/en/latest/networking.html#aws-parallelcluster-in-a-single-private-subnet-connected-using-direct-connect).

For the outbound list, we don't have a complete list on hand.
First thing is that I suggest you to use a custom AMI with the ParallelCluster software stack already installed on it. Following the [doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html), you can either:
* modify an official AWS ParallelCluster AMI
* build a custom AWS ParallelCluster AMI

At this point, since all the software is already installed in the AMI, the instances will not need to access endpoints like `python.org` or `pypa.io`
The only remaining endpoints will be

```
cloudformation.<region>.amazonaws.com
dynamodb.<region>.amazonaws.com
ec2.<region>.amazonaws.com
fsx.<region>.amazonaws.com
s3.<region>.amazonaws.com
logs.<region>.amazonaws.com
route53.amazonaws.com
```

and eventually the ubuntu repositories.

**Comment by andrei-xdlab** [comment]
Hi @lukeseawalker 

I attaching a complete cluster log archive with the ticket. pcluster create fails with the following error

2021-01-28 10:17:47,761 [DEBUG] Signaling resource MasterServer in stack parallelcluster-tcrdl-ami-202101281902-MasterServerSubstack-BC0SHB740JIX with unique ID i-0e8ba207d551c0b7a and status FAILURE


[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/5891345/cloud-init.log)
[chef-client.log](https://github.com/aws/aws-parallelcluster/files/5891346/chef-client.log)
[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/5891347/cloud-init-output.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/5891348/cfn-init.log)

**Comment by lukeseawalker** [comment]
Hi @andrei-xdlab,
I see
```
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "https://ec2.ap-northeast-1.amazonaws.com/"
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPSConnection object at 0x7f803f029208>, 'Connection to proxy.tytlabs.co.jp timed out. (connect timeout=60)')
```
have you allowed `ec2.ap-northeast-1.amazonaws.com`?
