### ISSUE TITLE
Question: Creating clusters in different accounts using pcluster from Lambda

### ISSUE THREAD

**Issue by cailinw** [aws/aws-parallelcluster#2408]
What is the suggested way to create a cluster in a different account from a Lambda function?

We currently have a Lambda function (as suggested by this [blog post](https://aws.amazon.com/blogs/compute/using-aws-parallelcluster-with-a-serverless-api/)) that can be called to create/delete clusters in account A. We want to be able to provision the resources for the creation of the parallelcluster in a different account (e.g., account B), determined by parameters passed to the Lambda function (in account A). We were thinking of creating a cross-account IAM role in account B that gives permission to account A to create a pcluster in account B. We also know that we can use sts to assume a role in the Lambda function. However, we are not sure what is the recommended way to specify that the pcluster gets created in account B.

Thank you.

**Comment by lukeseawalker** [comment]
Hi @cailinw,
the approach you described is reasonable.
In account B you have to create a role with the ParallelClusterUserPolicy (see https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html) that will allow to manage the cluster (creation, deletion, etc.). This role should be configured with a "trust relationship" so that the account A can assume it.
The lambda called from the account A will assume that role so that it's able to impersonate the account B.

**Comment by cailinw** [comment]
@lukeseawalker Thank you so much for the response. That should work for us.
