### ISSUE TITLE
Only one compute_instance_type per cluster supported?

### ISSUE THREAD

**Issue by elgalu** [aws/aws-parallelcluster#2439]
What is the recommended way of providing more than 1 compute_instance_type? separate clusters? (slurm use case)

**Comment by yuleiwan** [comment]
Hi @elgalu,

Since pcluster v2.9.0, pcluster supports [multiple queue mode](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorial-mqm.html). You are able to set different compute instance types in one queue and you also can define multiple queues in one cluster. There is a [Slurm guide for multiple queue mode](https://docs.aws.amazon.com/parallelcluster/latest/ug/multiple-queue-mode-slurm-user-guide.html) to get more information about slurm scheduler.
