### ISSUE TITLE
Parallel Cluster 2.10.1 scaling up for short jobs

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2454]
Hi!

I described an unwanted behaviour of scaling in the [HPC forum](https://forums.aws.amazon.com/thread.jspa?threadID=335794) (1).
My questions are:
- should I ask such questions to the HPC forums or ask them here?
- Should I describe the behavior here again?
- How to avoid this behavior?
- How to debug/confirm my hypothesis? Where can I see the logs and configurations which trigger scaling up and scaling down/cancelation of scaling up?

Thank you!

Ondra

[1] https://forums.aws.amazon.com/thread.jspa?threadID=335794

**Comment by hanwen-pcluste** [comment]
Hello Ondra,

Both Github issues and HPC forums are viable channels to reach us. We prefer Github for wider visibilities to help others with the same issues or find help from them, and it's easy for us to mark an issue as a bug or feature request. It would be great if you can describe the issue here again.

To always run the 5th job on node <strong>B</strong>, you could create the cluster with multiple queues and run the 5th job in a different queue.
Here is a tutorial for [multiple queue](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorial-mqm.html)

To do further investigation, could you follow [this guide](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs) and attach the complete cluster log archive?

Could you also provide the parallelcluster configuration file (without sensitive information) you used when creating the cluster?

Usually for scaling issues with AWS ParallelCluster >= v2.9.0 and scheduler == slurm, we would look into the following logs:
* From Head node: `/var/log/parallelcluster/clustermgtd.log`, `/var/log/parallelcluster/slurm_resume.log`, `/var/log/parallelcluster/slurm_suspend.log`, and `/var/log/slurmctld.log`
* From Compute node:  `/var/log/parallelcluster/computemgtd.log`, and `/var/log/slurmd.log`

Thank you,

Hanwen

**Comment by hanwen-pcluste** [comment]
Hello Ondra,

After looking into `pcluster` 2.10.1, jobs wouldn’t be in `PD` state unless the whole capacity of the cluster is occupied, i.e., all nodes are busy running jobs. Otherwise, the jobs would be assigned to a node and not be reassigned.
Therefore, could you double check the version of  `pcluster` you were using to create the cluster? 

Thank you,

Hanwen

**Comment by oplatek** [comment]
@hanwen-pcluste I am sure I am using the version of parallel cluster `2.10.1`. The jobs are in PD state in just a really short time.

I will post the configurations and logs here in a minute - sorry for the delay.

**Comment by oplatek** [comment]
Hi,

sorry for the delay. I will try to describe the problem by providing two scripts and logs replicating the behavior.

Note that the unwanted behavior was a result of inconvenient usage of SLURM commands and when scaling mechanisms is available (in a parallel cluster) then a bug.

The problematic behavior can be generated by the following script. 
If started on an empty cluster, just starting it on an empty cluster, it is enough to scale up to at least 2 more nodes then intended. 
If you set the `stage_secs` to 1 you are able to scale the cluster to all jobs requested in all the stages ie with the setup below to 22 nodes. ("2+3+3+3+3+4+4=22" )

```
#!/bin/bash
set -euo pipefail

stages_numjobs="2 3 3 3 3 4 4"   # number of parallel job at each stage
stage_secs=20

rm -f slurm-*.out

cat > run.sh << EOF
#!/bin/bash
sleep $stage_secs
EOF

for nj in $stages_numjobs ; do
  printf "\n$(date) Submitting start for stage with nj: $nj\n\n"
  out=$(sbatch --array=1-$nj run.sh)
  jobid=$(echo $out | sed "s/Submitted batch job //")

  printf "\n$(date) Submitting finished for stage with nj: $nj\n\n"
  printf "\nsinfo:\n"
  sinfo
  printf "\nsqueue:\n"
  squeue
  sleep 1
  printf "\nsqueue:\n"
  squeue
  printf "\nsinfo:\n"
  sinfo
  printf "\n$(date) sleeping $stage_secs  - the same time the jobs are sleeping\n\n"
  sleep $stage_secs
  printf "\n$(date) Sleeping is over  - the jobs should have finished by now if started at the beginning of the stage\n\n"
  printf "\nsinfo:\n"
  sinfo
  printf "\nsqueue:\n"
  squeue
  printf "\n$(date) Stage should with nj: $nj should be finished\n\n"
done
```

**Comment by oplatek** [comment]
The fix is simple, wait till the end of the job array to avoid the effect of cumulating unhandled jobs with current number of nodes!

```
#!/bin/bash
set -euo pipefail
# set -x
# See tutorial on waiting for slurm jobs on each other https://hpc.nih.gov/docs/job_dependencies.html


stages_numjobs="2 3 3 3 3 4 4"   # number of parallel job at each stage
stage_secs=20

rm -f slurm-*.out

cat > run.sh << EOF
#!/bin/bash
sleep $stage_secs
EOF

printf "\nsinfo:\n"
sinfo
printf "\nsqueue:\n"
squeue

for nj in $stages_numjobs ; do
  printf "\n$(date) Submitting start for stage with nj: $nj\n\n"
  out=$(sbatch --wait --array=1-$nj run.sh)
  jobid=$(echo $out | sed "s/Submitted batch job //")

  printf "\n$(date) Submitting finished for stage with nj: $nj\n\n"
  printf "\nsinfo:\n"
  sinfo
  printf "\nsqueue:\n"
  squeue
  sleep 1
  printf "\nsqueue:\n"
  squeue
  printf "\nsinfo:\n"
  sinfo
  printf "\n$(date) NOT sleeping $stage_secs  - the same time the jobs are sleeping\n\n"
  # sleep $stage_secs
  # printf "\n$(date) Sleeping is over  - the jobs should have finished by now if started at the beginning of the stage\n\n"
  printf "\nsinfo:\n"
  sinfo
  printf "\nsqueue:\n"
  squeue
  printf "\n$(date) Stage should with nj: $nj should be finished\n\n"
done
```

**Comment by oplatek** [comment]
The questions is:

Can the SLURM and parallel cluster be configured that the jobs will be scheduled on nodes which are either:
1. available when the jobs are submitted
2. or are added (woke up/ started up) because of the jobs?

**Comment by rexcsn** [comment]
Hi @oplatek,

Thanks for providing the job details. I must confess I can't see the exact behavior you are talking about just by looking at the job submission scripts.
I think cluster configuration and the outputs from your submission script to show the state of the cluster/queue would help.

However, I think I am understanding the point you are trying to make, so I will attempt to reproduce the behaviors and explain what is happening

I am using cluster with no nodes power_up to begin with. It's not clear what types of compute your were using with the job scripts you provided, so I am running with `c5.xlarge` computes, which have 4 vcpus as mentioned in your original post in the AWS forum.
I tried to run the script that you provided on my cluster and here are the outputs:

Running 1st job script with `stage_sec = 20` I get this output at the end:
```
squeue:
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON) 
              11_1        q1   run.sh   ubuntu CF       1:23      1 q1-dy-c5xlarge-3 
              11_2        q1   run.sh   ubuntu CF       1:23      1 q1-dy-c5xlarge-3 
              11_3        q1   run.sh   ubuntu CF       1:23      1 q1-dy-c5xlarge-3 
              14_1        q1   run.sh   ubuntu CF       1:02      1 q1-dy-c5xlarge-3 
              14_2        q1   run.sh   ubuntu CF       1:02      1 q1-dy-c5xlarge-4 
              14_3        q1   run.sh   ubuntu CF       1:02      1 q1-dy-c5xlarge-4 
              17_1        q1   run.sh   ubuntu CF       0:41      1 q1-dy-c5xlarge-4 
              17_2        q1   run.sh   ubuntu CF       0:41      1 q1-dy-c5xlarge-4 
              17_3        q1   run.sh   ubuntu CF       0:41      1 q1-dy-c5xlarge-5 
              17_4        q1   run.sh   ubuntu CF       0:41      1 q1-dy-c5xlarge-5 
              21_1        q1   run.sh   ubuntu CF       0:20      1 q1-dy-c5xlarge-5 
              21_2        q1   run.sh   ubuntu CF       0:20      1 q1-dy-c5xlarge-5 
              21_3        q1   run.sh   ubuntu CF       0:20      1 q1-dy-c5xlarge-6 
              21_4        q1   run.sh   ubuntu CF       0:20      1 q1-dy-c5xlarge-6 
               3_1        q1   run.sh   ubuntu  R       0:17      1 q1-dy-c5xlarge-1 
               3_2        q1   run.sh   ubuntu  R       0:17      1 q1-dy-c5xlarge-1 
               5_3        q1   run.sh   ubuntu  R       0:17      1 q1-dy-c5xlarge-2 
               5_1        q1   run.sh   ubuntu  R       2:05      1 q1-dy-c5xlarge-1 
               5_2        q1   run.sh   ubuntu  R       2:05      1 q1-dy-c5xlarge-1 
               8_1        q1   run.sh   ubuntu  R       1:44      1 q1-dy-c5xlarge-2 
               8_2        q1   run.sh   ubuntu  R       1:44      1 q1-dy-c5xlarge-2 
               8_3        q1   run.sh   ubuntu  R       1:44      1 q1-dy-c5xlarge-2 

Wed Mar  3 20:18:32 UTC 2021 Stage should with nj: 4 should be finished
```
Running 1st job script with `stage_sec = 1` I get this output at the end:
```
squeue:
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON) 
              25_1        q1   run.sh   ubuntu CF       0:13      1 q1-dy-c5xlarge-1 
              25_2        q1   run.sh   ubuntu CF       0:13      1 q1-dy-c5xlarge-1 
              27_1        q1   run.sh   ubuntu CF       0:11      1 q1-dy-c5xlarge-1 
              27_2        q1   run.sh   ubuntu CF       0:11      1 q1-dy-c5xlarge-1 
              27_3        q1   run.sh   ubuntu CF       0:11      1 q1-dy-c5xlarge-2 
              30_1        q1   run.sh   ubuntu CF       0:07      1 q1-dy-c5xlarge-2 
              30_2        q1   run.sh   ubuntu CF       0:07      1 q1-dy-c5xlarge-2 
              30_3        q1   run.sh   ubuntu CF       0:07      1 q1-dy-c5xlarge-2 
              31_1        q1   run.sh   ubuntu CF       0:07      1 q1-dy-c5xlarge-3 
              31_2        q1   run.sh   ubuntu CF       0:07      1 q1-dy-c5xlarge-3 
              31_3        q1   run.sh   ubuntu CF       0:07      1 q1-dy-c5xlarge-3 
              36_1        q1   run.sh   ubuntu CF       0:04      1 q1-dy-c5xlarge-3 
              36_2        q1   run.sh   ubuntu CF       0:04      1 q1-dy-c5xlarge-4 
              36_3        q1   run.sh   ubuntu CF       0:04      1 q1-dy-c5xlarge-4 
              39_1        q1   run.sh   ubuntu CF       0:01      1 q1-dy-c5xlarge-4 
              39_2        q1   run.sh   ubuntu CF       0:01      1 q1-dy-c5xlarge-4 
              39_3        q1   run.sh   ubuntu CF       0:01      1 q1-dy-c5xlarge-5 
              39_4        q1   run.sh   ubuntu CF       0:01      1 q1-dy-c5xlarge-5 
              40_1        q1   run.sh   ubuntu CF       0:01      1 q1-dy-c5xlarge-5 
              40_2        q1   run.sh   ubuntu CF       0:01      1 q1-dy-c5xlarge-5 
              40_3        q1   run.sh   ubuntu CF       0:01      1 q1-dy-c5xlarge-6 
              40_4        q1   run.sh   ubuntu CF       0:01      1 q1-dy-c5xlarge-6 

Wed Mar  3 23:08:56 UTC 2021 Stage should with nj: 4 should be finished
```
These 2 cases have the same end behavior: at the end, we scaled up to 6 nodes total, and all 6 nodes were used to run 22 jobs.
We scaled up to 6 nodes because no node were available at first, and slurm tries to assign a job to a node in the system as soon as it receives the job.
As we can see, nodes get assigned some jobs, but nodes cannot run the jobs right away, because nodes need time to power_up, and jobs that are waiting for node to power up are in configuring state(`CF`), and not in running state(`R`).
Once a job is assigned to a node(when you see `NODELIST` associated with job), the job is tied with the node, and cannot be reassigned to another node, even if another node is available. As a result, we had to scale up to 6 nodes total to process the 22 jobs right away.

**Note that sleeping for `sleep $stage_secs` does not guarantee the set of jobs will finish, because it takes time to power up nodes, and slurm might take more time to run a particular job.** 
For example, in the example above you will see `5_1        q1   run.sh   ubuntu  R       2:05      1 q1-dy-c5xlarge-1 `, which means that job `5_1` has been running for more than 2 mins since it was submitted, even though the actual job is just `sleep 20`, because the time it takes to power_up the node is included in job time.

For your 2nd job script we would scale up to a maximum of 4 nodes, because we are waiting for each job script to finish, with the `--wait` option, before submitting the next array job.
Therefore, all cores on nodes that were power_up and available for a previous job can be used for the next job because the nodes already finished the previous job.

Overall I would say that this is the expected behavior from pcluster, and I would encourage you to check out our [slurm user guide](https://docs.aws.amazon.com/parallelcluster/latest/ug/multiple-queue-mode-slurm-user-guide.html) for more details on how the scaling process works.

Now, to answer you questions:
> Can the SLURM and parallel cluster be configured that the jobs will be scheduled on nodes which are either:
available when the jobs are submitted
or are added (woke up/ started up) because of the jobs?

This is the expected behavior today. Slurm always prefers to schedule jobs on nodes that are already `POWER_UP` and available. Slurm would only allocate the job to a node in `POWER_SAVING` if all available nodes are already used by some current jobs.

Hope that helps, please let us know if you have any question. Thanks!

**Comment by oplatek** [comment]
@rexcsn thank you for spending time on this.

> Note that sleeping for sleep $stage_secs does not guarantee the set of jobs will finish, because it takes time to power up nodes, and slurm might take more time to run a particular job.

Exactly, I was just asking that if this is expected behavior.

Feel free to close this issue!
