### ISSUE TITLE
Does pcluster update run the post_install script on the head node?

### ISSUE THREAD

**Issue by cailinw** [aws/aws-parallelcluster#2558]
I'm not able to get the post-install script to run on the head node when updating a cluster. I created a pcluster, specifying a post_install script (path to s3). The script ran correctly on `pcluster create`. However, if I update this script file (including renaming the file, reuploading to s3, and updating the config file) and run `pcluster update`, the changes aren't reflected on the head node. How do I update a cluster with a new post-install script?

Below is the configuration file that I used.

[aws]
aws_region_name = us-west-2

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
key_name = ---
base_os = alinux2
scheduler = slurm
vpc_settings = default
queue_settings = compute
master_instance_type = t3.xlarge
additional_iam_policies = arn:aws:iam::---:policy/--, arn:aws:iam::---:policy/---
post_install = s3://cluster-scripts/script.sh
s3_read_resource = arn:aws:s3:::---
s3_read_write_resource = arn:aws:s3:::cluster-scripts*

[vpc default]
vpc_id = ---
master_subnet_id = ---

[queue compute]
enable_efa = false
compute_resource_settings = default

[compute_resource default]
instance_type = t3.large
max_count = 1

Thank you!

**Comment by calebwin** [comment]
To further qualify this question, will the post_install script be run regardless even if everything else in the configuration file stayed the same? And does the post_install script's filename need to be different for it to be re-run or is the time last changed checked by pcluster update?

**Comment by yuleiwan** [comment]
Hi @calebwin,

post install script only affects new launched nodes. The existing nodes like head node, which have already run the post-install script during the bootstrapping process, won't run the updated post install script during cluster update.

To answer your question, post_install script will be run regardless even if everything else in the configuration file stayed the same, but only on new launched nodes.

**Comment by calebwin** [comment]
Thanks for your response @yuleiwan. Sounds like we may have to do a `pcluster stop` before `pcluster update`. If we invoked `pcluster stop` and `pcluster update` both with `--no-wait` and in sequence, would that have the effect of spinning down all compute nodes and then preparing all nodes with the post-install script that will be run before later jobs submitted with Slurm are run? And are pcluster commands called with --no-wait still serialized?

**Comment by yuleiwan** [comment]
`pcluster stop` command doesn't have `--no-wait` option, `--no-wait` option only affects the stack events status display, but won't affect the command functionality, which means no matter you specify `--no-wait` or not, the cluster operation will be executed. 
And `--no-wait` option is defined in a specific command, only affects that command. for example, if you use `--no-wait` in `pcluster create` command, and you don't use `--no-wait` in `pcluster update` command. In this case, you only skip the stack event status display during pcluster creation, you will see the stack event status during pcluster update.

**Comment by calebwin** [comment]
I see. I'm trying to call `pcluster update` from behind an API Gateway in a Lambda function. So my execution time is limited (few seconds of execution would be ideal). And it seems like I may need to call `pcluster stop` first to ensure that the `pcluster update` succeeds. Given my requirements, do you think I could expect `pcluster stop` to take a small enough amount of time so that I can call it first and then call `pcluster update` with `--no-wait` afterwards? or would I need another approach?

Thank you again for your help.

**Comment by yuleiwan** [comment]
`pcluster stop` may take a few seconds, normally around 30 seconds and less than 1 minutes, because this command will stop the compute fleet. I am not sure if it is qualified for your Lambda function. If so, you can run `pcluster stop` and then run `pcluster update --no-wait`

**Comment by calebwin** [comment]
@yuleiwan Just to follow-up on this - in order to run a command on all existing nodes in the compute fleet, what is the easiest way to do this?

We are trying to use SSM and can successfully run commands on the master node (to download files, install stuff, run scripts, etc.). Is there a way to use SSM to run something on all compute nodes? Is there a tag for the EC2 instances that we could use?

**Comment by lukeseawalker** [comment]
Hi @calebwin,
we could use SSM to run commands on compute nodes as well. We can set tags through the configuration property [tag](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#tags), and then use the
`ssm send-command` specifying the tag key/value pair in the target parameter.

**Comment by calebwin** [comment]
Hmm.. I'm probably just confusing myself a bit but - if our sole goal is to install stuff to disk (packages, an interpreter, maybe some configuration files) and to be able to use the installed stuff from the compute nodes, shouldm't it be sufficient to SSM into the head node and run the commands their because of the shared file system?

**Comment by lukeseawalker** [comment]
@calebwin,
it really depends on which location you put the stuff on the head node. Not all the head node root volume is shared to the computes, but just `home` and the additional ebs volumes that you may have configured during cluster creation, see [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/ebs-section.html). Please also consider that other then sharing additional ebs through NFS, you can also use [EFS](https://docs.aws.amazon.com/parallelcluster/latest/ug/efs-section.html) or [FSx](https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html) file systems.

To give you an example, if you install a package through OS package manager in the head node, you will not find it installed in any of the compute.
Instead, if you have installed/unzipped/copied a package in one of the shared folder, or in a mount point backed by an EFS, you will be able to see the content in all the compute nodes as well.

L

**Comment by calebwin** [comment]
@lukeseawalker 

I see, thanks. Is there an EFS file system created by default? If not, what is the minimum I need to specify in my pcluster config file for one to be created? and how could I configure EFS so that using a package manager on the head node would result in packages being installed on all compute nodes?

Appreciate your help.

**Comment by lukeseawalker** [comment]
Hi @calebwin,
no EFS is created by default. To add an EFS to the cluster add [the relative setting](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#efs-settings) in cluster section and define an [EFS section](https://docs.aws.amazon.com/parallelcluster/latest/ug/efs-section.html) with the desired options.

> using a package manager

If you mean OS package manager, i.e. yum/apt, I'm not aware of any feature that would allow you to relocate the package installation to a different location. If you want to have same packages on head and computes, and those packages are installed through yum/apt, one other viable option would be to build a custom ParallelCluster AMI with the desired package already installed, see [doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html). This AMI will be used by 
 both head and compute nodes.
