### ISSUE TITLE
unable to read qmaster name from the jupyterhub with a new user

### ISSUE THREAD

**Issue by xuguorong2016** [aws/aws-parallelcluster#2561]
Hello,

I created a SGE cluster with ubuntu OS and I also installed jupyterhub on the master node. I am trying to submit a job from the jupyter notebook with different users (not ubuntu), but I got the error message that "Unable to initialize environment because of error: unable to read qmaster name: qmaster hostname in "/var/lib/gridengine/default/common/act_qmaster". But if I opened a terminal and ssh to the master node, I can submit a job to the cluster without any problem. Why not submit a job from the jupyter notebook? 

Your response would be really appreciated. 
<img width="1104" alt="Screen Shot 2021-03-22 at 10 19 01 PM" src="https://user-images.githubusercontent.com/19210374/112097838-fbf09700-8b5d-11eb-8b45-d770453f19c7.png">

**Comment by lukeseawalker** [comment]
Hi @xuguorong2016,
I'm not familiar with `jupyter notebook`.
As far I can see from the error, it's trying to look for `/var/lib/gridengine/default/common/act_qmaster`, but this is a wrong path, since the SGE installation done by ParallelCluster is located under `/opt/sge` and that particular file is located in `/opt/sge/default/common/act_qmaster`.

I would double check from where the `qsub` command is coming from, e.g. `which qsub`, and see which `$PATH` is set for the user executing that command.

L
