### ISSUE TITLE
Base AMI without CUDA/Nvidia drivers

### ISSUE THREAD

**Issue by keien** [aws/aws-parallelcluster#2568]
Is it possible to get a base AMI that doesn't have CUDA and Nvidia drivers pre-installed? We're struggling to get the p4d instances working using the existing Centos 7 image for v2.10.0 and our ML folks are saying that the way these are installed on the system is very nonstandard and confusing (not to mention not tracked by yum/rpm).

**Comment by lukeseawalker** [comment]
Hi @keien,
all the official ParallelCluster AMIs are shipped with Nvidia drivers preinstalled.
You could use the `pcluster createami` command to create a ParallelCluster-ized AMI on your own, starting from a vanilla CentOS7. In this case, when using the `createami` command, the Nvidia installation recipe is not executed.

That said I would like to understand more about the issues you are encountering with the provided installation.
We are using the official installation script from downloaded from [here](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/attributes/default.rb#L122) and executing it through [this command](https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.10.3/recipes/nvidia_install.rb#L37).

Thanks,
L

**Comment by keien** [comment]
Thanks, I'll give `createami` a try. Anything else I should know that is different between what gets installed with `createami` and what's in the base images?

The fact that it doesn't use a rpm-based install is an issue when we want to have multiple different CUDA version on the same machine and the rpms we try to install run into conflicts with the non-rpm files that are installed in the base image.

But that aside there seems to be something with the way this is installed that's not letting Tensorflow use the GPU on the A100s - I'll provide more details when our ML folks have a chance to dig in further.

**Comment by lukeseawalker** [comment]
> Anything else I should know that is different between what gets installed with createami and what's in the base images?

That should be the only difference, the [Nvidia installation recipe](https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.10.3/recipes/nvidia_install.rb) will be skipped.

> The fact that it doesn't use a rpm-based...

I see, one other alternative is to uninstall the drivers in advance, before you install yours. That should be doable passing the `--uninstall` flag to the Nvidia installer script.

**Comment by evren-cerebras** [comment]
@lukeseawalker it seems like the installer script is removed so we have not been able to uninstall the drivers before installing our own: https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.10.3/recipes/nvidia_install.rb#L38

more generally this is what we are trying to install:
`sudo yum install python3
sudo yum install python3-virtualenv
virtualenv-3.6 .venv
source .venv/bin/activate
pip3 install tensorflow-gpu==2.2`

Then we do 
`export LD_LIBRARY_PATH=/usr/local/cuda/lib64`

This fails when trying to use the GPU, we test that by launching python and running:
`import tensorflow as tf
tf.config.list_physical_devices('GPU')`
with error:
`2021-03-24 22:41:43.663012: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-03-24 22:41:43.667183: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_SYSTEM_NOT_READY: system not yet initialized
2021-03-24 22:41:43.667241: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ip-172-31-60-64.us-west-2.compute.internalcerebras.aws
2021-03-24 22:41:43.667252: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ip-172-31-60-64.us-west-2.compute.internalcerebras.aws
2021-03-24 22:41:43.667336: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 450.80.2
2021-03-24 22:41:43.667411: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 450.80.2
2021-03-24 22:41:43.667420: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 450.80.2`

We noticed that cudnn was missing, so we installed that both by rpm (which installs in /usr/lib64) and by copying the files from the tarball over to /usr/local/cuda/lib64 and /usr/local/cuda/include.  We get the same error message from TF.

TF is finding libcuda (from /usr/lib64) and the kernel versions (450.80.2) install in the root system.  But we think the issue is that other libraries, maybe cudnn or cublas, are not being found.

**Comment by enrico-usai** [comment]
Hi @evren-cerebras 

if you need to customize  the AMI you have a simple alternative that is to use [custom bootstrap action](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html), in this specific case maybe you can just add a `post_install` script to install the missing libraries.

If it's not enough I think the `createami` path is the best one to create your own custom ami. See full process [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html#build-a-custom-aws-parallelcluster-ami).

Let us know if it helps.

**Comment by keien** [comment]
Just to be clear, it's expected that cudNN is not installed as part of the base image? We're okay with doing our own custom image but we just want to understand what we should expect from the base image that you guys provide.

**Comment by tilne** [comment]
Correct, cudNN is not expected to be part of the base image.

**Comment by keien** [comment]
okay, thanks for the clarification

seems we're working our way through this slowly on our end, so I'll go ahead and close this
