### ISSUE TITLE
RFE: Allow machine names under 15 characters for AD join

### ISSUE THREAD

**Issue by kim0** [aws/aws-parallelcluster#2577]
By default compute nodes have really long host names. I would like to have those compute nodes automatically join active directory, bec that's where my users are! This setup roughly follows [these instructions](https://aws.amazon.com/blogs/opensource/aws-parallelcluster-aws-directory-services-authentication/). Unfortunately AD only supports 15-characters long maximum hostnames. Anything longer will get [truncated](https://pagure.io/SSSD/sssd/c/c6f1bc32774a7cf2f8678499dfbced420be3a3a1)

This is problematic, bec typically only the last 1 or 2 characters are what actually differ! Once they get truncated, all machines would be overwriting the same machine account which would break the whole setup.

Is there any possibility today to override the long (compute-st-c512xlarge-14) name into a more compact version like (csc5-14) ? I'm planning on using 2 queues (on-demand and spot), if it's possible, can you please show how this can be done for those 2 queues)

**Comment by lukeseawalker** [comment]
Hi @kim0,
unfortunately the compute node names are a critical part of the system and we cannot recommend a way to change it at the moment. The cluster logic relies on compute name to determine the queue, node type, and instance type information of a node.

**Comment by kim0** [comment]
Thanks @lukeseawalker .. I'm totally blocked if I cannot join AD though. I did some investigation work today, and could get short names working. The summary is below, can you please at least tell me if I'm missing something critical ? or I'm in a "This should work" territory. Thanks!

```
cd /opt/slurm/etc/

# cat pcluster/instance_name_type_mappings.json
{
    "t2large": "t2.large",
    "t2l": "t2.large"
}

# cat pcluster/slurm_parallelcluster_compute_partition.conf
# This file is automatically generated by pcluster

NodeName=compute-st-t2large-[1-1] CPUs=2 State=CLOUD Feature=static,t2.large,default
NodeName=c-dy-t2l-[1-9] CPUs=2 State=CLOUD Feature=dynamic,t2.large,default

NodeSet=compute_nodes Nodes=compute-st-t2large-[1-1],c-dy-t2l-[1-9]
PartitionName=compute Nodes=compute_nodes MaxTime=INFINITE State=UP Default=YES
```
And added a launch template with the needed name

**Comment by enrico-usai** [comment]
Hi Ahmed ,

The hostname is composed by `<QUEUENAME>-<st|dy>-<SANITIZED_INSTANCE_TYPE>-<NUMBER>` and the only way to reduce this lenght is by reducing the queue name.

You found the `instance_name_type_mappings` but we discourage to change it because it will be overrided in case of update of the cluster. To be sure they are always aligned you should modify it with a [post-install action](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html).

Anyway if you're using a custom AD and all your instances are resolvable by using your custom DNS domain you can disable the creation of the cluster DNS by setting the following parameters:
```
[cluster test]
disable_cluster_dns = true
extra_json = {"cluster": {"use_private_hostname": "true"}}
...
```
* `disable_cluster_dns` configuration parameter permits to disable the creation of the Route53 hosted zone.
* `use_private_hostname` is an internal parameters that permits to have the EC2 assigned hostnames for the compute nodes (i.e. `ip-<privateip>`, fqdn: `ip-<privateip>.ec2.internal`)

By using private hostnames you can save some characters, then you can use a subnet with a CIDR like 10.0.0.0/16, which would lead to hostnames as long as ip-10.0.255.254 (15 characters).

Let us know if it helps.

**Comment by enrico-usai** [comment]
>  don't know if this is expected, or can cause trouble later on. Please let me know. Any way to make it use the new names ?

It's expected, `sinfo` shows the Slurm NodeNames that we're configuring in the form `<QUEUENAME>-<st|dy>-<SANITIZED_INSTANCE_TYPE>-<NUMBER>`.

If you need to know other details (i.e. the NodeHostname) you can run the `scontrol` command, e.g.:
```
$ scontrol show nodes compute-st-t2xlarge-1 | grep NodeHostName
   NodeAddr=10.0.0.30 NodeHostName=ip-10-0-0-30 Port=0 Version=20.02.4
```

> Also, when an AD user submits a job, it seems to be stuck. My scripts do NOT join the head node to the AD. Not sure if this is what's causing the trouble.

It's not an issue because even when using default cluster DNS setup the head node is not part of the Route53 hosted zone domain. 

To debug what's happening to your compute node I'd take a look to `cloud-init.log` and `cloud-init-output.log` files of your compute instance. It can be an initialization problem due to the post-install script used to join the AD. You can find them in the [CloudWatch Dashboard](https://docs.aws.amazon.com/parallelcluster/latest/ug/cloudwatch-dashboard.html) or in [CloudWatch Logs](https://docs.aws.amazon.com/parallelcluster/latest/ug/cloudwatch-logs.html).

To have more insight about the output of the `sinfo` command in ParallelCluster integration you can take a look at this [Multiple queue mode tutorial](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorial-mqm.html).

Let us know if it helps.
