### ISSUE TITLE
Question: Exporting Fsx Lustre back to s3 on cluster destroy action

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2633]
Hi!

how can I set up synchronization of FSX Lustre to S3 using`export_path` as described  e.g. in  https://github.com/aws/aws-parallelcluster/issues/1795
so it can be triggered before `pcluster delete` action? 

The steps of the desired workflow:
1. Automatically import s3 bucket to FSX Lustre during `pcluster create test` process.
2. Use the `test` parallel cluster and optionally sync data to as described in https://github.com/aws/aws-parallelcluster/issues/1795
3. When the command `pcluster delete test` is called trigger FsX Lustre to S3 synchronization.

Thank you for any hints!

Ondra

**Comment by oplatek** [comment]
1. Is there `pre_destroy` parameter to register scripts to be launched? 
   With the same usage as `post_install` scripts.
2. Can you recommend to me a way how to get fsx_id of automatically created FSX Lustre during pcluster startup? 
   I need the fsx_id to use as a parameter in `aws fsx create-data-repository-task` call on the master node

**Comment by oplatek** [comment]
Linking relevant issue: https://github.com/aws/aws-parallelcluster/issues/2104

**Comment by lukeseawalker** [comment]
Hello @oplatek,
there are no hook that can be leveraged during cluster deletion time and I don't have good suggestions here.
Two hints that I can think of are:
* use epilog hook defined by Slurm. This of course doesn't apply for cluster deletion time, but for each job termination
* have a custom CloudFormation template that deploys a custom Lambda resource that is in charge to handle the CloudFormation stack deletion events. In the Lambda code you trigger the synchronization. This is a more involved workaround which I don't have personally tested.

For the question about how to get the `fsx_id` you can retrieve it by describing the stack resources.
Keep in mind that in order to do this operation it will be possible that you would need additional policies: 
for this purpose you can use the parameter [additional_iam_policies](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#additional-iam-policies) section of the 
 in the cluster config section.

**Comment by oplatek** [comment]
Thank you @lukeseawalker. Thank you for the tip about obtaining the `fsx_id` via stack resources.
