### ISSUE TITLE
Issues with forking and EFA

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#2835]
Hello,
I was wondering if v2.10.3 still uses EFA installer v1.11.2 or if it has been upgraded to 1.12.0. The reason is that I need the patch provided by 1.12.0 (https://github.com/ofiwg/libfabric/issues/6332) as I've faced issues when forking with EFA.
Thanks.

**Comment by demartinofra** [comment]
Yes versions 2.10.3 and 2.10.4 are both shipped with EFA 1.11.2. The upcoming 2.11.0 version will ship the latest available EFA.

**Comment by afernandezody** [comment]
Hi @**demartinofra**, 
Thank you for your reply. I have 2 follow-up qs:
1 - Could you share the ETA for the new release? It seems to be a major release so it's hard to guess based on past history.
2 - If the answer to the first questions is negative, I'd like to upgrade the fabrics myself. Does the configuration need anything else besides `./configure --prefix=/opt/amazon/efa --enable-efa`? My preliminary test seems to have been almost successful except that it has put the libraries at .efa/lib rather than at .efa/lib64 (which is odd being a CentOS system) and I'm not 100% sure if there are any other ramifications (that I cannot think of) by upgrading these components.

**Comment by demartinofra** [comment]
I don't have an exact date to share for ParallelCluster 2.11.0. What I can tell is that it is expected to be out within a week, at most 2.

If you want to upgrade EFA yourself by using a more recent installer my recommendation is to create a custom AMI with the newer version so that you don't need to repeat the installation for each compute node. A couple of ways to achieve that:
1. probably the simpler is to launch an ec2 instance that uses one of the ParallelCluster AMIs shipped with 2.10.3 or 2.10.4. Then install a newer version of EFA by following the [EFA docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-enable). Finally create a custom AMI out of it and use with ParallelCluster. You can follow the steps documented here: https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html#modify-an-aws-parallelcluster-ami
2. Use the `pcluster createami` and pass it a custom cookbook (`-cc`). Use as the custom cookbook the one corresponding to the release you are using and change the version of efa here: https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/attributes/default.rb#L156

**Comment by afernandezody** [comment]
Yes, I was talking about creating a custom AMI following method 1. I see that the main difference vs. my earlier attempt is the location of the installation files (https://efa-installer.amazonaws.com vs the more generic https://github.com/ofiwg/libfabric). Thanks.

**Comment by rexcsn** [comment]
pcluster v2.11.0 is released, which contains EFA installer v1.12.2.
Resolving the issue now, please let us know if you have any question, thanks!
