### ISSUE TITLE
Compute instance change broken

### ISSUE THREAD

**Issue by bwbarrett** [aws/aws-parallelcluster#310]
With CfnCluster 1.4.2, changing the compute instance type doesn't appear to work.  I built a cluster with compute node type `t2.small`, changed the config file to compute node `t2.large` and ran `cfncluster update <cluster name>`.  It looks like CloudFormation did something updating the ASG, but the instance type parameter (and the ASG instance type) didn't change.

**Comment by jmenbo** [comment]
@bwbarrett if you are using IAM roles to push the updates to your cluster, the issue you are experiencing might be related to this #276 I experienced that issue on 1.4.1 and fixed it adding the policies listed on my comments on #276

**Comment by enrico-usai** [comment]
This issue is solved. 
To have the new instance type you need to wait a new scaling up action.
I verified it locally and with a new integration test: https://github.com/aws/aws-parallelcluster/pull/982

It is also verified by the https://github.com/aws/aws-parallelcluster/issues/307#issuecomment-462215214
