### ISSUE TITLE
The compute node spun up and then terminated automatically

### ISSUE THREAD

**Issue by xuguorong2016** [aws/aws-parallelcluster#3113]
Hi parallelcluster team,

Recently I have two clusters and both got the same issue that the compute nodes can displayed in the console but not in the cluster (qhost doesn't show any nodes). The new created compute node is terminated after about a few minutes and then a new node is spun up. I checked the sqswatcher and I found it looks like it related to an empty SQS message. The parallelcluster cannot decode the json file correctly and throw an exception. Your response would be really appreciated. 

<img width="1717" alt="Screen Shot 2021-08-10 at 9 02 44 PM" src="https://user-images.githubusercontent.com/19210374/128968001-2dac5ae5-8547-4fd3-a5bd-0c30bc771e94.png">

**Comment by enrico-usai** [comment]
Hi @xuguorong2016 

to debug this issue we need more information, like:
- AWS ParallelCluster version:
- Full cluster configuration without any credentials or personal data
- [Optional] Arn of the cluster CloudFormation main stack
- Proper logs. We **STRONGLY** recommend following [this guide](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs) and attach the complete cluster log archive with the ticket, alternatively:
  - From Head node: `/var/log/jobwatcher`, `/var/log/sqswatcher`
  - From one of the failing compute nodes:`/var/log/nodewatcher`

Thanks

**Comment by xuguorong2016** [comment]
> Hi @xuguorong2016
> 
> to debug this issue we need more information, like:
> 
> * AWS ParallelCluster version: 2.10.3
> * Full cluster configuration without any credentials or personal data
> * [Optional] Arn of the cluster CloudFormation main stack
> * Proper logs. We **STRONGLY** recommend following [this guide](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs) and attach the complete cluster log archive with the ticket, alternatively:
>   
>   * From Head node: `/var/log/jobwatcher`, `/var/log/sqswatcher`
>   * From one of the failing compute nodes:`/var/log/nodewatcher`
> 
> Thanks

Hi Enrico,

Thanks for your reply!
The version of pcluster is: 2.10.3
The configuration file and the logs are attached for you. But the log for the failing compute nodes is not accessible because there is no node is accessed from the master node.
[config.txt](https://github.com/aws/aws-parallelcluster/files/6971780/config.txt)
[jobwatcher.zip](https://github.com/aws/aws-parallelcluster/files/6971777/jobwatcher.zip)
[sqswatcher.zip](https://github.com/aws/aws-parallelcluster/files/6971779/sqswatcher.zip)

Please let me know if you need anything else. Thanks!

**Comment by chenwany** [comment]
Hi Guorong,

Sorry for reply late.

Thank you for providing job watcher logs and sqswatcher logs! You are right that it is related to json decoding the SQS message.
The sqswatcher receive message from ASG and compute nodes.
From the logs you shared, there are 100 messages from SQS message. After that, there are errors with json decoding. It is not clear which message will lead to the problem. 
We want to learn more about why compute nodes are self terminate and which message are causing the error. I understand that it may not be easy to get compute node logs since they are terminated by ssh into them. Could you find the logs of compute nodes in cloudwatch logs if cloudwatch log is enabled? 
Another things can do that may helps to figure it out is to go to the simple service queue through aws console, go to the queue of the cluster and click on `poll for message` to see if there's some problematic message show up which indicates the error.

Thanks!

**Comment by tilne** [comment]
Guorong, have you found a solution to the issue you reported?
