### ISSUE TITLE
Question about limits on Pcluster

### ISSUE THREAD

**Issue by jandrovins** [aws/aws-parallelcluster#3205]
Hi! 

I have created a pretty expensive cluster on AWS with Parallel Cluster. I would like to know if there is any mechanism by which I could enforce a budget limit to the cluster, such that when trespassed then all instances of the cluster would be stopped (or terminated).

Is there anything like that ? I know I can configure budget actions [1] but, this only works to enforce limits over a single instance, not a hole cluster. Also, since instances are created dynamically, the Instance ID needed for the Budget Action would change constantly.

Any help or guide is greatly appreciated.

[1]: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/budgets-controls.html

**Comment by lukeseawalker** [comment]
Hello @jandrovins,
there isn't anything out of the box.
Closest solutions, even if don't satisfy your requirements, are to the usage of:
* budget limit, configured so that you receive a notification when threshold is reached. You can have a look at how it's implemented in this solution https://github.com/aws-samples/no-tears-cluster/
* cost explorer, you can enable cost allocation tags and track costs using Cost Explorer service

**Comment by lukeseawalker** [comment]
Another useful resource is this [blog post](https://aws.amazon.com/it/blogs/compute/using-cost-allocation-tags-with-aws-parallelcluster/)

**Comment by jandrovins** [comment]
Thanks a lot! Very useful resources.
