### ISSUE TITLE
Add nodes to cluster with no compute nodes, independent of auto-scaling rules

### ISSUE THREAD

**Issue by brainfood** [aws/aws-parallelcluster#344]
I configured a cfncluster with an initial_queue_size=1 and the following scaling rules:
```
scaling_threshold = 4
scaling_adjustment = 1
scaling_threshold2 = 10
scaling_adjustment2 = 2
scaling_period = 60
scaling_evaluation_periods = 5
scaling_cooldown = 300
```
The goal with this setup was to keep the cluster from scaling too quickly if there are light-weight jobs sitting in the queue that will all clear before the new node spools up completely, and to allow it to scale down completely once the current batch of jobs have finished. However, this leads to problems if the queue empties and the cluster scales down to 0 compute nodes (or if I launch a cluster with an initial_queue_size=0) and then I try to queue less than 4 jobs.

This could easily happen if I'm running software that works by starting a single master job, that then spawns and monitors other jobs. Unless that master job enters the running state, there won't be enough jobs in the queue to meet the scaling threshold and trigger the addition of compute nodes. I can get around this by submitting a bunch of dummy jobs that just run "ls" or "sleep", or by configuring the cluster so it always maintains a non-zero initial queue size. However, I was wondering if there was some other way to force cfncluster to add a new compute node when it currently has none? If not, I think this is an important feature worth building directly into cfncluster. It can help users minimize their compute costs without constant baby-sitting their clusters. Thanks.

**Comment by mohanasudhan** [comment]
As far I know, there is *no* way to meet your case in cfncluster. 

Problem:
You need slow scaleup behaviour ( by setting threshold = 4 ) under normal execution & at the same time you completely case-down when there is no job in queue ( maintain_initial_size = false). So restart back, you need 4 jobs in queue to get compute instance.

Suggestion:
Why don't you delete the cluster when there is no jobs in queue and recreate a new one as needed. I am not sure about your scheduling behavior and job nature, Just to thought to achieve the requested behavior today in cfncluster.

Request:
Will add to our request queue, We are planning to rework scaling behavior in near future. Will consider this request during rework.

**Comment by brainfood** [comment]
Thanks for your response and suggestion. Unfortunately that won't work for the use case that triggered this comment. I had a pipeline fail due to an error (that I was able to fix), and ran into this problem when I went to resume the pipeline. Restarting the cfncluster would have wiped out the data and progress I'd made on the pipeline thus far, so that wasn't an option. So for now, I'll just stick to queuing enough dummy jobs to hit the scaling threshold if I run into this situation. Thanks again.

**Comment by bwbarrett** [comment]
Which batch scheduler are you using?

If you're willing to work outside of CfnCluster a little bit, you should be able to build what you want.  http://cfncluster.readthedocs.io/en/latest/autoscaling.html is a pretty good primer on how autoscaling works.  And as both you and @mohanasudhan have pointed out, it doesn't handle your case of short jobs very well.  Scale-up is pretty simplistic; there's a cron job that runs once a minute that polls the queue length and publishes a metric.  Scale-down is also pretty simple: no jobs scheduled on a node *and* within the last 5 minutes of an hour (which is logic we need to change in the future, as EC2 has per-second billing).  As long as there's *at least one* job running on the instance, the instance will not scale down.

So, you could create a script that runs every 60 seconds on the master node and if there's at least one job, but less than 4 jobs, in the queue, directly set the ASG's `desired` count to `1`.  The instance won't scale down until there are no jobs in the queue and those jobs (once they start) won't count towards the scaling metric.  You would have to add `SetDesiredCapacity` to the IAM role used for the master server so that you don't need to authenticate for the script, but I think that would work.

**Comment by enrico-usai** [comment]
The scaling logic has been strongly refactored since CfnCluster 1.6.0.

Now there are no more _thresholds_ settings and the cluster will scale up/down according to the running/pending jobs.

Documentation:
https://aws-parallelcluster.readthedocs.io/en/v2.2.1/autoscaling.html
https://aws-parallelcluster.readthedocs.io/en/v2.2.1/configuration.html#scaling-section
