### ISSUE TITLE
Security vulnerabilty

### ISSUE THREAD

**Issue by haby0** [aws/aws-parallelcluster#3456]
What would be the right contact to report a security vulnerabilty? thanks!

**Comment by tilne** [comment]
Hi haby0, thanks for asking before posting. Let me bring this up with the team and get back to you tomorrow.

**Comment by tilne** [comment]
@haby0, you can report a security vulnerability using the processes described on [this page](https://github.com/aws/aws-parallelcluster/security/policy). I'm closing this issue because I think that page should have all of the information you'll need, but please re-open this if I can be of any more help.
