### ISSUE TITLE
Using a custom ec2 instance compute name

### ISSUE THREAD

**Issue by hsimran13** [aws/aws-parallelcluster#3569]
Hello,

I am using parallelcluster 3.0 and was wondering if there is a way for me to update the name of the compute ec2 instances in the AWS console.  Currently it seems to default to Compute but I would like to make it a bit more descriptive.  Is there a way to do this via tags?  I don't see a tags section for the slurm compute nodes so not sure if this is possible.  

Thanks,
-Simran

**Comment by hanwen-pcluste** [comment]
Hello Simran,

Unfortunately, there is no way to configure the name of the compute nodes. Could you tell us more about why a more descriptive name is useful for you. Would you have a custom name for all compute nodes, or different names for different compute nodes? Knowing your requirement would help us discuss the feature request.

Thank you,
Hanwen

**Comment by hsimran13** [comment]
Thanks Hanwen for your response.  I was hoping to have a more descriptive name for the compute nodes since they currently just show up as "Compute".  It would be good to easily identify the compute nodes belonging to a specific pcluster instance in the scenario that we have multiple clusters in the same account.  Also, we have a tagging convention for all of our ec2 instances that would be good to apply for any ec2 instance that is spun up by pcluster.  

Regards,
-Simran

**Comment by hanwen-pcluste** [comment]
`parallelcluster-cluster-name: <cluster-name>` tag is used to tag instances launched by ParallelCluster. You could filter the instances by the tag for instances belonging to a specific cluster
If you would include other tags on the instances, use the [`Tags` section](https://docs.aws.amazon.com/parallelcluster/latest/ug/Tags-v3.html).
However, I believe you cannot use the `name:` tag to overwrite the name of compute nodes, because ParallelCluster always set the tag for compute nodes to `Compute`. With the currently implementation, to change the compute nodes name, you have to manually modify the [launch templates](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html) created by ParallelCluster. If you would go down this path, I can give you more information.
Our team will discuss this feature request.

Thank you

**Comment by enrico-usai** [comment]
This is related to: https://github.com/aws/aws-parallelcluster/issues/3238

**Comment by enrico-usai** [comment]
The `Name` is a particular tag that can be easily modified by the user to identify a specific instance. 

ParallelCluster sets `parallelcluster:cluster-name` (V3) and `ClusterName` (V2) tags to all the instances.
We documented existing tags in official documentation:
* 2.x https://docs.aws.amazon.com/parallelcluster/latest/ug/resources-tags.html
* 3.x https://docs.aws.amazon.com/parallelcluster/latest/ug/resources-tags-v3.html

The usage of these tags with the possibility to add a new column in the AWS Console to show the tag values should solve this issue.

Thanks for your inputs.
