### ISSUE TITLE
Federated Requeue due to instance unavailability does not work

### ISSUE THREAD

**Issue by c200chromebook** [aws/aws-parallelcluster#3722]
**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 3.0.2
 - Full cluster configuration without any credentials or personal data
 - Cluster name: pcluster1b, pcluster1c

**Bug description and how to reproduce:**
Create two clusters, put them in a federation, submit jobs, have a job that ships to the secondary cluster, have that job fail for instance unavailability. The failed job will not requeue, and will get stuck in FedJobLock.

[logs.txt](https://github.com/aws/aws-parallelcluster/files/7962611/logs.txt)
[primary.txt](https://github.com/aws/aws-parallelcluster/files/7962612/primary.txt)
[secondary.txt](https://github.com/aws/aws-parallelcluster/files/7962613/secondary.txt)

**Comment by chenwany** [comment]
Hi,
From logs.txt, the cluster use p3.2xlarge as compute instance type, but there are insufficient capacity in the availability zone you are using. Can you switch to another availability zone with more capacity?

Are these two clusters have same node names? Can you unset `cloud_dns` in slurm.conf? It is possible that with cloud_dns enabled, federation between slurms on multiple ParallelCluster may become problematic as node names could collide.

Thanks

**Comment by c200chromebook** [comment]
So this is a thing that intermittently happens with GPU nodes - there's a shortage. Will try removing cloud_dns.

**Comment by c200chromebook** [comment]
Didn't seem to help the FedJobLock, sadly

**Comment by enrico-usai** [comment]
Hi @c200chromebook ,

The first thing I have to say is that Slurm Federation is not officially supported by ParallelCluster.
Anyway, I collected some information about it and `FedJobLock`.

Let's start from this interesting discussion we started with SchedMD:
> If the job fails at starting because nodes failed or couldn't be allocated (because of quota or stockout issues or something), the job gets requeued. At that point it retains the partition list originally requested. 
If the partitions are of the same priority tier, the partition that can run the job soonest will be chosen. So in your use case with cloud nodes and such, if Slurm thinks that original partition that first tried the job can run the job soonest, then it would try there again. The job would not cross partition barriers, only one partition is used.

Source: https://bugs.schedmd.com/show_bug.cgi?id=12849


Then there is the explanation of the `FedJobLock` reason:
> A federated job is submitted to each cluster in the federation. Then each cluster tries to schedule the job. 
But to avoid a split-brain situation where multiple clusters could start the job, the cluster attempts to get a "cluster lock" from the "origin cluster" -- cluster the job was originally submitted to. 
If it gets the lock then it will attempt to allocate resources for the job. Otherwise the scheduler will skip the job (the backfill scheduler will reserve resources for it and the main scheduler will just stop scheduling that partition). 
If it doesn't get the "cluster lock" from the origin cluster then it gets the FedJobLock reason.

Source: https://bugs.schedmd.com/show_bug.cgi?id=4388

Similar information are also reported in official [Slurm Federation documentation](https://slurm.schedmd.com/federation.html).

So according to the first link the job would be re-submitted in the same partition, but this didn't happen because for some reasons the secondary cluster didn't get the "cluster lock" from the origin cluster.
As we can see in the [Slurm code](https://github.com/SchedMD/slurm/blob/a8c6739d8be19dfdcafc750885573b9baa64cc8b/src/slurmctld/fed_mgr.c#L4529) there are some informative logs that could explain why this is failing.

My guess is that something wrong is happening with the iteration with `slurmdbd` daemon, that is important to manage the [shared information](https://slurm.schedmd.com/sacctmgr.html) in a Slurm federation.

Which guide are you following to setup the federation? Are sacctmgr and slurmdbd working correctly?

If you still have the clusters running it would be interesting to see the `slurmctld` logs of the two clusters. 
You could also add the `Federation` flag in the [`DebugFlags`](https://slurm.schedmd.com/slurm.conf.html#OPT_DebugFlags) configuration parameter of both the clusters.

Let us know if it helps.

Enrico
