### ISSUE TITLE
Timeout Errors (Create_Failed on MasterServer) with post install script. 

### ISSUE THREAD

**Issue by robgpita** [aws/aws-parallelcluster#3849]
After creating a new AWS Parallel Cluster, I'm getting the error `The following resource(s) failed to create: [MasterServer].` from the CloudFormation logs and pcluster cli output.

The issue is that I have a post install script that takes around 1.5 hours to complete. This script does run to completion, but the PCluster status is `CREATE_FAILED - - AWS::EC2::Instance MasterServer Failed to receive 1 resource signal(s) within the specified duration.`

So I know that I need to modify the Timeout line from the default CloudFormation Template to PT130M,

```
Resources:
  MasterServer:
   ......
     CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT130M
```

I've uploaded that file to an s3 bucket with public access, and specified it as the value for the `template_url ` paramater in my pcluster config file successfully. The problem I have now is that there are a whole lot of other parameters needing values in the `template_url` file which I believe are populated behind the scenes (or atleast are not explicit in the pcluster config file) with` pcluster create`.

Is there any way to get/find the CloudFormation template created from the "failed" cluster to pass as the `tempalate_url` in the pcluster config? Maybe this could be a feature request if not.

Is there a way to only update that one value (`Timeout`) in a CloudFormation Template, while keeping the rest as default? Being able to configure the timeout value from pcluster would be great. 

I did notice there was a [recent commit](https://github.com/aws/aws-parallelcluster/commit/bcd602c8eb4506a10501e97c4f64b38647bb6596) to PCluster v 2.11-release with a modification similar to what I need, but I'm unsure how to go about using that source code in my local `/.parallelcluster`. Also, not even sure if that would work, as I need around 1:30 mins of timeout.

**Comment by chenwany** [comment]
Hi Rob,

There is [an uploadTemplate.sh utility script](https://github.com/aws/aws-parallelcluster/blob/release-2.11/util/uploadTemplate.sh) that automatically performs the replacement of the substack url according to the bucket on which you're uploading the template.

If you want to increate the timeout, in your local `/.parallelcluster`, you need to modify the Timeout in `master-server-substack.cfn`, then use the script `uploadTemplate.sh`, it will automatically upload the template to your s3 bucket. Then you can create the cluster with settings like:
```
template_url = https://${_s3_folder_url}/aws-parallelcluster.cfn.json
hit_template_url = s3://${_bucket}/${_templates_folder}/compute-fleet-hit-substack.cfn.yaml
cw_dashboard_template_url = s3://${_bucket}/${_templates_folder}/cw-dashboard-substack.cfn.yaml

```

When you hit the timeout issue `CREATE_FAILED - - AWS::EC2::Instance MasterServer Failed to receive 1 resource signal(s) within the specified duration`, please also check if it is networking issue. For example, check if the subnet, security group is setup correctly.

Let us know if it works for you.

Thanks 
Wanyi

**Comment by chenwany** [comment]
Thanks for suggesting about configuring the timeout value from pcluster.
In ParallelCluster3, we are going to make Timeout Configurable for both Headnode and Computenode. [It](https://github.com/aws/aws-parallelcluster/commit/d4b2b5d62ad12ccfc74fd7fa207a7378bbd8708c) is already in develop branch

**Comment by robgpita** [comment]
@chenwany Thanks for the reply! I was not aware of the `uploadTemplate.sh` script. Once y'all have the Timeout configurable in ParallelCluster3, that might be reason enough for me to switch over.  In the interim, how would I go about finding and modifying the Timeout Value in`master-server-substack.cfn` in my local `/.parallelcluster` ?

**Comment by enrico-usai** [comment]
Hi @robgonzalezpita in [ParallelCluster 2.11.5](https://github.com/aws/aws-parallelcluster/releases/tag/v2.11.5) we extended the timeout of the head node to 1h, so if you're going to create a new cluster it might be enough to upgrade the cli to the latest 2.11 version and create a new cluster with it.
```
pip install aws-parallelcluster=2.11.5
```

If you need to stay with your CLI version and you want to modify the template, you have to search for `Timeout: PT30M` in the `cloudformation/master-server-substack.cfn.yaml` file. 

The value must be in [ISO8601 duration format](http://en.wikipedia.org/wiki/ISO_8601#Durations), in the form: PT#H#M, where each # is the number of hours and minutes, respectively. For best results, specify a period of time that gives your instances plenty of time to get up and running. A shorter timeout can cause a rollback.

You can take as reference at the patch we did to increase the timeout in ParallelCluster 2.11.5: https://github.com/aws/aws-parallelcluster/pull/3812/files

Enrico

**Comment by enrico-usai** [comment]
Hi @robgonzalezpita as you already discovered in [ParallelCluster 2.11.5](https://github.com/aws/aws-parallelcluster/releases/tag/v2.11.5) we extended the timeout of the head node to 1h, so if you're going to create a new cluster it might be enough to upgrade the cli to the latest 2.11 version and create a new cluster with it.
```
pip install aws-parallelcluster=2.11.5
```

If your instance initialization takes so long I'd suggest you to create a custom AMI with one of the approaches suggested here: https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html

This will speed up cluster creation and this is strongly suggested if you're executing this kind of initialization steps to all the compute nodes too, because each new node will have to take 1h30m to be ready to submit a job.
By creating a custom AMI all the required software will be in the instance and cluster creation and new compute nodes initialization will be faster.

If you don't want to use the custom AMI approach and you want to modify the template, you have to checkout the cli source code and switch to the code related to your cli version, by using the right tag.

Please replace v2.11.4 tag with your cli version in the following commands.
```
git clone https://github.com/aws/aws-parallelcluster
cd aws-parallelcluster
git fetch origin
git checkout tags/v2.11.4 -b v2.11.4
```

Search for `Timeout: PT30M` in the `cloudformation/master-server-substack.cfn.yaml` file and replace it.

The value must be in [ISO8601 duration format](http://en.wikipedia.org/wiki/ISO_8601#Durations), in the form: PT#H#M, where each # is the number of hours and minutes, respectively. 

Then you can execute the uploadTemplate.sh script to have your modified templates in your S3 buckets. In the output of the uploadTemplate.sh command you'll find the instructions to use the new template.

Enrico
