### ISSUE TITLE
Service: AmazonEC2; Status Code: 400; Error Code: InvalidNetworkInterface.InUse

### ISSUE THREAD

**Issue by cnvsuresh** [aws/aws-parallelcluster#4063]
Hi,

I'm facing an issue while updating the cluster. 
This update included some more compute nodes. Other than that didn't modify any other configuration. 

While updating the issue like this

`
Interface: [eni-XXXX] in use. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidNetworkInterface.InUse Request ID: XX-XX_XX; Proxy: null)
`

PCluster Version: 3.1.2

**Comment by cnvsuresh** [comment]
I've found something related to this issue from your resolutions. But that's related to the older version. Because of that reason raised a new request. 

Older Issue
https://github.com/aws/aws-parallelcluster/issues/623

**Comment by enrico-usai** [comment]
Hi @cnvsuresh,
thanks for opening the issue, this shouldn't happen when modifying compute nodes settings.

Could you provide your cluster configuration (without private data) and clarify which parameter did you modify in the config? I'd like to have all the details to try to replicate the issue.

It would be helpful to have CLI logs `~/.parallelcluster/pcluster-cli.log` too, because they should contain the details of the configuration and the steps you performed from the CLI point of view.

Enrico

**Comment by snemir2** [comment]
this issue same as https://github.com/aws/aws-parallelcluster/issues/6339#issue-2399268247
The only changes are to the custom scripts -- and it failed before the script even was called.
