### ISSUE TITLE
encrypted_ephemeral in ParallelCluster 3.x.x

### ISSUE THREAD

**Issue by WajdiH** [aws/aws-parallelcluster#4152]
Hi aws-parallelcluster team,

I am using "encrypted_ephemeral =true" -using LUKS- in ParallelCluster 2 but I don't see the equivalent of this in ParallelCluster 3.x.x  in the EphemeralVolume section. Is encrypted_ephemeral not supported in ParallelCluster 3?

I am also using a custom AMI built on the top of an aws-parallelcluster AMI that will be deprecated in september 2022, does that mean that my cluster will not run properly and I will no longer be able to use my custom AMI to build new clusters ( with ParallelCluster 2).

Thanks

**Comment by demartinofra** [comment]
Hi,

As reported in the changelog in ParallelCluster 3 we disabled software encryption for instance store and we are relying on default hardware encryption provided by NVMe instance store volumes:

> Remove instance store software encryption option (encrypted_ephemeral) and rely on default hardware encryption provided by NVMe instance store volumes.

More details can be found here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ssd-instance-store.html

> The data on NVMe instance storage is encrypted using an XTS-AES-256 block cipher implemented in a hardware module on the instance. The encryption keys are generated using the hardware module and are unique to each NVMe instance storage device. All encryption keys are destroyed when the instance is stopped or terminated and cannot be recovered. You cannot disable this encryption and you cannot provide your own encryption key.

Regarding AMI deprecation, we are going to remove the deprecation policy for official ParallelCluster AMIs so that users are still able to use them, however we strongly recommend to upgrade to newer versions. According to our [support policy](https://docs.aws.amazon.com/parallelcluster/latest/ug/support-policy.html), to receive bug and security fixes you must upgrade to a version that hasn't reached EOL.

Also since you are using a custom AMI you own, controlling the deprecation policy for such AMI is in your control. You are still able to use a custom AMI if you remove the deprecation policy regardless of the deprecation policy of the parent AMI.

Hope that helps.

**Comment by WajdiH** [comment]
Thank you very much for the prompt and detailed response.
