### ISSUE TITLE
hpc workshop distributed ML multiple errors

### ISSUE THREAD

**Issue by charlescurt** [aws/aws-parallelcluster#4265]
I am working through this workshop https://www.hpcworkshops.com/09-ml-on-parallelcluster.html, and all has been going well until the final part for distributed ML.

1. There is a typo and outdated instance in "b. Create a distributed ML cluster"
```
     Dcv:
        Emabled: true
```
_p3dn.24xlarge_ no longer exists as an available instance type.

2. After fixing these errors, I get new errors for a "S3BucketUriValidator error" for permissions to my s3 bucket, which I cannot get past in the manager UI no amount of permission adding helps.

3. I can however deploy this through the command :
`pcluster create-cluster --cluster-name ml-cluster -c ml-config.yaml`
When deployed and try to run the preprocess step I then end up with this new issue:
```
srun --exclusive -n 1 preprocess.sh
srun: Force Terminated job 1
srun: error: Node failure on compute-dy-p4d24xlarge-1
srun: error: Job allocation 1 has been revoked
```

Please let me know if there is more updated documentation around this, as I am very interested in distributed ML on the platform.

**Comment by enrico-usai** [comment]
Hi @charlescurt thanks for your input.

The right place to open issues related to HPC workshop is this GitHub repo: https://github.com/aws-samples/aws-hpc-tutorials

To understand the issue within your running cluster could you please share your cluster configuration and the following logs from the Head node: `/var/log/parallelcluster/clustermgtd`, `/var/log/parallelcluster/slurm_resume.log` and`/var/log/slurmctld.log`.  

I guess it might be a p4d.24xlarge capacity issue. Let's check.

**Comment by charlescurt** [comment]
I saw the logs you are correct it is a capacity issue. However, I cannot find an instance that exists, has the capacity or doesn't give a "NameValidator" error. 

Looking through the accelerated computing that supports EFA from this list I cannot use any of them. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types

I want an instance that uses EFA is there a specific region I should be using to better support hpc?

**Comment by enrico-usai** [comment]
You can do a first check for the capacity by manually launching an instance through AWS Console.

The `NameValidator` issue let me think to a typo in the configuration file, can you share it?
My guess is that you're modifying the [`Name`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeResources-Name) field of the `ComputeResource` item, rather than changing the [`InstanceType`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeResources-InstanceType).

We can check together by looking at your configuration file.
