### ISSUE TITLE
Compute node init hangs at "Processing ruby_block[retrieve compute node info]"

### ISSUE THREAD

**Issue by rems0** [aws/aws-parallelcluster#4364]
Hi all,

 - AWS ParallelCluster version [e.g. 3.1.1]: 3.2.0

 - Full cluster configuration without any credentials or personal data.
[C8-Cluster-config.yaml.txt](https://github.com/aws/aws-parallelcluster/files/9628889/C8-Cluster-config.yaml.txt)

 - Cluster name: C8-Cluster

 - Output of `pcluster describe-cluster` command.
[pcluster-describe-cluster.txt](https://github.com/aws/aws-parallelcluster/files/9628866/pcluster-describe-cluster.txt)

 - [Optional] Arn of the cluster CloudFormation main stack:
arn:aws:cloudformation:eu-west-1:266227821648:stack/C8-Cluster/34f88530-3a8f-11ed-a3fd-062dd99715a1

**Bug description and how to reproduce:**

This is the first job test after creating the cluster.
Started on the headnode:
sbatch --wrap 'sleep 1h'

A compute node gets started but setup hangs at:
  * ruby_block[retrieve compute node info] action run[2022-09-22T19:23:08+00:00] INFO: Processing ruby_block[retrieve compute node info] action run (aws-parallelcluster-slurm::init line 31)
[2022-09-22T19:33:20+00:00] INFO: Retrying execution of ruby_block[retrieve compute node info], 4 attempts left

* From Head node: `/var/log/cloud-init.log`, `/var/log/cfn-init.log` and `/var/log/chef-client.log`
[headnode-cloud-init.log](https://github.com/aws/aws-parallelcluster/files/9628978/headnode-cloud-init.log)
[headnode-cfn-init.log](https://github.com/aws/aws-parallelcluster/files/9628982/headnode-cfn-init.log)

* From Compute node:  `/var/log/cloud-init-output.log`.
[compute-cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/9628948/compute-cloud-init-output.log)

Kind regards and thanks,
Richard

**Comment by enrico-usai** [comment]
Hi @rems0 

thanks for providing all the requested info.
The compute nodes are unable to contact DynamoDB and this is probably due to network settings.

I see you're using the same subnet: `subnet-067f3bb147dbda058` for both head node and compute.

Mi guess is that you're using a public subnet (a subnet with an Internet Gateway) but you don't have "Auto-assign public IP" so the compute nodes are unable to reach internet.

When using a subnet with an Internet Gateway all the nodes **must** have a public IP associated to it.
If you don't want a public IP for the compute nodes you should move the compute nodes into a private subnet (you can use `pcluster configure` to create your subnet pairs).

See https://docs.aws.amazon.com/parallelcluster/latest/ug/network-configuration-v3.html#network-configuration-v3-two-subnets

**Comment by rems0** [comment]
Hi Enrico,

Yes! That was it, thanks!
And sorry for the noise. PEBKAC here.

Thanks again,
this is no bug and can be closed.

Kind Regards,
Richard
