### ISSUE TITLE
FSx performance optimization

### ISSUE THREAD

**Issue by mcb-silverlining** [aws/aws-parallelcluster#4476]
The FSx lustre documentation shows some performance improvement tips for large instances. Hpc6a qualifies. Have these been included with parallelcluster by default? Thanks

https://docs.aws.amazon.com/fsx/latest/LustreGuide/performance.html#performance-tips

**Comment by hanwen-pcluste** [comment]
ParallelCluster does not include the performance settings mentioned above because they are better suited to a few large Luster clients (more than 64 GiB memory or 64 CPU cores). Contrary to this, with too many clients or a smaller file system, these settings could overload the file system making these settings counterproductive.

If you would apply the performance tips, please follow [our guide](https://docs.aws.amazon.com/parallelcluster/latest/ug/custom-bootstrap-actions-v3.html) to use `OnNodeConfigured` `CustomActions`
