### ISSUE TITLE
Feature request: Specify custom AMI when launching SLURM jobs

### ISSUE THREAD

**Issue by srdecny** [aws/aws-parallelcluster#4494]
I know this sounds really weird, but I woud like to have an option to specify an AMI to be used when launching a job via SLURM. I assume it's just a question of modifying some parameter when using the EC2 API, so it should be possible, but I could be mistaken.

The use case for this is to be able to have an immutable environment for the compute nodes. For example, you want to run some jobs with a particular stack and other jobs with another, different stack. The exact dependencies and versions of these stacks also change frequently, so it isn't feasible to update the `pcluster` configuration over and over again, while having a single AMI that grows larger and larger.

I am aware this is a problem that can be entirely solved client-side via docker, but only to a point -- if the docker images grow too large and the amount of compute nodes too high, this is no longer a feasible approach. For example, while using AWS EC2, I get 10 MB/s download speed when running `docker pull`, which is just too slow when the image is 10GB large. And it's also really wasteful, downloading the same image over and over again, when it could just be baked in the AMI. Hence this feature request.

**Comment by enrico-usai** [comment]
Hi @srdecny

ParallelCluster permits to configure a different [`CustomAmi`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-Image-CustomAmi) for each queue.

At `pcluster update` you could update only the AMIs of the queues you want to change.
It's also possible to use the [`QueueUpdateStrategy`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmSettings-QueueUpdateStrategy) option to automatically DRAIN your compute nodes after the cluster update, when they complete the running jobs.

An alternative solution is to use a different [`OnNodeConfigured`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-CustomActions-OnNodeConfigured) custom bootstrap script for each queue, rather than using different CustomAMIs. 
You can update the bootstrap script directly from S3 and all the new nodes will use it, without requiring a cluster update.

Let us know if this helps.
Enrico

**Comment by srdecny** [comment]
@enrico-usai 
Ideally, I would be able to run a job with some AMI and then run another job with another AMI, without having to mess around with the pcluster config in between. I am aware of the postinstall script, but that isn't really feasible when installation of the dependencies takes e.g. tens of minutes.

**Comment by demartinofra** [comment]
@srdecny we do understand the use case and we will account for your precious feedback in future iterations. However with the current design we want to guarantee a certain degree of homogeneity and reproducibility for jobs that land in the same partition. For that we don't really allow the selection of per job features but rather let you configure multiple partitions that can satisfy heterogenous use cases.

To reduce the number of AMIs you'd require have you considered installing the software in a shared storage so that you don't need to create specialized AMI every time? This should also reduce the effort coming from managing many different AMIs.
