### ISSUE TITLE
Add a second node type: submission host

### ISSUE THREAD

**Issue by cancan101** [aws/aws-parallelcluster#47]
Add a second node type: submission host, that is not the SGE master not a compute node, but can be used for job submission.

**Comment by dougalb** [comment]
Could you please provide more background to this request? Typically CfnCluster is deployed on a per user, project or team and doesn't require dedicated submission hosts as seen with on-premise shared cluster architectures.

**Comment by chambm** [comment]
I'd like to see this too. I'm setting up a workflow management system on an ECS-based server which needs to be able to submit jobs via DRMAA to a HPC scheduler. That server needs to be a submit host to submit jobs to the cfncluster's master node. I am struggling to set this up manually. I failed with SLURM, and am having trouble with SGE. But I now realize the SGE problems are due to mismatched versions between the workflow server and HPC master, so perhaps that was causing SLURM to fail as well.

**Comment by dougalb** [comment]
@chambm Not clear how an additional node in CfnCluster will help you configure an ECS Task that is able to submit to CfnCluster however happy to discuss offline how you can achieve this setup. Please email me dougalb at amazon dot com and we can discuss.

**Comment by enrico-usai** [comment]
This FE can be closed, since we added Login Nodes as part of [3.7.0 release](https://github.com/aws/aws-parallelcluster/releases/tag/v3.7.0)
