### ISSUE TITLE
initial_queue_size and cfncluster update --reset-desired

### ISSUE THREAD

**Issue by wjaskowski** [aws/aws-parallelcluster#574]
I have `initial_queue_size=2` in my config. No jobs, so after some time of inactivity, the computational nodes go down as expected. Then I want them back so I execute:
```
> cfncluster update --reset-desired cluster
Updating: cluster
No updates are to be performed.
```
But the effect is not the desired one. A workaround is to artificially set `initial_queue_size=1`, then do the update, set `initial_queue_size=2` back and update again. Seems like a bug.

**Comment by sean-smith** [comment]
The ASG desired is updated outside of the CloudFormation template, thus cloudformation doesn't track that change and doesn't do an update (since in it's mind nothing has changed).

Using `cfncluster update` is the wrong approach here. You can adjust the desired value in the EC2 AutoScaling Console, via the aws CLI, or by submitting a job and waiting for it to scale up.

To do so via the aws cli, start by grabbing the asg name from the ec2 console in the AutoScaling section. It'll follow the pattern `cfncluster-[cluster_name]-ComputeFleet-[hash]`. Then you can run:

```bash
aws autoscaling set-desired-capacity --auto-scaling-group-name [ASG_NAME] --desired-capacity 2
```

You can do this on the Master Instance, or on any machine that has the iam permissions `autoscaling:SetDesiredCapacity `.

**Comment by wjaskowski** [comment]
Thank you for the explanation. I am just pointing out that from a cfncluster user perspective, who does not need to understand the whole stack, the behaviour looks inconsistent.
