### ISSUE TITLE
Custom AMI for Ubuntu 22.04 failing

### ISSUE THREAD

**Issue by kaisenl** [aws/aws-parallelcluster#5746]
I'm using the vanilla Ubuntu 22.04 AMI in us-west-2 to create a custom AMI so my image configuration looks like:

```
Build:
  ParentImage: ami-03f65b8614a860c29
  ...
```

I'm using pcluster 3.7.1 and when I run `pcluster build-image`, it will say build in progress, but eventually the CloudFormation stack will fail. Some logs in CloudWatch say:

```
FATAL: Chef::Exceptions::Package: lustre[Install FSx options] (aws-parallelcluster-environment::install line 22) had an error: Chef::Exceptions::Package: apt_package[lustre-client-modules-5.19.0-1025-aws, lustre-client-modules-aws, initramfs-tools] ((eval) line 27) had an error: Chef::Exceptions::Package: No candidate version available for lustre-client-modules-5.19.0-1025-aws
```

Not sure if this is related, but https://docs.aws.amazon.com/fsx/latest/LustreGuide/install-lustre-client.html#lustre-client-matrix shows that Ubuntu 22.04 has a max kernel version for Lustre that is lower than the AWS Ubuntu 22.04 kernel version.

**Comment by dreambeyondorange** [comment]
That is correct. You cannot update the image because lustre does not have a client for kernel 5.19. You need to use a version of Ubuntu 22 that uses a compatible kernel

Also make sure the below config option is set to false.   It is by default
https://docs.aws.amazon.com/parallelcluster/latest/ug/Build-v3.html#Build-v3-UpdateOsPackages 

Once lustre has a compatible version, we will update the PCluster images

**Comment by kaisenl** [comment]
Thanks! The workaround for anyone else who runs into this is to use the alternate method of building custom AMIs: https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html#modify-an-aws-parallelcluster-ami-v3 with the Ubuntu 22 AMI via `pcluster --list-official-images`
