### ISSUE TITLE
SGE Security

### ISSUE THREAD

**Issue by cancan101** [aws/aws-parallelcluster#664]
Right it looks like the default and only option is to [make all compute nodes submit hosts and administrative](https://github.com/awslabs/cfncluster-node/blob/484b4699a857ff0bc0577cc935f4a97c14709a3e/sqswatcher/plugins/sge.py#L37-L42) hosts.

Ideally there would be some way to lock down privileges on the computer nodes, for example to prevent malicious programs that have been submitted from gaining admin access to the entire cluster. 

docs are provided here: http://arc.liv.ac.uk/SGE/howto/sge-security.html for securing a cluster and I would suggest at least linking to them if not also making of these settings default

**Comment by demartinofra** [comment]
Because we have announced that we will be deprecating support for SGE in the near-future (see: https://github.com/aws/aws-parallelcluster/wiki/Deprecation-of-SGE-and-Torque-in-ParallelCluster), we will not be performing additional enhancements specific to SGE.

I am going to close this issue. If you would like to request a similar enhancement for one of our other supported schedulers (Slurm or AWS Batch), please feel free to create a new issue.
