### ISSUE TITLE
Cannot create custom aliases (ie. put/get)

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#906]
Cannot create custom aliases (ie. put/get)

The following configuration results in the error: "pcluster: error: argument command: invalid choice: 'put'"

```
[aliases]
ssh = ssh -i ~/key.pem {CFN_USER}@{MASTER_IP} {ARGS}
put = scp -i ~/key.pem {ARGS} {CFN_USER}@{MASTER_IP}:~/
get = scp -i ~/key.pem {CFN_USER}@{MASTER_IP}:~/{ARGS} .
```

**Comment by sean-smith** [comment]
Hi @RickoLacharity 

This isn't currently supported. You can modify the `ssh` command but not the others... If you want to open a pull request to do this, you'd start by modifying the `cli/pcluster/cfnconfig.py` file. Follow the ssh example. Thanks!

**Comment by RickoLacharity** [comment]
This functionality did work and was broken in commit: fb23bf184b983a5af39315549d2ff100930dfac1 with a change from `parse_args` to `parse_known_args` in cli.py.

**Comment by sean-smith** [comment]
@RickoLacharity yep, I wrote that commit initially with the intent to support other use cases, such as what you've added with `put` and `get`. However, there's a catch 22 in this, one of the cli options, `--config`, needs to be parsed before reading from the config file. Since the extra commands (such as `put` and `get`) are included in the config file, we need to parse the config before parsing the cli, and we can't parse the cli with parsing the config.

A solution is to just add `put` and `get` as command line options. For example, `put` would look like:

```
pput = subparsers.add_parser(
        "put",
        help="Connect to the master instance and copy a file into the home directory.",
        description="Run scp command with the cluster username and IP address pre-populated. "
        "Any arguments provided are used as flags and local file location."
        "This command may be customized in the aliases "
        "section of the config file.",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    pssh.add_argument("cluster_name", help="name of the cluster to connect to")
    pssh.add_argument("-d", "--dryrun", action="store_true", default=False, help="print command and exit")
    pssh.set_defaults(func=command)
``` 

I'd be happy to review a pull request with this functionality. Feel free to add this to cli.py
