### ISSUE TITLE
qhost nodes missconfigured after `pcluster update`

### ISSUE THREAD

**Issue by joamatab** [aws/aws-parallelcluster#950]
When I update the number of nodes, for example going from queue size 0 to 1, or changing the nodes size from c5.2xlarge to c5.4xlarge and updating the cluster
$ `pcluster update cadclustercentos`

$ `qhost` did not reflect the changes, so I had to delete and create the cluster again
 how can I reset the connections on the Master after updating the cluster config?

pcluster version: 2.2.1
OS: centos7

[scaling custom]
scaling_threshold2 = 3
scaling_adjustment2 = 8

[cluster oregon]
vpc_settings = vpc_oregon
key_name = joaquin_oregon
master_root_volume_size = 200
compute_root_volume_size = 30
initial_queue_size = 1
max_queue_size = 8 
maintain_initial_size = true
master_instance_type = c5.2xlarge
compute_instance_type = c5.4xlarge
scaling_settings = custom
base_os = centos7
cluster_type = spot
spot_price = 1.50

**Comment by sean-smith** [comment]
Hi @joamatab 

We're aware that the `pcluster update` doesn't update the nodes added to the SGE scheduler and we're working on a fix. For now you can delete and re-create when you need to switch to a new instance type. 

For scaling, you can just update your autoscaling group. Go to the EC2 Console > Auto Scaling Groups > parallelcluster-[cluster name] and edit the desired:

![image](https://user-images.githubusercontent.com/5545980/55115207-2f000d00-50a1-11e9-851d-e37d7a11775c.png)

The host will automatically get added to the scheduler in a few minutes.

Note, due to how the autoscaling group update works, you won't actually get new instance types until there's some sort of scaling behaviour. This is because only new nodes are launched with the updated Launch Template. See [AutoScaling docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-launchtemplate)

**Comment by enrico-usai** [comment]
Hi @joamatab, some additional comments:
1. You can remove your existing compute instances by adding the `--reset-desired` flag to the `update` command:
https://aws-parallelcluster.readthedocs.io/en/latest/commands.html#update
1. You are using the old scaling configuration parameters: `scaling_threshold2`, `scaling_adjustment2`, you should instead use the `scaledown_idletime` parameter:
https://aws-parallelcluster.readthedocs.io/en/latest/autoscaling.html
https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#scaling-settings
