### ISSUE TITLE
VPC setup when use_public_ips is set to false

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#968]
**Environment:**
 - AWS ParallelCluster: 2.2.1
 - OS: ubuntu1604
 - Scheduler: slurm
 - Master instance type: t2.medium
 - Compute instance type: t2.medium

**Bug description and how to reproduce:**
Are there any examples on VPC setup when use_public_ips is set to false? When I set `use_public_ips=false` along with default vpc, cluster formation is stuck at `AWS::AutoScaling::AutoScalingGroup | ComputeFleet`. 

We are spinning up multiple clusters and running out of elastic IP limits. I don't need compute instances to have public IPs. Network configuration documentation says

_With use_public_ips set to false The VPC must be correctly setup to use the Proxy for all traffic. Web access is required for both Master and Compute instances._

Appreciate any pointers!

Thanks
Santi

**Comment by sean-smith** [comment]
Hi @adavanisanti,

This is rather confusing and we'll update the docs to make it clearer. To make this work, you'll need a public and private subnet, the private subnet requires a NAT gateway. To create these subnets do:

1. In the [VPC Dashboard](https://console.aws.amazon.com/vpc/home) , click "VPC Wizard"

![image](https://user-images.githubusercontent.com/5545980/55517061-0d180480-5624-11e9-8e6a-ce34615ad79c.png)

2. Select the second tab "VPC with Public and Private Subnets"

![image](https://user-images.githubusercontent.com/5545980/55517117-35076800-5624-11e9-84e1-6932c5bf306e.png)

3. Create the VPC, giving it a name, like `public-private`:

![image](https://user-images.githubusercontent.com/5545980/55517284-caa2f780-5624-11e9-9002-7ec7551172ed.png)

4. Enable "Auto-assign public ip's" on the `Public Subnet`.

![image](https://user-images.githubusercontent.com/5545980/55517368-135ab080-5625-11e9-9de2-e099262d0627.png)

5. From your `~/.parallelcluster/config` file add a vpc section that includes your newly created vpc and subnets, and reference it in your cluster section:

```
[cluster mycluster]
...
vpc_settings = public-private

[vpc public-private]
vpc_id = [VPC you created]
master_subnet_id = [Public Subnet]
compute_subnet_id = [Private Subnet]
use_public_ips = false
```

6. Create the cluster! When you ssh in, you'll need to grab the public ip from the EC2 console, rather than `pcluster ssh cluster`.
